window.REHAB_DATA = [
    {
        "id": "1",
        "district": "도담동",
        "name": "세종충남대학교병원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "급성기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 소아재활, 스포츠 손상, 근골격계 재활",
        "specialty": "대학병원급 다학제 협진 / 소아재활센터 / 산재 지정",
        "recovery": "해당없음",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "세종특별자치시 보듬7로 20 (도담동)",
        "phone": "1800-3114",
        "sources": "https://www.cnush.co.kr/",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "세종시 유일의 국립대 종합병원. 최첨단 재활 로봇 및 소아 재활 전문 치료실을 갖추어 급성기 및 고난이도 재활 치료에 강점을 보입니다."
    },
    {
        "id": "2",
        "district": "나성동",
        "name": "NK세종병원",
        "type": "병원",
        "inclusion": "병원급 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "수술 후 집중재활, 뇌혈관 질환 후유증, 척추·관절 재활",
        "specialty": "24시간 응급실 운영 / 수술 후 조기 재활 / 산재 지정",
        "recovery": "해당없음",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "세종특별자치시 한누리대로 253 (나성동)",
        "phone": "044-850-7500",
        "sources": "http://www.nksejong.com/",
        "verification": "HIRA/공단 확인",
        "notes": "나성동에 위치한 병원급 의료기관으로 정형외과/신경외과 수술 후 맞춤형 집중 물리치료 및 도수치료 연계가 강점입니다."
    },
    {
        "id": "3",
        "district": "나성동",
        "name": "리더본재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문의 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "디스크, 척추관협착증, 거북목, 스포츠 손상, 족부 통증",
        "specialty": "비수술적 척추관절 재활 / 체외충격파 / 맞춤 도수치료",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "세종특별자치시 나성북로 30, 퍼스트원 B동 6층 (나성동)",
        "phone": "044-865-0700",
        "sources": "http://leaderbone.co.kr/",
        "verification": "HIRA/공식 정보 확인",
        "notes": "재활의학과 전문의가 상주하여 정밀 초음파 진단을 통해 1:1 맞춤 통증 주사 치료 및 체계적인 운동/도수치료 프로그램을 제공합니다."
    },
    {
        "id": "4",
        "district": "소담동",
        "name": "세종탑재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문의 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "근골격계 통증, 자세교정, 도수치료, 신경차단술",
        "specialty": "1:1 정밀 도수치료 / 오십견 및 만성 통증 재활",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "세종특별자치시 한누리대로 2018, 사이언스타운 5층 (소담동)",
        "phone": "044-864-1620",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "3생활권(소담동/보람동) 중심에 위치하여 인근 주민들의 척추, 관절 비수술 통증 케어와 체계적인 근골격 도수재활 치료를 전문으로 합니다."
    },
    {
        "id": "5",
        "district": "어진동",
        "name": "서울아산재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문의 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "목·허리 디스크, 관절염, 스포츠 손상, 체형 및 자세 교정",
        "specialty": "아산병원 출신 전문의 / 비수술 관절 주사 / 체외충격파",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "세종특별자치시 절재로 194, 중앙타운 4층 (어진동)",
        "phone": "044-715-7591",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "정부세종청사 인근 어진동에 위치하여 공무원 및 인근 직장인들을 위한 거북목, 오십견, 만성 척추 관절 통증의 빠르고 효과적인 비수술 재활치료를 실시합니다."
    },
    {
        "id": "6",
        "district": "새롬동",
        "name": "서울굿닥터의원",
        "type": "의원",
        "inclusion": "대형 재활 연계 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "뇌졸중 외래재활, 스포츠 재활, 도수치료, 소아/성인 통증 치료",
        "specialty": "규모 있는 물리치료실 / 산재 지정 / 아동 발달 연계",
        "recovery": "해당없음",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "세종특별자치시 새롬로 26, 새롬빌딩 3층 (새롬동)",
        "phone": "044-867-9933",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA/공단 확인",
        "notes": "새롬동에 위치하여 소아 물리치료, 성인 근골격 재활 등 넓은 공간과 다양한 장비를 기반으로 대형 규모의 외래 재활 인프라를 운영하고 있습니다."
    },
    {
        "id": "7",
        "district": "조치원읍",
        "name": "한양재활의학과의원",
        "type": "의원",
        "inclusion": "조치원 재활의학과 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "노인성 관절염, 만성 요통, 오십견, 신경통 비수술 치료",
        "specialty": "조치원 거점 재활 통증 케어 / 물리치료 특화",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "세종특별자치시 조치원읍 새내로 68",
        "phone": "044-862-2300",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "조치원 원도심 지역에 위치하여 어르신들을 위한 관절염 물리치료, 노인성 만성 통증 케어 및 뼈·관절 비수술 재활을 친절히 돕는 의원입니다."
    },
    {
        "id": "8",
        "district": "연서면",
        "name": "조치원노인전문병원",
        "type": "요양병원",
        "inclusion": "공공성 요양 재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "치매, 뇌졸중 후유증, 노인성 만성 질환, 와상 환자 케어",
        "specialty": "치매안심병원 지정 / 공공 노인 의료 복지",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "미운영",
        "address": "세종특별자치시 연서면 도신고복로 789-17",
        "phone": "044-862-7607",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "시립 격의 공공 요양병원으로 만성 질환 및 뇌졸중 후유증 어르신들의 요양과 완만한 물리재활 치료를 전문적으로 돕는 공공 병원입니다."
    },
    {
        "id": "9",
        "district": "조치원읍",
        "name": "세종중앙요양병원",
        "type": "요양병원",
        "inclusion": "재활 연계 요양병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌혈관 질환 마비 재활, 골절 수술 후 요양, 노인성 와상 케어",
        "specialty": "넓은 입원 병상 / 집중 요양 재활 치료실 운영",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "미운영",
        "address": "세종특별자치시 조치원읍 섭골길 37",
        "phone": "044-865-0066",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "조치원읍에 위치하여 넓고 쾌적한 병상 환경에서 뇌졸중 후유 마비나 수술 후 장기 요양이 필요한 환자 대상의 일상 복귀 물리치료를 제공합니다."
    },
    {
        "id": "10",
        "district": "장군면",
        "name": "세종요양병원",
        "type": "요양병원",
        "inclusion": "재활 연계 요양병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌졸중 예방 및 재활, 만성 관절 통증, 노인성 치매 장기 요양",
        "specialty": "친자연적 환경 / 욕창 예방 및 환자 케어 특화",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "미운영",
        "address": "세종특별자치시 장군면 구석뜸길 140",
        "phone": "044-881-1711",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "장군면의 한적하고 자연친화적인 부지에 자리 잡아, 급성기 치료 후 정서적 안정과 만성기 재활 치료를 병행하기에 적합한 환경을 자랑합니다."
    },
    {
        "id": "11",
        "district": "대평동",
        "name": "세종하이한방병원",
        "type": "한방병원",
        "inclusion": "양한방 협진 재활병원",
        "rehabDept": "한방/양방협진",
        "specialists": "의사·한의사 협진",
        "careType": "양한방 협진/입원재활/외래재활",
        "conditions": "교통사고 후유증, 수술 후 회복 재활, 디스크 추나/도수치료",
        "specialty": "양·한방 통합 면역재활 / 쾌적한 입원실 / 추나 및 도수치료",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "세종특별자치시 갈매로 58 (대평동, 삼성디지털프라자 3층, 6층)",
        "phone": "044-999-1999",
        "sources": "http://hihanbang.com/",
        "verification": "공식 정보 교차 검토",
        "notes": "3생활권 대평동에 위치한 대규모 양한방 협진 병원으로, 수술 후 조기 입원 재활과 교통사고 후유증 추나/도수 통증 집중 치료실을 운영합니다."
    },
    {
        "id": "12",
        "district": "소담동",
        "name": "강남세종한방병원",
        "type": "한방병원",
        "inclusion": "양한방 협진 재활병원",
        "rehabDept": "한방/양방협진",
        "specialists": "의사·한의사 협진",
        "careType": "양한방 협진/입원재활/외래재활",
        "conditions": "디스크 및 척추 관절 재활, 교통사고 후유증 치료, 도수/추나",
        "specialty": "한방 재활의학 / 입원 집중 추나 요법",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "세종특별자치시 한누리대로 2275 (소담동, 알파메디컬센터 4~6층)",
        "phone": "044-863-7775",
        "sources": "http://gangnamsj.com/",
        "verification": "공식 정보 교차 검토",
        "notes": "소담동에 위치하여 쾌적한 최신 입원 시설을 갖추고 있으며, 숙련된 추나/도수 치료진이 척추·관절 환자의 양한방 협진 재활을 돕습니다."
    },
    {
        "id": "13",
        "district": "나성동",
        "name": "오케이한방병원",
        "type": "한방병원",
        "inclusion": "양한방 협진 재활병원",
        "rehabDept": "한방/양방협진",
        "specialists": "의사·한의사 협진",
        "careType": "양한방 협진/입원재활/외래재활",
        "conditions": "교통사고 후유증 재활, 목·허리 통증, 수술 후 기능 회복",
        "specialty": "중심상업지구 입원실 운영 / 맞춤 물리재활치료",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "세종특별자치시 한누리대로 253, 세종메디피아 6층 (나성동)",
        "phone": "044-1668-0090",
        "sources": "http://okmedi.kr/",
        "verification": "공식 정보 교차 검토",
        "notes": "나성동 중심가 위치로 접근성이 매우 뛰어나며, 통증 원인 분석을 통한 비수술 도수/추나 치료와 입원 집중 재활 프로그램을 제공합니다."
    },
    {
        "id": "14",
        "district": "보람동",
        "name": "연세새봄재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문의 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "목·허리 디스크, 관절염, 거북목, 오십견, 도수치료",
        "specialty": "소아 및 성인 통증 재활 / 맞춤형 도수치료",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "세종특별자치시 호려울로 9, 3층 (보람동)",
        "phone": "044-865-9099",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "보람동 3생활권에 위치하며, 재활의학과 전문의의 정밀 진단을 바탕으로 소아 발달 센터 및 성인 만성 통증 비수술 도수재활 치료를 시행합니다."
    },
    {
        "id": "15",
        "district": "도담동",
        "name": "도담재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문의 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "척추 측만증, 거북목 교정, 디스크, 관절통증, 도수치료",
        "specialty": "체형 및 자세 교정 재활 / 1:1 도수치료 특화",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "세종특별자치시 보듬3로 8-20, 세종한림프라자 3층 (도담동)",
        "phone": "044-863-7582",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "도담동 중심상가에 위치하여 학생 및 직장인들의 구부정한 체형 교정 재활 및 목, 어깨, 허리 부위 통증 완화를 전문적으로 관리하는 의원입니다."
    },
    {
        "id": "16",
        "district": "아름동",
        "name": "바른길재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문의 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "신경통, 골다공증, 만성 요통, 스포츠 손상 재활, 도수치료",
        "specialty": "스포츠 손상 재활 / 뼈·관절 신경차단술 / 체외충격파",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "세종특별자치시 보듬3로 100, 세종갈라가든 4층 (아름동)",
        "phone": "044-863-1275",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "아름동에 위치하며, 스포츠 손상 환자들의 빠른 관절 복귀 재활과 중장년층을 위한 신경 비수술 주사 치료, 첨단 장비를 이용한 통증 재활을 지원합니다."
    },
    {
        "id": "17",
        "district": "다정동",
        "name": "다정재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문의 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "디스크, 협착증, 무릎 관절염, 오십견, 도수운동치료",
        "specialty": "노인성 근골격계 질환 재활 / 1:1 도수운동 치료",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "세종특별자치시 다정중앙로 53, 다정프라자 5층 (다정동)",
        "phone": "044-868-7570",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "다정동 유일의 재활의학과 전문의 의료기관으로, 근력을 강화하여 관절 통증을 근본적으로 개선하는 운동 재활 및 맞춤 도수치료를 운영하고 있습니다."
    }
];
