window.REHAB_DATA = [
  {
    "id": "1",
    "district": "김해시",
    "name": "의료법인환명의료재단 조은금강병원",
    "type": "종합병원",
    "inclusion": "재활의학과 보유 종합병원",
    "rehabDept": "있음",
    "specialists": "1명(HIRA 확인)",
    "careType": "외래/입원 재활 가능성",
    "conditions": "뇌졸중 후유증, 근골격계, 수술 후 재활, 보행장애, 통증",
    "specialty": "종합병원 재활의학과",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 김해대로 1814-37",
    "phone": "055-330-0300",
    "sources": "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkODkkMzgxMzUxIzExIyQxIyQzIyQ2MiQ0NjEwMDIjNjEjJDEjJDQjJDgz",
    "verification": "HIRA 확인",
    "notes": "HIRA에서 재활의학과 전문의 1명 확인. 입원재활 세부 운영은 전화확인 필요"
  },
  {
    "id": "2",
    "district": "김해시",
    "name": "김해굿모닝병원",
    "type": "병원",
    "inclusion": "재활의학과 보유 병원",
    "rehabDept": "있음",
    "specialists": "1명(HIRA 검색결과)",
    "careType": "외래/입원 재활 가능성",
    "conditions": "근골격계, 수술 후 재활, 통증, 보행장애",
    "specialty": "병원 재활의학과",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 분성로 444",
    "phone": "055-333-9522",
    "sources": "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkMzgxMzUxIzIxIyQxIyQ1IyQ4OSQyNjEwMDIjNDEjJDEjJDgjJDgz",
    "verification": "HIRA 검색결과 확인",
    "notes": "검색결과상 재활의학과(1) 표기. HIRA 세부 전문의 현황 재확인 권장"
  },
  {
    "id": "3",
    "district": "김해시",
    "name": "구샘재활의학과의원",
    "type": "의원",
    "inclusion": "재활의학과 의원",
    "rehabDept": "있음",
    "specialists": "확인필요",
    "careType": "외래 중심",
    "conditions": "근골격계 통증, 도수/물리치료, 신경계 후유증, 보행/운동재활",
    "specialty": "재활의학과 외래",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 진영읍 김해대로361번길 16, 3층",
    "phone": "055-343-1345",
    "sources": "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMiMkNCMkMDAkNDgxMzUxIzMxIyQxIyQ3IyQ5MiQ0NjE0ODEjODEjJDEjJDIjJDgz",
    "verification": "HIRA 확인",
    "notes": "전문의 수는 세부 진료과목 현황 재확인 필요"
  },
  {
    "id": "4",
    "district": "김해시",
    "name": "의료법인희원의료재단 래봄병원",
    "type": "병원",
    "inclusion": "재활병원/재활의학과 전문의 후보",
    "rehabDept": "있음",
    "specialists": "전문의 확인(기관 홈페이지)",
    "careType": "입원재활/외래재활",
    "conditions": "뇌졸중, 뇌손상, 척수손상, 파킨슨, 근골격계, 로봇재활, 일상생활동작",
    "specialty": "재활치료센터/로봇재활",
    "recovery": "제3기 여부 확인필요",
    "workersComp": "산재 재활인증기관 확인(근로복지공단)",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 분성로 202",
    "phone": "1644-8765",
    "sources": "https://www.rebom.or.kr/ / https://www.comwel.or.kr/comwel/comp/trmt/rein02.jsp",
    "verification": "공식+공단 확인",
    "notes": "근로복지공단 재활인증 목록에 래봄병원 김해시 분성로 202 표시. 회복기 지정 여부는 제3기 명단에서 재확인"
  },
  {
    "id": "5",
    "district": "김해시",
    "name": "의료법인푸른솔의료재단 김해한솔재활요양병원",
    "type": "요양병원",
    "inclusion": "재활요양병원/재활의학과 전문의",
    "rehabDept": "있음",
    "specialists": "4명(요양병원 정보 확인)",
    "careType": "입원재활/요양재활",
    "conditions": "뇌손상, 척수손상, 로봇재활, 근골격계/통증, 소아재활, 호흡재활",
    "specialty": "재활요양/로봇재활",
    "recovery": "확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 김해대로 2379",
    "phone": "055-329-3340",
    "sources": "https://www.ghhansol.co.kr/ / https://ddoga.co.kr/ltch/13/JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzExIyQxIyQzIyQ5MiQyNjE0ODEjNDEjJDEjJDgjJDgz/W01",
    "verification": "공식+요양정보 확인",
    "notes": "기관 홈페이지에 뇌손상/척수손상/로봇재활 등 표기, 전문의 수는 HIRA 재확인 권장"
  },
  {
    "id": "6",
    "district": "김해시",
    "name": "(의)수의료재단 서청솔요양병원",
    "type": "요양병원",
    "inclusion": "재활요양병원/전문의 후보",
    "rehabDept": "있음",
    "specialists": "전문의 확인필요",
    "careType": "입원재활/요양재활",
    "conditions": "뇌졸중, 중추신경계, 노인성질환, 통증, 양한방협진",
    "specialty": "재활치료/양한방협진",
    "recovery": "확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 금관대로1084번길 15",
    "phone": "확인필요",
    "sources": "https://www.scsh.co.kr/ / https://ddoga.co.kr/ltch/13/JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzIxIyQxIyQ1IyQ4MiQzNjEyMjIjNTEjJDEjJDIjJDgz/W01",
    "verification": "공식+후보",
    "notes": "공식 홈페이지 재활치료 표기. 재활의학과 전문의 수는 HIRA/전화확인 필요"
  },
  {
    "id": "7",
    "district": "김해시",
    "name": "의료법인한솔의료재단 한서재활요양병원",
    "type": "요양병원",
    "inclusion": "재활요양병원/전문의 후보",
    "rehabDept": "있음",
    "specialists": "전문의 후보",
    "careType": "입원재활/요양재활",
    "conditions": "중풍, 뇌졸중, 산업재해, 교통사고, 발달장애, 기능장애",
    "specialty": "재활요양",
    "recovery": "확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 진영읍 일대",
    "phone": "확인필요",
    "sources": "https://www.peonani.com/facility/1092/의료법인한솔의료재단한서재활요양병원 / https://my-doctor.io/hospital/deptHub/list/region/재활의학과-전문의-경남-김해시",
    "verification": "후보/전화확인",
    "notes": "제3자 정보상 재활의학과 전문의 후보. HIRA에서 진료과목·전문의 수 재확인 필요"
  },
  {
    "id": "8",
    "district": "김해시",
    "name": "한가족요양병원",
    "type": "요양병원",
    "inclusion": "재활요양병원/재활의학과 전문의 후보",
    "rehabDept": "있음",
    "specialists": "1명(요양정보 확인)",
    "careType": "입원재활/요양재활",
    "conditions": "뇌졸중, 노인성질환, 근골격계, 통증, 양한방협진",
    "specialty": "재활요양",
    "recovery": "확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 전하로 234 또는 내외로77번길 6 확인필요",
    "phone": "055-338-0011",
    "sources": "https://ddoga.co.kr/ltch/13/JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzIxIyQxIyQxIyQ4OSQzNjE4MzIjODEjJDEjJDIjJDgz/W01 / https://mobile.hidoc.co.kr/find/result/view/H0000155262",
    "verification": "후보/주소 재확인",
    "notes": "검색원별 주소가 달라 HIRA에서 최신 주소 재확인 필요"
  },
  {
    "id": "9",
    "district": "김해시",
    "name": "(의)밀성학원의료재단 성모아하브요양병원",
    "type": "요양병원",
    "inclusion": "요양병원/물리치료실 보유",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "요양재활 가능성",
    "conditions": "노인성질환, 기능저하, 물리치료, 만성기 관리",
    "specialty": "요양병원",
    "recovery": "확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 김해대로 2479-1",
    "phone": "055-320-2080",
    "sources": "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzIxIyQxIyQ1IyQ4OSQzNjE4MzIjNjEjJDEjJDAjJDgz",
    "verification": "HIRA 확인",
    "notes": "HIRA상 요양병원·물리치료실 11 확인. 재활의학과 전문의 여부는 별도 확인 필요"
  },
  {
    "id": "10",
    "district": "김해시",
    "name": "의료법인한서의료재단 진영병원",
    "type": "병원",
    "inclusion": "재활의학과 진료과목 후보/정형·신경계 외래",
    "rehabDept": "없음 또는 0명(HIRA)",
    "specialists": "0명(HIRA 확인)",
    "careType": "외래/입원 가능성",
    "conditions": "정형외과, 신경외과, 영상의학 기반 재활 연계 가능성",
    "specialty": "재활의학과 전문의 없음",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 진영읍 김해대로334번길 9",
    "phone": "055-340-3700",
    "sources": "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkMzgxMzUxIzIxIyQxIyQ5IyQ3OSQyNjEyMjIjODEjJDEjJDYjJDgz",
    "verification": "HIRA 확인",
    "notes": "HIRA상 재활의학과 전문의 0명. 재활의학과 전문치료기관으로 분류하지 않도록 주의"
  },
  {
    "id": "11",
    "district": "김해시",
    "name": "강일병원",
    "type": "종합/병원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 김해시",
    "phone": "확인필요",
    "sources": "https://widocs.com/finder/경상남도/김해시/재활의학과/ / https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-김해시",
    "verification": "후보/전화확인",
    "notes": "HIRA/위닥스 후보. HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "12",
    "district": "김해시",
    "name": "의료법인갑을의료재단 갑을장유병원",
    "type": "종합/병원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 장유 일대",
    "phone": "확인필요",
    "sources": "https://widocs.com/finder/경상남도/김해시/재활의학과/ / https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-김해시",
    "verification": "후보/전화확인",
    "notes": "HIRA/위닥스 후보. HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "13",
    "district": "김해시",
    "name": "의료법인숭인의료재단 김해복음병원",
    "type": "종합병원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 김해시",
    "phone": "확인필요",
    "sources": "https://widocs.com/finder/경상남도/김해시/재활의학과/ / https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-김해시",
    "verification": "후보/전화확인",
    "notes": "HIRA/위닥스 후보. HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "14",
    "district": "김해시",
    "name": "(의)경빈의료재단 김해센텀병원",
    "type": "병원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 김해시",
    "phone": "확인필요",
    "sources": "https://widocs.com/finder/경상남도/김해시/재활의학과/ / https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-김해시",
    "verification": "후보/전화확인",
    "notes": "HIRA/위닥스 후보. HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "15",
    "district": "김해시",
    "name": "의료법인 리드의료재단 다정한요양병원",
    "type": "요양병원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 삼정동",
    "phone": "확인필요",
    "sources": "https://widocs.com/finder/경상남도/김해시/재활의학과/ / https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-김해시",
    "verification": "후보/전화확인",
    "notes": "일요일 진료 검색 후보. HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "16",
    "district": "김해시",
    "name": "강민의료재단 나누리요양병원",
    "type": "요양병원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 김해시",
    "phone": "확인필요",
    "sources": "https://widocs.com/finder/경상남도/김해시/재활의학과/ / https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-김해시",
    "verification": "후보/전화확인",
    "notes": "HIRA/위닥스 후보. HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "17",
    "district": "김해시",
    "name": "(의)환명의료재단 경상남도립김해노인전문병원",
    "type": "요양병원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 김해시",
    "phone": "확인필요",
    "sources": "https://widocs.com/finder/경상남도/김해시/재활의학과/ / https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-김해시",
    "verification": "후보/전화확인",
    "notes": "HIRA/위닥스 후보. HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "18",
    "district": "김해시",
    "name": "연세바른본의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 부곡동",
    "phone": "확인필요",
    "sources": "https://widocs.com/finder/경상남도/김해시/재활의학과/ / https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-김해시",
    "verification": "후보/전화확인",
    "notes": "재활의학과 진료 후보. HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "19",
    "district": "김해시",
    "name": "김영일정형외과의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 진영읍",
    "phone": "확인필요",
    "sources": "https://widocs.com/finder/경상남도/김해시/재활의학과/ / https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-김해시",
    "verification": "후보/전화확인",
    "notes": "재활의학과 진료과목 후보. HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "20",
    "district": "김해시",
    "name": "명성마취통증의학과의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 내동",
    "phone": "확인필요",
    "sources": "https://widocs.com/finder/경상남도/김해시/재활의학과/ / https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-김해시",
    "verification": "후보/전화확인",
    "notes": "재활의학과 진료과목 후보. HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "21",
    "district": "김해시",
    "name": "바른정형외과의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 율하동",
    "phone": "확인필요",
    "sources": "https://widocs.com/finder/경상남도/김해시/재활의학과/ / https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-김해시",
    "verification": "후보/전화확인",
    "notes": "재활의학과 진료과목 후보. HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "22",
    "district": "김해시",
    "name": "박정규정형외과의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 외동",
    "phone": "확인필요",
    "sources": "https://widocs.com/finder/경상남도/김해시/재활의학과/ / https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-김해시",
    "verification": "후보/전화확인",
    "notes": "재활의학과 진료과목 후보. HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "23",
    "district": "김해시",
    "name": "서울베스트신경외과의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 부원동",
    "phone": "확인필요",
    "sources": "https://widocs.com/finder/경상남도/김해시/재활의학과/ / https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-김해시",
    "verification": "후보/전화확인",
    "notes": "재활의학과 진료과목 후보. HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "24",
    "district": "김해시",
    "name": "장유서화정형외과의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 대청동",
    "phone": "확인필요",
    "sources": "https://widocs.com/finder/경상남도/김해시/재활의학과/ / https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-김해시",
    "verification": "후보/전화확인",
    "notes": "재활의학과 진료과목 후보. HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "25",
    "district": "김해시",
    "name": "장유으뜸신경외과의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 부곡동",
    "phone": "확인필요",
    "sources": "https://widocs.com/finder/경상남도/김해시/재활의학과/ / https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-김해시",
    "verification": "후보/전화확인",
    "notes": "재활의학과 진료과목 후보. HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "26",
    "district": "김해시",
    "name": "진영센텀정형외과의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 진영읍",
    "phone": "확인필요",
    "sources": "https://widocs.com/finder/경상남도/김해시/재활의학과/ / https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-김해시",
    "verification": "후보/전화확인",
    "notes": "재활의학과 진료과목 후보. HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "27",
    "district": "김해시",
    "name": "김해탑재활의학과의원",
    "type": "의원",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 삼방동",
    "phone": "확인필요",
    "sources": "https://widocs.com/finder/경상남도/김해시/재활의학과/ / https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-김해시",
    "verification": "후보/전화확인",
    "notes": "재활의학과 직접 후보. HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "28",
    "district": "김해시",
    "name": "김해본365마취통증의학과의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 김해시 삼계동",
    "phone": "확인필요",
    "sources": "https://widocs.com/finder/경상남도/김해시/재활의학과/ / https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-김해시",
    "verification": "후보/전화확인",
    "notes": "재활의학과 진료 후보. HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "29",
    "district": "양산시",
    "name": "양산부산대학교병원",
    "type": "상급종합병원",
    "inclusion": "재활의학과 보유 상급종합병원",
    "rehabDept": "있음",
    "specialists": "확인필요",
    "careType": "급성기/외래/입원재활",
    "conditions": "뇌졸중, 뇌손상, 척수손상, 소아재활, 암재활, 근골격계, 보조기",
    "specialty": "상급종합 재활의학과",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "외래/입원 중심",
    "address": "경남 양산시 물금읍 금오로 20",
    "phone": "055-360-1000",
    "sources": "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?isNewWindow=Y&isPopupYn=Y&ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkODkkMzgxMzUxIzExIyQxIyQzIyQ3MiQyNjE0ODEjODEjJDEjJDYjJDgz",
    "verification": "HIRA 확인",
    "notes": "전문의 수는 HIRA 진료과목 세부현황 재확인 필요"
  },
  {
    "id": "30",
    "district": "양산시",
    "name": "양산제일병원",
    "type": "병원",
    "inclusion": "재활의학과 보유 병원",
    "rehabDept": "있음",
    "specialists": "2명(검색결과)",
    "careType": "외래/입원 재활 가능성",
    "conditions": "근골격계, 수술 후 재활, 통증, 신경계 후유증",
    "specialty": "병원 재활의학과",
    "recovery": "확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 양산시 동면 금오로 255",
    "phone": "055-904-7575",
    "sources": "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkMzgxMzUxIzMxIyQxIyQzIyQ4OSQzNjE0ODEjODEjJDEjJDYjJDgz / https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-양산시",
    "verification": "HIRA+검색결과 확인",
    "notes": "검색결과상 재활의학과 전문의 2명. HIRA 세부 재확인 권장"
  },
  {
    "id": "31",
    "district": "양산시",
    "name": "양산서울요양병원",
    "type": "요양병원",
    "inclusion": "재활요양병원/재활의학과 보유",
    "rehabDept": "있음",
    "specialists": "1명(HIRA 확인)",
    "careType": "입원재활/요양재활",
    "conditions": "뇌졸중, 노인성질환, 정형외과 수술 후, 신경계 후유증, 한방협진",
    "specialty": "재활요양/양한방",
    "recovery": "확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "해당없음",
    "address": "경남 양산시 북정동 일대",
    "phone": "확인필요",
    "sources": "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzIxIyQxIyQ1IyQwMyQ0NjEwMDIjNDEjJDEjJDgjJDgz",
    "verification": "HIRA 확인",
    "notes": "HIRA상 재활의학과 전문의 1명 확인"
  },
  {
    "id": "32",
    "district": "양산시",
    "name": "양산아이재활의학과의원",
    "type": "의원",
    "inclusion": "재활의학과 의원/아동특화",
    "rehabDept": "있음",
    "specialists": "확인필요",
    "careType": "외래 중심",
    "conditions": "소아·아동 재활, 발달평가, 언어/인지/운동 발달, 신경계 질환",
    "specialty": "아동 특화 재활의학과",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "해당없음",
    "address": "경남 양산시 물금읍 청운로 185, 오즈시티 203호",
    "phone": "055-381-1236",
    "sources": "https://yangsani.co.kr/ / https://doctorindex.co.kr/clinic/경상남도-양산시-양산아이재활의학과의원/",
    "verification": "공식+공공데이터",
    "notes": "2025.05.13 개설 자료. HIRA 최신개설상태 재확인 필요"
  },
  {
    "id": "33",
    "district": "양산시",
    "name": "양산더존한방병원",
    "type": "한방병원",
    "inclusion": "한방재활의학과 전문의/한방재활",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래/입원 가능성",
    "conditions": "추나, 한방재활, 교통사고 후유증, 척추·관절 통증",
    "specialty": "한방재활의학과 전문의",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "확인필요",
    "address": "경남 양산시 물금읍 청운로 349",
    "phone": "055-785-0000",
    "sources": "https://www.kmspecialist.org/community/bbs/kmspecialist.php?guest=true&mb_id=soal86 / https://yangsan.thezoneh.com/kwa-40122",
    "verification": "전문의 공식 확인",
    "notes": "한방재활의학과 전문의 김형구 표기. 의과 재활의학과와 구분 필요"
  },
  {
    "id": "34",
    "district": "양산시",
    "name": "양산부산대학교한방병원",
    "type": "한방병원",
    "inclusion": "한방재활의학과/공립 한방병원",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래/입원 가능성",
    "conditions": "한방재활, 추나, 근골격계, 중풍 후유증, 통증",
    "specialty": "공립 한방병원",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "확인필요",
    "address": "경남 양산시 물금읍 금오로 20",
    "phone": "055-360-5555",
    "sources": "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?isNewWindow=Y&ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkMTMkMzgxMTkxIzExIyQxIyQzIyQ5OSQ0NjE0ODEjNDEjJDEjJDQjJDgz",
    "verification": "HIRA 확인",
    "notes": "한방병원으로 의과 재활의학과 전문의와 별도 구분"
  },
  {
    "id": "35",
    "district": "양산시",
    "name": "아는마음한방병원",
    "type": "한방병원",
    "inclusion": "한방재활/교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래/입원 가능성",
    "conditions": "추나, 한방재활, 교통사고 후유증, 척추·관절 통증",
    "specialty": "한방재활 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "확인필요",
    "address": "경남 양산시 물금읍",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-양산시",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 후보. HIRA 세부페이지 확인 필요"
  },
  {
    "id": "36",
    "district": "양산시",
    "name": "임병원마취통증의학과의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 양산시 덕계동",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-양산시 / https://widocs.com/finder/경상남도/재활의학과/",
    "verification": "후보/전화확인",
    "notes": "HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "37",
    "district": "양산시",
    "name": "덕계올바른마취통증의학과의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 양산시 덕계동",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-양산시 / https://widocs.com/finder/경상남도/재활의학과/",
    "verification": "후보/전화확인",
    "notes": "HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "38",
    "district": "양산시",
    "name": "새로운정형외과의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 양산시 덕계동",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-양산시 / https://widocs.com/finder/경상남도/재활의학과/",
    "verification": "후보/전화확인",
    "notes": "HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "39",
    "district": "양산시",
    "name": "세민정형외과의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 양산시 삼호동",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-양산시 / https://widocs.com/finder/경상남도/재활의학과/",
    "verification": "후보/전화확인",
    "notes": "HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "40",
    "district": "양산시",
    "name": "진정형외과의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 양산시 물금읍",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-양산시 / https://widocs.com/finder/경상남도/재활의학과/",
    "verification": "후보/전화확인",
    "notes": "HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "41",
    "district": "양산시",
    "name": "양산본마취통증의학과의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 양산시 남부동",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-양산시 / https://widocs.com/finder/경상남도/재활의학과/",
    "verification": "후보/전화확인",
    "notes": "HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "42",
    "district": "양산시",
    "name": "인산정형외과의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 양산시 물금읍",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-양산시 / https://widocs.com/finder/경상남도/재활의학과/",
    "verification": "후보/전화확인",
    "notes": "HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "43",
    "district": "양산시",
    "name": "행복한가정의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 양산시 상북면",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-양산시 / https://widocs.com/finder/경상남도/재활의학과/",
    "verification": "후보/전화확인",
    "notes": "HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "44",
    "district": "양산시",
    "name": "참사랑정형외과의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 양산시 중부동",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-양산시 / https://widocs.com/finder/경상남도/재활의학과/",
    "verification": "후보/전화확인",
    "notes": "HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "45",
    "district": "양산시",
    "name": "이화외과의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 양산시 동면",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-양산시 / https://widocs.com/finder/경상남도/재활의학과/",
    "verification": "후보/전화확인",
    "notes": "HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "46",
    "district": "양산시",
    "name": "이승재정형외과의원",
    "type": "의원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 양산시 물금읍",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-양산시 / https://widocs.com/finder/경상남도/재활의학과/",
    "verification": "후보/전화확인",
    "notes": "HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "47",
    "district": "양산시",
    "name": "더이로운병원",
    "type": "병원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 양산시 북부동",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-양산시 / https://widocs.com/finder/경상남도/재활의학과/",
    "verification": "후보/전화확인",
    "notes": "HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "48",
    "district": "양산시",
    "name": "새웅상요양병원",
    "type": "요양병원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 양산시 삼호동",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-양산시 / https://widocs.com/finder/경상남도/재활의학과/",
    "verification": "후보/전화확인",
    "notes": "HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "49",
    "district": "양산시",
    "name": "의료법인 인경의료재단 홍익요양병원",
    "type": "요양병원 후보",
    "inclusion": "재활의학과 진료과목/재활 관련 후보",
    "rehabDept": "확인필요",
    "specialists": "확인필요",
    "careType": "외래 중심 또는 입원 가능성",
    "conditions": "근골격계 통증, 수술 후 재활, 물리치료, 신경계 후유증 후보",
    "specialty": "후보",
    "recovery": "해당없음 또는 확인필요",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "확인필요",
    "dayRehab": "확인필요",
    "address": "경남 양산시 북부동",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-양산시 / https://widocs.com/finder/경상남도/재활의학과/",
    "verification": "후보/전화확인",
    "notes": "HIRA 세부페이지로 개설상태·전문의 수·진료과목 확인 필요"
  },
  {
    "id": "50",
    "district": "김해시",
    "name": "늘푸른한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "51",
    "district": "김해시",
    "name": "부원한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "52",
    "district": "김해시",
    "name": "더나은365한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "53",
    "district": "김해시",
    "name": "유상호한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "54",
    "district": "김해시",
    "name": "석중한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "55",
    "district": "김해시",
    "name": "신세계한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "56",
    "district": "김해시",
    "name": "쾌통한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "57",
    "district": "김해시",
    "name": "율하신세계한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "58",
    "district": "김해시",
    "name": "가야한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "59",
    "district": "김해시",
    "name": "갑오한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "60",
    "district": "김해시",
    "name": "강한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "61",
    "district": "김해시",
    "name": "거송한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "62",
    "district": "김해시",
    "name": "경운부부한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "63",
    "district": "김해시",
    "name": "경희용한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "64",
    "district": "김해시",
    "name": "경희한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "65",
    "district": "김해시",
    "name": "고려한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "66",
    "district": "김해시",
    "name": "금강산한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "67",
    "district": "김해시",
    "name": "김석주한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "68",
    "district": "김해시",
    "name": "김용대한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "69",
    "district": "김해시",
    "name": "김해내외열린한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "70",
    "district": "김해시",
    "name": "동의김해한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "71",
    "district": "김해시",
    "name": "정한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "72",
    "district": "김해시",
    "name": "제산한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 김해시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-김해시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "73",
    "district": "양산시",
    "name": "바른 한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 양산시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-양산시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "74",
    "district": "양산시",
    "name": "대운한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 양산시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-양산시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "75",
    "district": "양산시",
    "name": "마디움한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 양산시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-양산시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "76",
    "district": "양산시",
    "name": "미래한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 양산시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-양산시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "77",
    "district": "양산시",
    "name": "삼동한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 양산시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-양산시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "78",
    "district": "양산시",
    "name": "서울한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 양산시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-양산시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "79",
    "district": "양산시",
    "name": "세명한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 양산시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-양산시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "80",
    "district": "양산시",
    "name": "유창한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 양산시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-양산시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "81",
    "district": "양산시",
    "name": "증산한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 양산시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-양산시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "82",
    "district": "양산시",
    "name": "가촌한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 양산시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-양산시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "83",
    "district": "양산시",
    "name": "건강백세한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 양산시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-양산시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "84",
    "district": "양산시",
    "name": "경희본한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 양산시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-양산시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "85",
    "district": "양산시",
    "name": "경희아침한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 양산시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-양산시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "86",
    "district": "양산시",
    "name": "경희한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 양산시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-양산시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "87",
    "district": "양산시",
    "name": "금강한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 양산시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-양산시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "88",
    "district": "양산시",
    "name": "기쁨한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 양산시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-양산시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  },
  {
    "id": "89",
    "district": "양산시",
    "name": "도옴연합한의원",
    "type": "한의원",
    "inclusion": "한방재활의학과/추나·교통사고 후유증 후보",
    "rehabDept": "해당없음",
    "specialists": "해당없음",
    "careType": "외래 중심",
    "conditions": "목·허리·어깨·무릎 통증, 염좌, 추나, 침구, 교통사고 후유증, 한방재활 후보",
    "specialty": "한방재활/교통사고 후유증 후보",
    "recovery": "해당없음",
    "workersComp": "산재지정 여부 확인필요",
    "autoInsurance": "자동차보험 확인필요",
    "dayRehab": "해당없음",
    "address": "경남 양산시 상세주소 확인필요",
    "phone": "확인필요",
    "sources": "https://my-doctor.io/hospital/deptHub/list/region/한방재활의학과-전체-경남-양산시 / https://www.hira.or.kr/ra/hosp/getHealthMap.do?pgmid=HIRAA030002010000",
    "verification": "후보/전화확인",
    "notes": "한방재활의학과 전문의 여부·추나/자동차보험 청구 여부 전화확인 필요"
  }
];
