window.REHAB_DATA = [
    {
        "id": "1",
        "district": "광산구",
        "name": "광주365재활병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 근골격계 재활, 수술 후 집중재활",
        "specialty": "보건복지부 회복기 지정 / 산재 재활인증",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "광주광역시 광산구 임방울대로 350 (수완동)",
        "phone": "062-951-0365",
        "sources": "http://www.gj365rh.kr/",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관 (2026.03 ~ 2029.02). 근로복지공단 산재 재활인증 의료기관. 1대1 집중 재활 치료 및 간호간병통합서비스 병동 운영."
    },
    {
        "id": "2",
        "district": "북구",
        "name": "호남권역재활병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활/소아재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 소아재활, 근골격계 재활, 비사용증후군",
        "specialty": "보건복지부 회복기 지정 / 국립재활원 연계 권역재활병원",
        "recovery": "지정(제3기)",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "광주광역시 북구 첨단벤처소로 38 (월출동)",
        "phone": "062-613-9000",
        "sources": "http://www.hnrh.or.kr/",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관. 광주·전남 지역 유일의 권역재활병원으로 수준 높은 소아 및 성인 전문 재활치료실과 간호간병통합서비스 병동 완비."
    },
    {
        "id": "3",
        "district": "북구",
        "name": "우암병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 뇌성마비, 수술 후 집중재활",
        "specialty": "보건복지부 회복기 지정 / 집중재활센터",
        "recovery": "지정(제3기)",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "광주광역시 북구 경열로 224 (중흥동)",
        "phone": "062-720-9700",
        "sources": "http://www.wooamhosp.co.kr/",
        "verification": "보건복지부/HIRA 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관. 뇌신경, 척수 손상 환자 대상의 1대1 집중 물리/작업치료실 및 운동치료 특화 병동을 갖춘 재활 거점 병원."
    },
    {
        "id": "4",
        "district": "순천시",
        "name": "근로복지공단 순천병원",
        "type": "종합병원",
        "inclusion": "공단 직영 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "산재 장해 재활, 중추신경계 마비, 직업복귀 평가, 근골격계 물리치료",
        "specialty": "근로복지공단 직영 / 재활전문센터 / 산재 재활인증",
        "recovery": "해당없음",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "전라남도 순천시 조례못등길 34 (조례동)",
        "phone": "061-729-1114",
        "sources": "https://www.comwel.or.kr/suncheon/",
        "verification": "근로복지공단 공식 확인",
        "notes": "근로복지공단 직영 공공 의료기관으로 대규모 재활전문센터를 운영하며 산재 근로자 및 지역 주민을 위한 체계적인 재활 운동 및 작업/언어 치료 제공."
    },
    {
        "id": "5",
        "district": "서구",
        "name": "근로복지공단 광주의원",
        "type": "의원",
        "inclusion": "공단 직영 외래재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "산재 장해 재활, 도수치료, 운동치료, 작업 복귀 평가",
        "specialty": "근로복지공단 직영 / 외래 재활 특화 / 산재 재활인증",
        "recovery": "해당없음",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "광주광역시 서구 죽봉대로 68 (광천동)",
        "phone": "062-607-3300",
        "sources": "https://www.comwel.or.kr/",
        "verification": "근로복지공단 공식 확인",
        "notes": "근로복지공단에서 직영하는 외래 전문 재활의원. 1:1 맞춤형 재활치료 및 직업 복귀 프로그램 운영."
    },
    {
        "id": "6",
        "district": "목포시",
        "name": "목포재활요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌경색/뇌출혈 마비, 연하 장애 치료, 작업치료",
        "specialty": "재활의학과 전문의 상주 / 서남권 대표 요양재활",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "전라남도 목포시 통일대로 105 (석현동)",
        "phone": "061-285-8575",
        "sources": "http://www.mprh.co.kr/",
        "verification": "HIRA/심평원 적정성평가 1등급 확인",
        "notes": "목포 석현동에 위치한 재활의학과 전문의 상주 요양병원. 2년 연속 심평원 적정성 평가 1등급 획득. 1대1 운동치료, 작업치료, 연하 장애 치료 등 체계적인 뇌졸중 후유증 케어."
    },
    {
        "id": "7",
        "district": "여수시",
        "name": "여수강남요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "노인성 마비, 척추·관절 수술 후 회복, 물리치료",
        "specialty": "여수 거점 재활치료 요양병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "전라남도 여수시 여서로 100 (여서동)",
        "phone": "061-654-8275",
        "sources": "http://www.ysknh.co.kr/",
        "verification": "HIRA 확인",
        "notes": "여수 지역 최대 규모의 재활 요양병원. 노인성 마비 및 수술 후 관절 가동 범위 확보를 위한 물리재활치료실 활성화."
    },
    {
        "id": "8",
        "district": "남구",
        "name": "씨티재활의학과요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활/외래재활",
        "conditions": "뇌졸중 후유증, 파킨슨병, 수술 후 관절 재활, 통증 물리치료",
        "specialty": "재활의학과 전문의 진료 / 대규모 치료실",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "광주광역시 남구 송암로 76 (송하동)",
        "phone": "062-606-2000",
        "sources": "http://www.ctrehab.co.kr/",
        "verification": "HIRA 확인",
        "notes": "광주 남구 지역 대표 재활 특화 요양병원. 재활의학과 전문의 및 대규모 재활치료센터를 갖추고 뇌경색/뇌출혈 및 수술 후 관절 재활 집중 치료."
    },
    {
        "id": "9",
        "district": "광산구",
        "name": "첨단요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활/투석 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활/투석재활",
        "conditions": "뇌경색, 뇌출혈, 파킨슨, 만성 신부전(인공신장 투석)",
        "specialty": "재활치료실 운영 / 인공신장실(투석) 병행",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "광주광역시 광산구 첨단중앙로182번길 40 (쌍암동)",
        "phone": "062-970-1000",
        "sources": "http://www.cheomdancare.co.kr/",
        "verification": "HIRA/심평원 적정성평가 1등급 확인",
        "notes": "대규모 재활치료센터 및 투석 인공신장실을 함께 갖추어 만성 신부전 환자의 투석 중 재활치료에 특화된 요양병원. 심평원 적정성 평가 1등급."
    },
    {
        "id": "10",
        "district": "서구",
        "name": "상무힐링재활요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌졸중 마비, 수술 후 외상 재활, 양한방 협진",
        "specialty": "다학제 협진 시스템 / 상무지구 중심가",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "광주광역시 서구 상무평화로 62 (치평동)",
        "phone": "062-380-7000",
        "sources": "http://www.smrhealing.co.kr/",
        "verification": "HIRA 확인",
        "notes": "상무지구 내 위치한 재활 요양병원. 정형 및 신경계 다학제 협진 시스템과 쾌적한 치료 환경을 갖추어 장기 재활 요양에 적합."
    },
    {
        "id": "11",
        "district": "남구",
        "name": "효인재활요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌신경 손상 마비, 뇌졸중 후유증 보행훈련, 연하치료",
        "specialty": "중추신경계 마비 집중 치료실 / 보행훈련 특화",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "광주광역시 남구 월산로 92 (월산동)",
        "phone": "062-350-7575",
        "sources": "http://hyo-in.co.kr/",
        "verification": "HIRA 확인",
        "notes": "신경외과 및 재활의학과 전문의 상주. 중추신경계 마비 환자 대상 집중 치료실 및 보행 훈련 프로그램 가동."
    },
    {
        "id": "12",
        "district": "북구",
        "name": "천사요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌졸중 마비, 보행훈련, 연하재활, 인지재활",
        "specialty": "중추신경계 재활 / 연하 및 도수치료",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "광주광역시 북구 본촌마을길 77 (본촌동)",
        "phone": "062-570-1004",
        "sources": "http://www.1004hospital.com/",
        "verification": "HIRA 확인",
        "notes": "중추신경계 재활, 뇌졸중 후유증 보행 훈련, 통증 물리치료 및 작업치료 클리닉 활성화."
    },
    {
        "id": "13",
        "district": "서구",
        "name": "상무효정요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 양한방 협진",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌졸중 마비, 만성기 통증, 양한방 협진 재활",
        "specialty": "양한방 협진 물리치료 / 노인 만성 관리",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "광주광역시 서구 마륵복개로 135 (마륵동)",
        "phone": "062-385-8000",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "재활의학과 전문의 상주 하에 양한방 협진 진료 제공. 만성기 환자 보존적 물리치료 중심."
    },
    {
        "id": "14",
        "district": "광산구",
        "name": "산들요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 적정성 1등급",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "고령 만성 환자 마비재활, 통증 완화, 인지 재활",
        "specialty": "심평원 적정성평가 1등급 / 고령 특화 재활",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "광주광역시 광산구 신창로 64 (신창동)",
        "phone": "062-960-9900",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA/심평원 적정성평가 1등급 확인",
        "notes": "건강보험심사평가원 요양병원 적정성 평가 1등급 획득. 재활의학과 전문의 진료 및 물리치료실 운영."
    },
    {
        "id": "15",
        "district": "남구",
        "name": "광주연세요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 적정성 1등급",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌졸중 만성 마비, 인지저하(치매) 관리, 물리치료",
        "specialty": "심평원 적정성평가 1등급 / 치매 및 물리재활",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "광주광역시 남구 효우로 325 (행암동)",
        "phone": "062-601-3000",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA/심평원 적정성평가 1등급 확인",
        "notes": "심평원 적정성 평가 1등급. 고령 환자 집중 케어 및 기능 유지 물리치료실 가동."
    },
    {
        "id": "16",
        "district": "서구",
        "name": "동행요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 적정성 1등급",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "만성 노인마비, 치매 관리, 관절 척추 보존 물리치료",
        "specialty": "심평원 적정성평가 1등급 / 도심형 요양재활",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "광주광역시 서구 회재로 829 (매월동)",
        "phone": "062-608-8000",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA/심평원 적정성평가 1등급 확인",
        "notes": "심평원 적정성 평가 1등급 요양병원. 노인성 치매 및 중추신경계 만성 마비 환자를 위한 요양재활 전문 병상 운영."
    },
    {
        "id": "17",
        "district": "서구",
        "name": "서광요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활/암 케어",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활/암재활",
        "conditions": "암 환자 림프부종 재활, 만성 통증, 노인 물리치료",
        "specialty": "암 면역 요양 병동 / 운동재활치료실 연계",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "광주광역시 서구 화개중앙로 74 (금호동)",
        "phone": "062-603-8000",
        "sources": "http://sghospital.kr/",
        "verification": "HIRA 확인",
        "notes": "금호동에 위치하여 쾌적한 도심형 요양 환경. 암 요양 병동 및 재활의학과 연계 운동재활치료실 가동."
    },
    {
        "id": "18",
        "district": "광양시",
        "name": "광양수요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "만성 통증 완화, 근골격계 물리치료, 온열 치료",
        "specialty": "광양읍 소재 / 맞춤형 통증 관리",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "전라남도 광양시 광양읍 매천로 845",
        "phone": "061-760-8275",
        "sources": "http://www.gysuyh.co.kr/",
        "verification": "HIRA 확인",
        "notes": "광양읍에 위치한 재활의학과 보유 요양병원. 만성 질환 환자를 위한 맞춤형 온열 치료 및 근골격계 통증 완화 재활물리치료 전문."
    },
    {
        "id": "19",
        "district": "화순군",
        "name": "백재활요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활/암케어",
        "conditions": "뇌졸중 마비, 정형계 수술후 재활, 통증 도수치료",
        "specialty": "재활의학과 전문의 상주 / 전문 도수치료",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "전라남도 화순군 화순읍 충의로 125 (일심리)",
        "phone": "061-370-1300",
        "sources": "http://www.bio100hospital.com/",
        "verification": "HIRA 확인",
        "notes": "화순의 대표적인 재활 특화 요양병원. 재활의학과 전문의 진료 하에 정형계 및 중추신경계 마비 재활 치료."
    },
    {
        "id": "20",
        "district": "여수시",
        "name": "사랑재활요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌졸중 후유증 마비, 중추신경 마비, 일대일 운동재활",
        "specialty": "여수 봉산동 소재 / 맞춤 운동 및 작업치료",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "전라남도 여수시 봉산남4길 17 (봉산동)",
        "phone": "061-640-1000",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "여수 봉산동 소재. 재활의학과 전문의 상주. 중추신경계 마비 및 뇌졸중 후유증 일대일 맞춤 물리재활치료."
    },
    {
        "id": "21",
        "district": "목포시",
        "name": "부부요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 노인재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "관절 가동성 마비, 만성 퇴행성 통증, 노인 물리치료",
        "specialty": "고령 환자 특화 보존 치료 / 석현동 병원가",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "전라남도 목포시 통일대로 75 (석현동)",
        "phone": "061-280-9999",
        "sources": "http://boobooh.co.kr/",
        "verification": "HIRA 확인",
        "notes": "재활의학과 전문의 상주 하에 고령 환자 맞춤 통증 조절 및 관절 가동성 유지 물리치료실 가동."
    },
    {
        "id": "22",
        "district": "목포시",
        "name": "목포성심요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 치매/재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "노인성 치매, 만성 뇌졸중 마비, 동작 유지 훈련",
        "specialty": "의료법인 새한의료재단 / 대규모 치매·재활병상",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "전라남도 목포시 대양산단로 50 (대양동)",
        "phone": "061-285-8855",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "의료법인 새한의료재단. 재활의학과 전문의 진료 및 대규모 노인 재활/치매 안심 병상 가동."
    },
    {
        "id": "23",
        "district": "화순군",
        "name": "화순군립요양병원",
        "type": "요양병원",
        "inclusion": "공립요양병원 적정성 1등급",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "치매 케어, 뇌졸중 만성 마비, 작업훈련, 관절 회복 물리치료",
        "specialty": "공립노인전문요양 / 심평원 적정성 1등급",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "전라남도 화순군 화순읍 지강로 337",
        "phone": "061-370-1100",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA/심평원 적정성평가 1등급 확인",
        "notes": "군립 공공요양병원으로 심평원 적정성 평가 1등급 획득. 치매안심병원 지정 및 체계적인 물리재활치료 제공."
    },
    {
        "id": "24",
        "district": "목포시",
        "name": "보궁요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 적정성 1등급",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "양한방 보존 재활, 근골격계 관절 통증 조절, 노인 케어",
        "specialty": "심평원 적정성평가 1등급 / 양한방 협진",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "전라남도 목포시 연산백련로 4-11 (용해동)",
        "phone": "061-274-1234",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA/심평원 적정성평가 1등급 확인",
        "notes": "2년 연속 심평원 적정성 평가 1등급 획득. 양한방 협진 진료 및 근골격계 통증 조절 물리치료실 운영."
    },
    {
        "id": "25",
        "district": "순천시",
        "name": "순천만요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 적정성 1등급",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "고령 환자 만성 통증, 뇌졸중 후기 마비 관리, 자연 전원 요양",
        "specialty": "심평원 적정성평가 1등급 / 자연 친화적 쾌적 환경",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "전라남도 순천시 녹색로 542 (별량면)",
        "phone": "061-746-9900",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA/심평원 적정성평가 1등급 확인",
        "notes": "순천만 습지 인근 자연 친화적 입지. 심평원 적정성 평가 1등급으로 고령 및 만성 뇌졸중 환자를 위한 요양재활 중심 운영."
    },
    {
        "id": "26",
        "district": "화순군",
        "name": "전남제일요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 적정성 1등급",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "항암 면역 케어, 수술후 물리재활, 림프부종 재활",
        "specialty": "심평원 적정성평가 1등급 / 면역 및 정형재활 병행",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "전라남도 화순군 화순읍 학포로 2673",
        "phone": "061-370-0100",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA/심평원 적정성평가 1등급 확인",
        "notes": "심평원 적정성 평가 1등급 요양병원. 암 면역 케어와 물리재활치료 연동 시스템."
    },
    {
        "id": "27",
        "district": "순천시",
        "name": "메디팜요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "중추신경계 마비, 파킨슨병, 고령 노인 재활, 운동치료",
        "specialty": "재활의학과 전문의 상주 / 자연 친화적 입지",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "전라남도 순천시 팔마로 347 (인월동)",
        "phone": "061-740-5000",
        "sources": "http://www.medifarm.kr/",
        "verification": "HIRA 확인",
        "notes": "재활의학과 전문의 상주 하에 체계적인 운동/작업치료를 병행하는 순천 내 재활 요양병원. 쾌적한 전원 환경과 병동 케어."
    },
    {
        "id": "28",
        "district": "나주시",
        "name": "나주노블요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌졸중 후기 요양, 노인성 마비, 기능 복원 훈련",
        "specialty": "나주 남평 신도시 소재 / 쾌적한 요양시설",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "전라남도 나주시 남평읍 강변도시길 11 (동소리)",
        "phone": "061-337-3300",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "나주 남평 강변도시에 위치하여 쾌적하며, 뇌경색 후기 요양 및 관절 기능 유지 보존적 재활물리치료 제공."
    },
    {
        "id": "29",
        "district": "목포시",
        "name": "목포더좋은요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 적정성 1등급",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "집중 통증 재활, 도수치료, 척추·관절 물리치료",
        "specialty": "심평원 적정성평가 1등급 / 도수 및 집중물리치료실",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "전라남도 목포시 포미로 45 (용해동)",
        "phone": "061-278-8275",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA/심평원 적정성평가 1등급 확인",
        "notes": "심평원 적정성 평가 1등급 요양병원. 집중 통증 클리닉 및 맞춤 도수치료실, 물리치료실 운영."
    },
    {
        "id": "30",
        "district": "광산구",
        "name": "광주시립요양병원",
        "type": "요양병원",
        "inclusion": "공립요양병원 적정성 1등급",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "치매 안심 케어, 뇌졸중 마비 요양재활, 공공의료 서비스",
        "specialty": "광주시립 제2요양병원 / 심평원 적정성 1등급",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "광주광역시 광산구 삼거길 85 (덕림동)",
        "phone": "062-949-5200",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA/심평원 적정성평가 1등급 확인",
        "notes": "광주광역시립 제2요양병원. 심평원 적정성 평가 1등급 및 공공 노인 보건의료 서비스 거점으로 표준 요양재활 가이드 적용."
    }
];
