window.REHAB_DATA = [
    {
        "id": "1",
        "district": "강북구",
        "name": "국립재활원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 소아재활, 근골격계 재활",
        "specialty": "보건복지부 지정 회복기 지정 / 산재 재활인증",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "서울특별시 강북구 삼각산로 58",
        "phone": "02-901-1700",
        "sources": "https://www.nrc.go.kr/nrc/main.do",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관 (2026.03 ~ 2029.02). 국가 차원의 전문재활 중심 기관으로 간호간병통합서비스 제공."
    },
    {
        "id": "2",
        "district": "종로구",
        "name": "로이병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 근골격계 재활",
        "specialty": "보건복지부 지정 회복기 지정",
        "recovery": "지정(제3기)",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "서울특별시 종로구 평창문화로 75",
        "phone": "1644-7541",
        "sources": "",
        "verification": "보건복지부/HIRA 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관. 뇌신경 재활 및 수술 후 회복 치료 제공."
    },
    {
        "id": "3",
        "district": "영등포구",
        "name": "명지춘혜재활병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 근골격계 재활",
        "specialty": "보건복지부 지정 회복기 지정 / 산재 재활인증",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "서울특별시 영등포구 대림로 223",
        "phone": "02-3284-7777",
        "sources": "https://mjchoonhey.co.kr",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관. 뇌/척수 전문재활 및 로봇 재활 시스템 도입."
    },
    {
        "id": "4",
        "district": "은평구",
        "name": "서울재활병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활/소아재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 소아마비/발달지연, 근골격계 재활",
        "specialty": "보건복지부 지정 회복기 지정 / 소아재활 특화 / 산재 재활인증",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "서울특별시 은평구 갈현로11길 30",
        "phone": "02-6020-3000",
        "sources": "",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관. 영유아부터 청소년, 성인에 이르는 전 생애주기별 재활치료망 완비."
    },
    {
        "id": "5",
        "district": "강서구",
        "name": "서울큰나무병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 근골격계 재활",
        "specialty": "보건복지부 지정 회복기 지정",
        "recovery": "지정(제3기)",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "서울특별시 강서구 강서로 206",
        "phone": "02-2695-1155",
        "sources": "https://seoul-big-tree.com",
        "verification": "보건복지부/HIRA 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관. 뇌신경계 질환 집중 재활 치료 및 쾌적한 입원실 환경."
    },
    {
        "id": "6",
        "district": "관악구",
        "name": "서울퍼스트병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 근골격계 재활, 노인성 질환",
        "specialty": "보건복지부 지정 회복기 지정 / 간호간병통합서비스",
        "recovery": "지정(제3기)",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "서울특별시 관악구 은천로 51 (봉천동, 은호빌딩)",
        "phone": "02-882-6900",
        "sources": "https://sfhospital.co.kr",
        "verification": "보건복지부/HIRA 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관. 뇌신경계 및 근골격계 질환 맞춤형 재활, 간호간병통합서비스."
    },
    {
        "id": "7",
        "district": "송파구",
        "name": "송파드림재활병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 중추신경계 손상",
        "specialty": "보건복지부 지정 회복기 지정 / 산재 재활인증",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "서울특별시 송파구 송이로 111 (가락동)",
        "phone": "02-430-1122",
        "sources": "https://sd-dream.co.kr",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관. 쾌적한 1:1 환자 맞춤형 전문 재활치료 시스템 구축."
    },
    {
        "id": "8",
        "district": "구로구",
        "name": "에이치플러스자립병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 근골격계 손상",
        "specialty": "보건복지부 지정 회복기 지정 / 신경재활 특화",
        "recovery": "지정(제3기)",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "서울특별시 구로구 공원로6가길 4 (구로동, 고려수타워)",
        "phone": "02-1577-2588",
        "sources": "",
        "verification": "보건복지부/HIRA 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관. 신경계 집중 재활 치료 및 일상 자립 훈련 프로그램 강점."
    },
    {
        "id": "9",
        "district": "광진구",
        "name": "제니스병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/암재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 암 재활, 근골격계 질환",
        "specialty": "보건복지부 지정 회복기 지정 / 한·양방 협진",
        "recovery": "지정(제3기)",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "서울특별시 광진구 자양로 215 (구의동)",
        "phone": "02-3436-8888",
        "sources": "",
        "verification": "보건복지부/HIRA 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관. 암 수술 후 재활 및 뇌/척수 신경재활 동시 전문 운영."
    },
    {
        "id": "10",
        "district": "강남구",
        "name": "청담병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 신경마비, 근골격계 재활",
        "specialty": "보건복지부 지정 회복기 지정 / 로봇재활기기 완비 / 일상생활동작(ADL) 훈련 특화",
        "recovery": "지정(제3기)",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "서울특별시 강남구 삼성로147길 46 (청담동)",
        "phone": "02-2104-2000",
        "sources": "http://www.cdrusk.co.kr/renewal/",
        "verification": "보건복지부/HIRA 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관. 최신형 로봇 재활 장비 도입 및 내원 환경과 입원 만족도가 높은 프리미엄 재활병원."
    },
    {
        "id": "11",
        "district": "강북구",
        "name": "포근한병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 고령환자 마비재활",
        "specialty": "보건복지부 지정 회복기 지정",
        "recovery": "지정(제3기)",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "서울특별시 강북구 도봉로 266 (미아동)",
        "phone": "02-986-9988",
        "sources": "",
        "verification": "보건복지부/HIRA 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관. 공식 홈페이지가 확인되지 않으므로 클릭 시 네이버 홈페이지 검색 결과로 대체 연동됩니다."
    },
    {
        "id": "12",
        "district": "중랑구",
        "name": "러스크서울병원",
        "type": "요양병원",
        "inclusion": "요양병원 전문재활 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/요양외래",
        "conditions": "뇌졸중, 척수손상, 파킨슨병, 암재활, 수술후 회복",
        "specialty": "전문재활치료실 운영 / 요양병원 인증",
        "recovery": "해당없음",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "서울특별시 중랑구 망우로 470 (망우동)",
        "phone": "02-3426-0100",
        "sources": "",
        "verification": "HIRA/공단 확인",
        "notes": "러스크 재활 네트워크 병원으로 뇌졸중, 암 재활 등 특화된 물리치료 및 작업치료 제공."
    },
    {
        "id": "13",
        "district": "강남구",
        "name": "강남구립행복요양병원",
        "type": "요양병원",
        "inclusion": "공공요양병원/재활 가능",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/집중요양",
        "conditions": "노인성 질환, 치매, 뇌졸중 후유증, 마비 재활",
        "specialty": "강남구립 공공의료 / 치매적정성 1등급",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "서울특별시 강남구 헌릉로590길 60 (세곡동)",
        "phone": "02-6053-2114",
        "sources": "",
        "verification": "HIRA 확인",
        "notes": "강남구가 설립하여 공공의료를 제공하는 요양병원. 넓은 재활치료센터와 야외 산책로 구비."
    },
    {
        "id": "14",
        "district": "강남구",
        "name": "네이처요양병원",
        "type": "요양병원",
        "inclusion": "특화재활 요양병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/로봇재활",
        "conditions": "뇌졸중, 척수손상, 근골격계 재활, 인공관절 수술후 재활",
        "specialty": "보행 로봇재활 장비 구비",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "서울특별시 강남구 헌릉로569길 21-40 (세곡동)",
        "phone": "02-575-5114",
        "sources": "",
        "verification": "HIRA/홈페이지 확인",
        "notes": "도심 속 숲세권에 위치하여 쾌적한 재활이 가능한 프리미엄급 재활요양병원. 첨단 3D 보행 로봇 재활 운영."
    },
    {
        "id": "15",
        "district": "성북구",
        "name": "성북서울요양병원",
        "type": "요양병원",
        "inclusion": "전문재활 요양병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/집중치료",
        "conditions": "뇌졸중, 파킨슨병, 척수손상, 뇌 손상, 노인성 만성질환",
        "specialty": "신경과 및 재활의학과 협진",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "서울특별시 성북구 종암로 31 (종암동)",
        "phone": "02-6312-3700",
        "sources": "",
        "verification": "HIRA 확인",
        "notes": "종암동에 위치. 신경과, 가정의학과와 협진하여 환자 상태 맞춤형 전문 재활치료를 병행 시행."
    },
    {
        "id": "16",
        "district": "서대문구",
        "name": "서울중앙요양병원",
        "type": "요양병원",
        "inclusion": "투석/재활 병행 요양병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/인공신장",
        "conditions": "만성 신부전(투석), 뇌졸중 후유증, 만성질환 재활",
        "specialty": "인공신장실 운영 / 투석환자 맞춤 재활",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "서울특별시 서대문구 충정로 71-5 (충정로2가)",
        "phone": "02-3147-0999",
        "sources": "",
        "verification": "HIRA/홈페이지 확인",
        "notes": "서대문역 인근 도심형 요양병원. 투석 치료를 받으면서 전문의 상주 재활치료를 병행할 수 있어 신부전 합병 환자에게 추천."
    },
    {
        "id": "17",
        "district": "영등포구",
        "name": "한강성심병원",
        "type": "종합병원",
        "inclusion": "종합병원/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/입원재활/화상재활",
        "conditions": "화상 흉터 및 관절구축 재활, 중추/말초신경 손상",
        "specialty": "보건복지부 지정 화상전문병원 / 산재 재활인증",
        "recovery": "해당없음",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "서울특별시 영등포구 버드나루로7길 12 (영등포동7가)",
        "phone": "02-2639-5114",
        "sources": "https://hgb.hallym.or.kr",
        "verification": "보건복지부/공단 확인",
        "notes": "국내 유일의 보건복지부 지정 화상전문 대학병원으로, 화상 근골격 및 관절 구축 극복 전문 재활 치료의 선두 주자. 근로복지공단 산재 재활인증 의료기관."
    }
];
