window.REHAB_DATA = [
    {
        "id": "1",
        "district": "청주시",
        "name": "씨엔씨푸른병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 수술 후 집중재활, 소아재활",
        "specialty": "보건복지부 회복기 지정 / 산재 재활인증",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "충청북도 청주시 흥덕구 2순환로 1234 (강서동)",
        "phone": "043-291-8114",
        "sources": "https://pf.kakao.com/_xeKxnQK",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관 (2026.03 ~ 2029.02). 근로복지공단 산재 전문재활인증의료기관. 뇌신경 및 관절 재활 특화. 공식 소식은 카카오톡 채널 참고."
    },
    {
        "id": "2",
        "district": "청주시",
        "name": "아이엠재활병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활/낮병동",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 소아재활, 근골격계 집중재활",
        "specialty": "보건복지부 회복기 지정 / 산재 재활인증",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "충청북도 청주시 서원구 모충로 32 (모충동)",
        "phone": "043-263-0111",
        "sources": "http://www.imrh.kr/",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관. 근로복지공단 산재 재활인증기관. 보건복지부 장관 표창 수상, 재활 및 소아재활 특화 병동 운영."
    },
    {
        "id": "3",
        "district": "청주시",
        "name": "첼로병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 파킨슨병, 근골격계 재활",
        "specialty": "보건복지부 회복기 지정 / 산재 재활인증",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "충청북도 청주시 청원구 2순환로 120 (주성동)",
        "phone": "043-211-9000",
        "sources": "http://청주재활병원.com",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관 및 산재 재활인증기관. 로봇 재활 치료기 도입 및 간호간병통합서비스 병동 운영."
    },
    {
        "id": "4",
        "district": "청주시",
        "name": "마이크로재활병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 골절 및 수술 후 재활",
        "specialty": "보건복지부 회복기 지정 / 수술 및 재활 협진",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청북도 청주시 흥덕구 직지대로 637 (운천동)",
        "phone": "043-265-0071",
        "sources": "https://micromedicalcenter.com/rehabilitation/",
        "verification": "보건복지부/HIRA 확인",
        "notes": "구 마이크로요양병원에서 종별 전환을 통해 제3기 회복기 재활의료기관으로 신규 지정됨. 마이크로병원(정형외과 등)과의 연계 강점."
    },
    {
        "id": "5",
        "district": "청주시",
        "name": "충북대학교병원",
        "type": "종합병원",
        "inclusion": "상급종합/산재 재활인증",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "급성기/입원재활/외래재활",
        "conditions": "급성기 뇌졸중, 척수마비, 소아마비 및 발달지연, 스포츠 손상 재활",
        "specialty": "충북 유일 상급종합병원 / 산재 재활인증",
        "recovery": "해당없음",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청북도 청주시 서원구 1순환로 776 (개신동)",
        "phone": "043-269-6114",
        "sources": "https://www.cbnuh.or.kr/",
        "verification": "HIRA/공단 확인",
        "notes": "충북 유일의 상급종합병원이자 지역 거점 의료기관. 급성기 수술 후 조기 재활 치료 시스템이 매우 우수함. 산재보험 전문재활인증."
    },
    {
        "id": "6",
        "district": "청주시",
        "name": "충청북도 청주의료원",
        "type": "종합병원",
        "inclusion": "지역 책임의료기관 재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "급성기/입원재활/외래재활",
        "conditions": "뇌졸중 및 뇌손상 재활, 퇴행성 관절 질환, 외래 물리치료",
        "specialty": "공공보건의료 수행기관 / 재활센터 운영",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청북도 청주시 서원구 흥덕로 48 (사직동)",
        "phone": "043-279-0114",
        "sources": "https://www.cjmc.or.kr/",
        "verification": "HIRA 확인",
        "notes": "충청북도 도립 공공병원으로 합리적인 진료비와 전문적인 재활센터 인프라 보유. 공공재활 및 물리치료 활성화."
    },
    {
        "id": "7",
        "district": "청주시",
        "name": "청주성모병원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "급성기/입원재활/외래재활",
        "conditions": "뇌졸중 치료 후 조기 재활, 스포츠 의학 및 근골격 재활",
        "specialty": "가톨릭 의료원 협진 / 우수 의료진",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청북도 청주시 청원구 주성로 173-19 (율량동)",
        "phone": "043-219-8000",
        "sources": "http://www.ccmc.or.kr",
        "verification": "HIRA 확인",
        "notes": "청주 북부 권역의 대표적인 가톨릭계 종합병원. 뇌신경 센터 등과의 긴밀한 협진으로 빠른 초기 재활 시행."
    },
    {
        "id": "8",
        "district": "청주시",
        "name": "청주효성병원",
        "type": "종합병원",
        "inclusion": "재활의학과 보유 종합병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "급성기/입원재활/외래재활",
        "conditions": "뇌혈관 질환 후 재활, 정형외과 수술 후 재활, 소아 및 성인 물리치료",
        "specialty": "상당구 거점 종합병원 / 재활치료실 완비",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청북도 청주시 상당구 쇠내로 16 (금천동)",
        "phone": "043-221-5000",
        "sources": "http://5388hyosunghospital.com",
        "verification": "HIRA 확인",
        "notes": "청주 금천동 소재 종합병원. 재활의학과 전문의 상주 및 물리치료, 작업치료, 도수치료 프로그램 제공."
    },
    {
        "id": "9",
        "district": "청주시",
        "name": "청주시립요양병원",
        "type": "요양병원",
        "inclusion": "시립 공공요양병원 재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/장기입원",
        "conditions": "노인성 질환, 중풍 및 뇌졸중 마비 후 재활, 노인 작업치료",
        "specialty": "청주시립 / 공공요양병원 인프라",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청북도 청주시 서원구 궁뜰로62번길 29 (장성동)",
        "phone": "043-220-8000",
        "sources": "http://www.cjshospital.co.kr/",
        "verification": "HIRA 확인",
        "notes": "청주시가 설립한 공공 요양병원. 합리적 비용으로 전문 재활의학과 전문의의 장기 요양 및 기능 회복 재활 제공."
    },
    {
        "id": "10",
        "district": "청주시",
        "name": "청주탑요양병원",
        "type": "요양병원",
        "inclusion": "재활의학과 보유 요양병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/장기입원",
        "conditions": "뇌질환 후유증, 노인성 마비 질환, 연하(삼킴) 장애, 장기 요양",
        "specialty": "요양재활 특화 / 넓은 재활치료실",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청북도 청주시 서원구 궁뜰로 16 (미평동)",
        "phone": "043-296-5000",
        "sources": "http://www.cjtop.co.kr",
        "verification": "HIRA 확인",
        "notes": "재활의학과 전문의 상주로 체계적인 노인 요양 및 만성기 재활 치료를 동시에 진행."
    },
    {
        "id": "11",
        "district": "청주시",
        "name": "스마일재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문의 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/물리치료",
        "conditions": "척추/골반 교정, 도수치료, 비수술 만성 통증 조절, 재활 운동",
        "specialty": "복대동 재활 전문 / 맞춤형 물리치료",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "충청북도 청주시 흥덕구 대농로 50, 302호·303호 (복대동)",
        "phone": "043-284-7533",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "청주 지웰시티 인근에 위치한 비수술적 통증재활 특화 의원. 자세 교정 및 물리치료 프로그램 운영."
    },
    {
        "id": "12",
        "district": "청주시",
        "name": "삼성재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문의 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/물리치료",
        "conditions": "목/허리 디스크 통증, 관절염 재활, 충격파 치료, 물리치료",
        "specialty": "복대동 재활 전문 / 정밀 통증 치료",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "충청북도 청주시 흥덕구 대농로 49, 4층 404호 (복대동)",
        "phone": "043-234-3433",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "삼성서울병원 출신 전문의 진료. 정밀 신경차단술 및 1:1 도수치료실 보유."
    },
    {
        "id": "13",
        "district": "청주시",
        "name": "연세재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문의 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/물리치료",
        "conditions": "자세 불균형, 스포츠 손상 재활, 도수치료, 만성 관절 통증",
        "specialty": "복대동 재활 전문 / 체형 및 척추 교정",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "충청북도 청주시 흥덕구 내수동로 2, 10층 (복대동, 새롬메디빌딩)",
        "phone": "043-273-1122",
        "sources": "http://ysrehab.com",
        "verification": "HIRA 확인",
        "notes": "체형 분석기를 활용한 맞춤형 교정 치료 및 고주파 도수치료 특화."
    },
    {
        "id": "14",
        "district": "청주시",
        "name": "율량팔팔재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문의 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/물리치료",
        "conditions": "비수술 관절 치료, 오십견, 디스크 신경치료, 도수치료",
        "specialty": "율량동 재활 전문 / 야간진료 운영",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "충청북도 청주시 청원구 율봉로 97, 베리돈타워 2층 (율량동)",
        "phone": "043-715-8575",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "청주 율량지구 베리돈타워 위치. 쾌적한 1:1 도수치료 공간과 충격파 치료기 다수 완비."
    },
    {
        "id": "15",
        "district": "충주시",
        "name": "건국대학교 충주병원",
        "type": "종합병원",
        "inclusion": "충주 지역 거점 대학병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "급성기/입원재활/외래재활",
        "conditions": "뇌신경재활, 척수마비 재활, 관절 및 근골격계 통증 재활",
        "specialty": "대학병원 / 종합 재활치료",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청북도 충주시 국원대로 82 (문화동)",
        "phone": "043-840-8200",
        "sources": "https://www.kuh.co.kr/",
        "verification": "HIRA 확인",
        "notes": "충주 및 충북 북부 지역의 대표적인 대학 부속 종합병원. 재활의학과 전문의 및 대규모 재활치료실 운영."
    },
    {
        "id": "16",
        "district": "충주시",
        "name": "충주미래병원",
        "type": "병원",
        "inclusion": "재활의학과 전문의 상주",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활/물리치료",
        "conditions": "뇌졸중(중풍) 후유증, 외상성 뇌손상, 척수마비, 정형외과 수술 후 집중재활",
        "specialty": "충주 지역 재활 특화 / 넓은 치료실",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청북도 충주시 국원대로 99 (교현동)",
        "phone": "043-852-9119",
        "sources": "https://cjmirae.com",
        "verification": "HIRA 확인",
        "notes": "의료법인 대성의료재단 충주미래병원. 전문 재활치료사 다수 근무, 넓은 운동/작업치료실 및 연하장애 치료 도입."
    },
    {
        "id": "17",
        "district": "충주시",
        "name": "충주시노인전문병원",
        "type": "요양병원",
        "inclusion": "시립 공공요양병원 재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/장기입원/치매케어",
        "conditions": "치매, 뇌졸중 후유마비, 노인성 근력약화 물리치료",
        "specialty": "충주시립 / 공공의료 치매·재활 거점",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청북도 충주시 동량면 충원대로 1398",
        "phone": "043-855-9393",
        "sources": "http://www.cjnoin.com",
        "verification": "HIRA 확인",
        "notes": "충주시가 건립한 노인전문 시립 병원. 재활의학과 전문의 지도하에 안전하고 따뜻한 물리치료 및 작업치료 시행."
    },
    {
        "id": "18",
        "district": "충주시",
        "name": "김신경재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문의 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/물리치료",
        "conditions": "근골격계 질환, 디스크 통증, 마취통증, 자세 교정 및 재활",
        "specialty": "외래 집중 / 도수치료 및 통증재활",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "충청북도 충주시 봉계1길 58, 4층 (칠금동)",
        "phone": "043-855-7588",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "충주 터미널 인근에 위치하여 접근성이 높음. 1:1 도수치료 및 체외충격파 등 통증·재활 클리닉 특화."
    },
    {
        "id": "19",
        "district": "충주시",
        "name": "홍재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문의 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/물리치료",
        "conditions": "신경통, 관절 통증, 체형 교정, 물리치료",
        "specialty": "통증재활 / 물리치료 특화",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "충청북도 충주시 봉계1길 66, 3층 (칠금동, 황금빌딩)",
        "phone": "043-848-7582",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "충주 칠금동에 위치한 의원으로 만성 통증 환자 대상의 물리치료와 신경블록 치료 제공."
    },
    {
        "id": "20",
        "district": "제천시",
        "name": "제천서울병원",
        "type": "종합병원",
        "inclusion": "제천 지역 거점 종합병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "급성기/입원재활/외래재활",
        "conditions": "중추신경계 마비 재활, 스포츠 손상 재활, 만성 통증",
        "specialty": "종합병원 / 뇌졸중 및 골절 후 재활",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청북도 제천시 숭문로 57 (서부동)",
        "phone": "043-640-7600",
        "sources": "https://www.seoulhp.co.kr/",
        "verification": "HIRA 확인",
        "notes": "제천 지역을 책임지는 거점 종합병원. 운동치료실 및 작업치료실을 갖춘 전문 재활 치료 제공."
    },
    {
        "id": "21",
        "district": "제천시",
        "name": "제천명지병원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "급성기/입원재활/외래재활",
        "conditions": "뇌졸중, 외상성 뇌손상, 척수 손상, 연하 장애 재활",
        "specialty": "심뇌혈관센터 연계 조기 재활",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청북도 제천시 내토로 991 (고암동)",
        "phone": "043-640-8114",
        "sources": "https://www.mjh.or.kr",
        "verification": "HIRA 확인",
        "notes": "재활의학과 전문의 진료. 심뇌혈관센터 연계로 뇌졸중 발병 초기부터 집중적인 급성기 재활 치료 제공."
    },
    {
        "id": "22",
        "district": "제천시",
        "name": "예성요양병원",
        "type": "요양병원",
        "inclusion": "재활의학과 전문의 상주",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/장기입원/운동치료",
        "conditions": "뇌 마비 후유증, 노인성 만성 통증, 척수 손상 만성기 재활, 작업치료",
        "specialty": "제천 내 재활의학과 전문의 상주 요양병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청북도 제천시 용두천로 333 (청전동)",
        "phone": "043-653-7700",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "제천 청전동 소재 요양병원. 재활의학과 전문의 지도하에 운동치료실, 작업치료실을 운영하며 고령 환자 집중 케어."
    },
    {
        "id": "23",
        "district": "제천시",
        "name": "박용수재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문의 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/물리치료",
        "conditions": "오십견, 관절염, 만성 요통, 물리치료, 비수술 통증 재활",
        "specialty": "외래 도수치료 / 신경통증 클리닉",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "충청북도 제천시 의병대로 105 (남천동)",
        "phone": "043-644-1119",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "제천 시내에 위치하여 고령 환자들의 통증 조절 및 관절 기능 회복 물리치료 제공."
    },
    {
        "id": "24",
        "district": "보은군",
        "name": "하나마취통증의학과의원",
        "type": "의원",
        "inclusion": "재활치료실 보유 통증의학과",
        "rehabDept": "없음",
        "specialists": "전문의 없음",
        "careType": "외래물리치료/도수치료",
        "conditions": "허리디스크 통증 완화, 관절 가동성 회복, 도수치료",
        "specialty": "보은 지역 통증 치료 및 기능 개선 재활",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "충청북도 보은군 보은읍 삼산남로 36",
        "phone": "043-542-7582",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "마취통증의학과 중심이나 보은 지역에서 어르신들의 만성 통증 완화와 기능 회복 물리치료를 집중 제공."
    },
    {
        "id": "25",
        "district": "옥천군",
        "name": "옥천탑재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문의 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/물리치료",
        "conditions": "만성 근골격계 통증, 퇴행성 척추관절 질환, 도수 및 견인치료",
        "specialty": "옥천 유일 재활의학과 전문의 의원",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "충청북도 옥천군 옥천읍 삼금로 11, 5층",
        "phone": "043-731-7588",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "옥천 내 대표적인 비수술적 통증재활치료 의원. 정밀 진단 후 개별 물리치료 시행."
    },
    {
        "id": "26",
        "district": "영동군",
        "name": "한사랑재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문의 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/물리치료",
        "conditions": "목/허리 디스크, 관절통, 신경차단술, 도수치료",
        "specialty": "영동군 유일 재활의학과 전문의 의원",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "충청북도 영동군 영동읍 중앙로1길 4",
        "phone": "043-745-7588",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "영동군 내에서 전문의를 통한 정교한 관절 및 신경 재활, 물리치료 처방이 가능한 유일한 곳."
    },
    {
        "id": "27",
        "district": "증평군",
        "name": "서울튼튼재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문의 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/물리치료",
        "conditions": "척추/골반 교정, 관절염 비수술 치료, 인대강화주사, 물리치료",
        "specialty": "증평 지역 유일의 재활의학과 의원",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "충청북도 증평군 증평읍 중앙로 184-1 (2, 3층)",
        "phone": "043-838-2600",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "증평 지역 유일의 재활의학과 의원. 최신 물리치료기기와 넓은 도수치료실 보유."
    },
    {
        "id": "28",
        "district": "진천군",
        "name": "진천중앙재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문의 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/물리치료",
        "conditions": "근골격계 만성통증, 척추관절 질환, 도수치료",
        "specialty": "진천군 내 대표 재활의학과 의원",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "충청북도 진천군 진천읍 중앙서1길 6",
        "phone": "043-534-7117",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "진천군 진천읍 중심가 위치. 고령 환자 및 직장인을 위한 도수·물리치료 처방 및 통증 클리닉 운영."
    },
    {
        "id": "29",
        "district": "괴산군",
        "name": "괴산성모병원",
        "type": "병원",
        "inclusion": "괴산 지역 거점 재활치료",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활/물리치료",
        "conditions": "수술 후 회복 재활, 만성 통증, 고령 환자 기능 보존 재활",
        "specialty": "괴산군 유일 종합 재활 치료 병원",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청북도 괴산군 괴산읍 임꺽정로 132",
        "phone": "043-830-5400",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "괴산 유일의 거점 병원으로 대규모 재활치료 시설을 갖추고 시골 고령 환자들에게 전문 재활 서비스를 제공."
    },
    {
        "id": "30",
        "district": "음성군",
        "name": "인곡자애병원",
        "type": "병원",
        "inclusion": "요양 및 완화 재활",
        "rehabDept": "없음",
        "specialists": "전문의 없음",
        "careType": "요양입원/물리치료",
        "conditions": "노인성 질환, 중증 치매 및 요양 환자의 만성 물리치료",
        "specialty": "가톨릭 꽃동네 재단 / 공익적 병원",
        "recovery": "해당없음",
        "workersComp": "미지정",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "충청북도 음성군 맹동면 꽃동네길 37",
        "phone": "043-879-0300",
        "sources": "http://www.kkot.or.kr",
        "verification": "HIRA 확인",
        "notes": "꽃동네 내 복지 의료기관으로 소외 계층 및 만성 요양 환자 중심의 따뜻한 돌봄과 만성 물리치료 제공."
    },
    {
        "id": "31",
        "district": "음성군",
        "name": "굿모닝요양병원",
        "type": "요양병원",
        "inclusion": "재활의학과 전문의 상주 요양병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/장기입원/물리치료",
        "conditions": "노인성 관절 및 신경 질환, 중풍 치료 후 요양재활, 만성 물리치료",
        "specialty": "음성 내 전문의 상주 재활 요양병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청북도 음성군 대소면 대금로 532",
        "phone": "043-878-8600",
        "sources": "http://www.goodmorninghp.co.kr/",
        "verification": "HIRA 확인",
        "notes": "음성 대소면 위치. 재활의학과 전문의 상주로 체계적 물리치료 및 노인 전문 만성기 재활 운영."
    },
    {
        "id": "32",
        "district": "단양군",
        "name": "늘편한정형외과의원",
        "type": "의원",
        "inclusion": "재활치료실 보유 정형외과",
        "rehabDept": "없음",
        "specialists": "전문의 없음",
        "careType": "외래물리치료/도수치료",
        "conditions": "퇴행성 마비 및 통증, 척추 골절 회복, 물리치료",
        "specialty": "단양 지역 통증 및 재활 물리치료",
        "recovery": "해당없음",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "충청북도 단양군 단양읍 삼봉로 294",
        "phone": "043-421-7588",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "재활의학과 전문의는 없으나 물리치료실이 잘 완비되어 단양 지역 어르신들의 재활 물리치료 거점으로 기능."
    }
];
