window.REHAB_DATA = [
    {
        "id": "1",
        "district": "유성구",
        "name": "유성웰니스재활병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 소아재활, 근골격계 재활",
        "specialty": "보건복지부 회복기 지정 / 산재 재활인증",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "대전광역시 유성구 계룡로 6 (봉명동)",
        "phone": "042-824-6900",
        "sources": "http://www.yswellness.co.kr/",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "대전·충남 대표 회복기 재활의료기관. 보건복지부 지정 제3기 회복기 재활의료기관(2026.03 ~ 2029.02). 간호간병통합서비스 및 소아낮병동 운영."
    },
    {
        "id": "2",
        "district": "서구",
        "name": "다빈치병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 뇌성마비, 근골격계 재활",
        "specialty": "보건복지부 회복기 지정 / 산재 재활인증",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "대전광역시 서구 대덕대로 168 (갈마동)",
        "phone": "042-526-7500",
        "sources": "http://davincihospital.co.kr/",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관. 1:1 맞춤형 로봇재활치료기 도입. 넓고 쾌적한 재활치료실 완비."
    },
    {
        "id": "3",
        "district": "대덕구",
        "name": "대전웰니스병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 소아재활, 성인재활",
        "specialty": "보건복지부 회복기 지정 / 산재 재활인증",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "대전광역시 대덕구 동춘당로 90 (송촌동)",
        "phone": "042-630-1000",
        "sources": "http://www.djwellness.co.kr/",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "제3기 회복기 재활의료기관 지정. 뇌신경재활, 척수재활, 소아재활 특화. 간호간병통합서비스 및 스포츠재활센터 운영."
    },
    {
        "id": "4",
        "district": "서구",
        "name": "워크웰재활의학과병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활",
        "conditions": "뇌졸중, 척수손상, 뇌외상, 고관절 수술 후 재활",
        "specialty": "보건복지부 회복기 지정 / 맞춤형 보행치료",
        "recovery": "지정(제3기)",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "대전광역시 서구 한밭대로 701 (월평동)",
        "phone": "042-482-0100",
        "sources": "https://www.hira.or.kr",
        "verification": "보건복지부/HIRA 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관. 뇌병변 및 근골격 보행 재활에 집중 치료 제공."
    },
    {
        "id": "5",
        "district": "예산군",
        "name": "예산명지병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활",
        "conditions": "뇌졸중, 척수손상, 근골격계 수술 후 재활",
        "specialty": "보건복지부 회복기 지정 / 충남 북부 재활거점",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청남도 예산군 신안원로 83 (예산읍)",
        "phone": "041-330-7500",
        "sources": "http://myungjihp.co.kr/",
        "verification": "보건복지부/HIRA 확인",
        "notes": "충남 도내 군 단위 유일의 보건복지부 지정 제3기 회복기 재활의료기관. 지역사회 연계 재활서비스 제공."
    },
    {
        "id": "6",
        "district": "천안시",
        "name": "천안재활병원",
        "type": "병원",
        "inclusion": "재활의학과 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "중추신경계 손상, 척수손상, 근골격 수술 후 집중재활",
        "specialty": "로봇 보행 훈련 / 전문의 상주",
        "recovery": "비지정",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "충청남도 천안시 서북구 한들1로 88 (백석동)",
        "phone": "041-558-7588",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "보행재활로봇 도입, 환자 맞춤형 집중 입원 치료 프로그램을 운영. 다양한 신경계/근골격계 전문 재활치료실 완비."
    },
    {
        "id": "7",
        "district": "중구",
        "name": "충남대학교병원 (대전충청권역의료원)",
        "type": "종합병원",
        "inclusion": "권역재활의료센터 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 다수 상주",
        "careType": "급성기/외래재활/입원재활",
        "conditions": "뇌졸중, 척수손상, 소아재활, 암재활, 심폐재활",
        "specialty": "보건복지부 지정 권역재활전문센터 / 대학병원 협진",
        "recovery": "비지정",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "대전광역시 중구 문화로 282 (대사동)",
        "phone": "042-280-7114",
        "sources": "https://www.cnuh.co.kr/rehab/",
        "verification": "보건복지부/HIRA 확인",
        "notes": "국가 지정 대전충청권역 재활전문센터 운영. 급성기 수술 후 초기 재활과 고난도 복합재활치료 특화."
    },
    {
        "id": "8",
        "district": "대덕구",
        "name": "로하스활력요양병원",
        "type": "요양병원",
        "inclusion": "요양병원/재활/투석",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "재활요양/입원재활/인공신장",
        "conditions": "노인성 질환, 뇌졸중 후유증, 투석 필요 환자 재활",
        "specialty": "인공신장실(투석) 운영 / 중증 재활 요양",
        "recovery": "비지정",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "대전광역시 대덕구 대덕대로 1447 (신대동)",
        "phone": "042-638-7500",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "재활의학과 전문의 상주 및 물리치료사 다수 근무. 인공신장실을 함께 갖추어 신장 투석과 재활이 동시 필요한 환자에 최적."
    },
    {
        "id": "9",
        "district": "공주시",
        "name": "주은라파스요양병원",
        "type": "요양병원",
        "inclusion": "요양병원/산재인증",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "재활요양/입원재활",
        "conditions": "치매, 중풍, 파킨슨병, 산재 요양재활",
        "specialty": "근로복지공단 산재 재활인증요양병원 / 자연친화 요양",
        "recovery": "비지정",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청남도 공주시 검상안길 126 (검상동)",
        "phone": "041-858-7300",
        "sources": "http://www.jueunlafas.co.kr/",
        "verification": "공단/HIRA 확인",
        "notes": "근로복지공단 지정 산재 재활인증 요양병원. 넓은 부지의 자연 친화적 환경에서 집중적인 요양 및 재활 치료를 연계."
    },
    {
        "id": "10",
        "district": "천안시",
        "name": "천안충무병원",
        "type": "종합병원",
        "inclusion": "종합병원/재활의학과 있음",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "급성기/외래재활/일부입원",
        "conditions": "뇌혈관 질환 수술 후, 스포츠 손상 재활, 척추 통증",
        "specialty": "뇌심혈관 센터 연계 급성기 초기 재활",
        "recovery": "비지정",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청남도 천안시 동남구 다가말길 31 (쌍용동)",
        "phone": "041-550-7000",
        "sources": "http://www.cmh.or.kr/",
        "verification": "HIRA 확인",
        "notes": "천안 지역 거점 종합병원. 뇌신경센터와 정형외과 협진을 통해 수술 직후의 조기 재활 치료를 체계적으로 수행."
    },
    {
        "id": "11",
        "district": "아산시",
        "name": "아산충무병원",
        "type": "종합병원",
        "inclusion": "종합병원/재활의학과 있음",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "급성기/외래재활/협진입원",
        "conditions": "뇌손상, 척수손상, 관절 치환술 후 재활, 도수치료",
        "specialty": "심뇌혈관센터 협진 및 정형외과 수술 후 재활",
        "recovery": "비지정",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청남도 아산시 문화로 381 (모종동)",
        "phone": "041-536-6500",
        "sources": "http://www.asancmh.co.kr/",
        "verification": "HIRA 확인",
        "notes": "아산 내 종합병원. 넓은 재활치료실을 보유하고 있어 정형외과 및 신경외과 수술 환자 대상의 집중적인 외래/입원 재활 연계."
    },
    {
        "id": "12",
        "district": "서산시",
        "name": "충청남도 서산의료원",
        "type": "종합병원",
        "inclusion": "공공의료/재활의학과 있음",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/입원 연계",
        "conditions": "뇌졸중 후유재활, 근골격계 통증재활, 도수치료",
        "specialty": "지역거점 공공병원 / 무료 재활 연계 프로그램",
        "recovery": "비지정",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청남도 서산시 중앙로 149 (석림동)",
        "phone": "041-689-7000",
        "sources": "https://www.seosanmc.or.kr/",
        "verification": "HIRA/공식 확인",
        "notes": "서해안 중부 권역 거점 공공병원. 서울대학교병원 재활의학과 전문의 파견 협진 및 공공재활 프로그램 운영."
    },
    {
        "id": "13",
        "district": "홍성군",
        "name": "충청남도 홍성의료원",
        "type": "종합병원",
        "inclusion": "공공의료/재활의학과 있음",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/입원재활",
        "conditions": "중추신경계 마비재활, 척추·오십견 등 근골격계 재활",
        "specialty": "공공보건의료 협력체계 구축 / 한방·재활 협진",
        "recovery": "비지정",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청남도 홍성군 홍성읍 아문길 29-30",
        "phone": "041-630-6114",
        "sources": "https://www.hongmc.or.kr/",
        "verification": "HIRA/공식 확인",
        "notes": "충남 내포신도시 인근 공공병원. 신경계 재활치료실과 근골격계 물리치료실을 개별 운영하여 맞춤 케어."
    },
    {
        "id": "14",
        "district": "공주시",
        "name": "충청남도 공주의료원",
        "type": "종합병원",
        "inclusion": "공공의료/재활의학과 있음",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/입원재활",
        "conditions": "뇌졸중, 척수 손상, 도수치료, 물리치료",
        "specialty": "재활의학과 특화 / 어르신 맞춤 통증케어",
        "recovery": "비지정",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청남도 공주시 무령로 137 (웅진동)",
        "phone": "041-962-1114",
        "sources": "http://www.gongjumc.or.kr/",
        "verification": "HIRA/공식 확인",
        "notes": "신축 이전하여 최신식 재활치료 시설 보유. 외래 물리치료와 더불어 입원 환자 대상의 급성기 재활 인프라 제공."
    },
    {
        "id": "15",
        "district": "유성구",
        "name": "유성한가족요양병원",
        "type": "요양병원",
        "inclusion": "요양병원/재활의학과 있음",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "재활요양/입원재활",
        "conditions": "뇌외상, 파킨슨병, 노인성 질환, 골절 후 잔여 재활",
        "specialty": "중증환자 집중 케어 / 양·한방 협진",
        "recovery": "비지정",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "대전광역시 유성구 계룡로 141번길 29 (봉명동)",
        "phone": "042-717-0001",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "대규모 요양병원으로 전문 재활치료실을 구축. 입원 환자 중심의 물리치료, 작업치료 및 양한방 협진을 수행."
    },
    {
        "id": "16",
        "district": "동구",
        "name": "대전선병원",
        "type": "종합병원",
        "inclusion": "종합병원/재활의학과 있음",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/물리치료",
        "conditions": "스포츠 외상, 오십견, 디스크 비수술 재활, 관절 통증",
        "specialty": "관절/척추 센터 특화 및 외래 도수치료",
        "recovery": "비지정",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "대전광역시 동구 목척4길 21 (중동)",
        "phone": "1588-7011",
        "sources": "http://www.sunhospital.com/",
        "verification": "HIRA 확인",
        "notes": "대전 동구 중심가에 위치한 종합병원. 외래 물리치료센터와 운동 치료실을 통해 퇴원 후의 일상 기능 회복을 지원."
    },
    {
        "id": "17",
        "district": "중구",
        "name": "대전평화재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 있음",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/물리치료",
        "conditions": "근골격계 통증, 디스크, 측만증, 도수 및 체외충격파",
        "specialty": "비수술적 통증재활 전문 / 직장인 도수치료",
        "recovery": "비지정",
        "workersComp": "미지정",
        "autoInsurance": "가능",
        "dayRehab": "미운영",
        "address": "대전광역시 중구 중앙로 132 (대흥동)",
        "phone": "042-222-7582",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "재활의학과 전문의가 직접 진료하며 일대일 맞춤 도수치료와 척추 관절 통증 치료를 외래 위주로 운영."
    },
    {
        "id": "18",
        "district": "서구",
        "name": "대전한방병원 (대전대학교 대전한방병원)",
        "type": "한방병원",
        "inclusion": "한방재활/양한방협진",
        "rehabDept": "있음",
        "specialists": "한방재활 전문의 상주",
        "careType": "입원재활/외래재활/한방재활",
        "conditions": "중풍 후유증 한방재활, 안면마비, 교통사고 후유증",
        "specialty": "양·한방 통합 재활치료 / 교통사고 입원치료",
        "recovery": "비지정",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "대전광역시 서구 대덕대로 176 (둔산동)",
        "phone": "042-470-9000",
        "sources": "https://www.dju.ac.kr/daejeon/",
        "verification": "HIRA/공식 확인",
        "notes": "대전대학교 부속 한방병원. 침·뜸·추나 요법과 현대의학 물리치료가 결합된 통합 한방재활 케어 제공."
    },
    {
        "id": "19",
        "district": "계룡시",
        "name": "우리재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 있음",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/도수치료",
        "conditions": "척추 관절 통증, 자세교정, 도수치료, 소아 자세",
        "specialty": "계룡 지역 유일의 재활의학과 전문의 의원",
        "recovery": "비지정",
        "workersComp": "미지정",
        "autoInsurance": "가능",
        "dayRehab": "미운영",
        "address": "충청남도 계룡시 금암로 140 (금암동)",
        "phone": "042-841-8275",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "계룡시청 인근 위치. 소아 척추측만, 오십견, 퇴행성 관절염 환자를 위한 비수술적 통증재활 외래 진료."
    },
    {
        "id": "20",
        "district": "아산시",
        "name": "아산재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 있음",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/도수치료",
        "conditions": "체형 교정, 거북목, 스포츠 재활, 만성 통증",
        "specialty": "비수술 관절 척추 통증 치료 / 외래 집중 도수",
        "recovery": "비지정",
        "workersComp": "미지정",
        "autoInsurance": "가능",
        "dayRehab": "미운영",
        "address": "충청남도 아산시 온천대로 1412 (온천동)",
        "phone": "041-544-7585",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "온양온천역 인근 위치. 신경계 환자 외래 물리치료 및 척추 관절 도수치료 특화 의원."
    },
    {
        "id": "21",
        "district": "논산시",
        "name": "논산백제병원",
        "type": "종합병원",
        "inclusion": "종합병원/재활의학과 있음",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/입원 연계",
        "conditions": "뇌졸중 초기재활, 척수손상, 근골격계 수술후 재활",
        "specialty": "논산 지역 거점 종합병원 / 응급실 연계 안심케어",
        "recovery": "비지정",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청남도 논산시 시민로 294 (취암동)",
        "phone": "041-730-6000",
        "sources": "http://www.bjh.co.kr/",
        "verification": "HIRA 확인",
        "notes": "논산·계룡·금산 권역의 최대 종합병원. 급성기 질환 치료 후 통합 재활 및 요양 치료 연계 가능."
    },
    {
        "id": "22",
        "district": "당진시",
        "name": "당진종합병원",
        "type": "종합병원",
        "inclusion": "종합병원/재활의학과 있음",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/입원 연계",
        "conditions": "뇌질환 후유장애, 관절 수술 후 재활, 통증 도수치료",
        "specialty": "건강검진센터 연계 / 당진 최대 종합재활실",
        "recovery": "비지정",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청남도 당진시 반촌로 140 (송악읍)",
        "phone": "041-351-7000",
        "sources": "http://www.dangjinhp.com/",
        "verification": "HIRA 확인",
        "notes": "종합재활치료실을 확장 운영하여 신경계 재활과 근골격계 물리/도수치료를 원스톱으로 지원."
    },
    {
        "id": "23",
        "district": "서산시",
        "name": "서산탑재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 있음",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/도수치료",
        "conditions": "척추협착증, 디스크, 오십견, 체외충격파, 족저근막염",
        "specialty": "일대일 도수치료실 및 물리치료 장비 완비",
        "recovery": "비지정",
        "workersComp": "미지정",
        "autoInsurance": "가능",
        "dayRehab": "미운영",
        "address": "충청남도 서산시 안견로 195 (동문동)",
        "phone": "041-662-7533",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "서산 동부시장 인근 위치. 만성 퇴행성 척추관절 질환 환자들을 위한 정밀 외래 물리/도수치료 운영."
    },
    {
        "id": "24",
        "district": "보령시",
        "name": "신석재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 있음",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/물리치료",
        "conditions": "어깨 통증, 무릎 관절염, 디스크 통증, 수술 후 관리",
        "specialty": "보령 시내 재활의학과 전문의 진료 의원",
        "recovery": "비지정",
        "workersComp": "미지정",
        "autoInsurance": "가능",
        "dayRehab": "미운영",
        "address": "충청남도 보령시 한내로 16 (동대동)",
        "phone": "041-931-7588",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "보령 동대동 핵심 상권에 위치. 어르신 근골격계 통증 경감 및 만성 통증 비수술 외래 치료 특화."
    },
    {
        "id": "25",
        "district": "금산군",
        "name": "금산효사랑요양병원",
        "type": "요양병원",
        "inclusion": "요양병원/재활요양",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "재활요양/장기입원",
        "conditions": "치매, 중풍, 노인성 만성질환, 수술 후 회복 요양",
        "specialty": "노인성 질환 특화 요양 / 입원 물리치료",
        "recovery": "비지정",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청남도 금산군 금산읍 인삼로 32",
        "phone": "041-754-0011",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "만성 질환을 앓는 고령 환자들을 대상으로 전문 물리치료실에서 장기적인 유지 재활 및 요양 서비스 제공."
    },
    {
        "id": "26",
        "district": "부여군",
        "name": "부여성심요양병원",
        "type": "요양병원",
        "inclusion": "요양병원/재활물리치료",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "재활요양/장기입원",
        "conditions": "뇌졸중 후유증, 파킨슨, 노인성 관절염, 욕창 관리",
        "specialty": "양한방 협진 요양 / 재활 치료실 운영",
        "recovery": "비지정",
        "workersComp": "지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청남도 부여군 부여읍 성왕로 124",
        "phone": "041-837-7755",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "부여 시내 위치. 장기 입원 요양 환자들을 위한 기본적인 신경계/근골격계 물리치료 시설 운영."
    },
    {
        "id": "27",
        "district": "서천군",
        "name": "서천현대요양병원",
        "type": "요양병원",
        "inclusion": "요양병원/재활물리치료",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "재활요양/장기입원",
        "conditions": "고령 환자 만성 질환, 중풍 재활, 호스피스 완화",
        "specialty": "치매/중풍 어르신 안심 케어 / 맞춤 물리치료",
        "recovery": "비지정",
        "workersComp": "미지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "충청남도 서천군 서천읍 군사길 9",
        "phone": "041-953-6114",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "서천 읍내에 위치하여 대중교통 접근이 용이. 노인성 질환의 진행을 늦추기 위한 유지 목적의 물리치료 진행."
    },
    {
        "id": "28",
        "district": "청양군",
        "name": "청양군보건의료원",
        "type": "의원",
        "inclusion": "공공보건/외래재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주 (공보의)",
        "careType": "외래물리치료/보건사업",
        "conditions": "만성 관절염, 요통, 농업인 근골격계 통증, 외래 물리치료",
        "specialty": "보건의료원 공공 물리치료 / 장애인 재활 사업",
        "recovery": "비지정",
        "workersComp": "미지정",
        "autoInsurance": "불가",
        "dayRehab": "미운영",
        "address": "충청남도 청양군 청양읍 칠갑산로 222",
        "phone": "041-940-4500",
        "sources": "https://www.cheongyang.go.kr/med.do",
        "verification": "공식 확인",
        "notes": "청양군 내 거점 공공 의료기관. 저렴한 비용으로 외래 물리치료실 이용 가능하며, 지역사회 재활협력 사업 진행."
    },
    {
        "id": "29",
        "district": "태안군",
        "name": "태안군보건의료원",
        "type": "의원",
        "inclusion": "공공보건/외래재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주 (공보의)",
        "careType": "외래물리치료/방문재활",
        "conditions": "퇴행성 근골격 통증, 중풍 후유증, 외래 물리치료",
        "specialty": "태안 유일 보건의료원 / 찾아가는 물리치료",
        "recovery": "비지정",
        "workersComp": "미지정",
        "autoInsurance": "불가",
        "dayRehab": "미운영",
        "address": "충청남도 태안군 태안읍 평천길 110",
        "phone": "041-671-5200",
        "sources": "https://www.taean.go.kr/html/med/",
        "verification": "공식 확인",
        "notes": "태안 지역의 유일한 공공 거점 의료원. 종합적인 외래 물리치료장비를 갖추고 있어 군민 대상의 밀착 재활 제공."
    },
    {
        "id": "30",
        "district": "서천군",
        "name": "장항한의원 (한방재활)",
        "type": "한의원",
        "inclusion": "한방재활/추나",
        "rehabDept": "있음",
        "specialists": "한방 전문의",
        "careType": "외래재활/침구치료",
        "conditions": "교통사고 후유증, 디스크 통증, 오십견, 마비 재활",
        "specialty": "한방 추나 요법 및 약침 치료 특화",
        "recovery": "비지정",
        "workersComp": "미지정",
        "autoInsurance": "가능",
        "dayRehab": "미운영",
        "address": "충청남도 서천군 장항읍 장서로 78",
        "phone": "041-956-7512",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "장항읍내 위치. 한방 침구 및 물리치료를 병행하며, 비수술 척추 관절 교정 추나 요법을 직접 시술."
    }
];
