window.REHAB_DATA = [
    {
        "id": "1",
        "district": "경산시",
        "name": "경북권역재활병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 소아재활, 근골격계 재활",
        "specialty": "보건복지부 회복기 지정 / 산재 재활인증",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "경상북도 경산시 미래로 120 (평산동)",
        "phone": "053-230-8800",
        "sources": "http://grrh.or.kr/",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "경북 유일의 권역재활병원. 보건복지부 지정 제3기 회복기 재활의료기관 (2026.03 ~ 2029.02). 간호간병통합서비스 제공."
    },
    {
        "id": "2",
        "district": "구미시",
        "name": "갑을구미재활병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 근골격계 재활",
        "specialty": "보건복지부 회복기 지정 / 산재 재활인증",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "경상북도 구미시 3공단1로 280-3 (임수동)",
        "phone": "054-710-6000",
        "sources": "http://kabul.co.kr/",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관 (2026.03 ~ 2029.02). 근로복지공단 산재 재활인증기관."
    },
    {
        "id": "3",
        "district": "구미시",
        "name": "구미으뜸병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 수술 후 집중재활",
        "specialty": "보건복지부 회복기 지정 / 산재 지정",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 구미시 금오산로 198-20 (남통동)",
        "phone": "054-452-9000",
        "sources": "https://www.hira.or.kr",
        "verification": "보건복지부/HIRA 확인",
        "notes": "의료법인 승미의료재단 구미으뜸재활병원. 보건복지부 지정 제3기 회복기 재활의료기관."
    },
    {
        "id": "4",
        "district": "영주시",
        "name": "더명품재활병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 근골격계 재활",
        "specialty": "보건복지부 회복기 지정 / 산재 지정",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 영주시 반지미로 265 (가흥동)",
        "phone": "054-633-3300",
        "sources": "http://myeongpum.co.kr/",
        "verification": "보건복지부/HIRA 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관. 경북 북부 지역 거점 재활병원."
    },
    {
        "id": "5",
        "district": "안동시",
        "name": "복주회복병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 노인성 질환 재활",
        "specialty": "보건복지부 회복기 지정 / 존엄케어 특화",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 안동시 풍산읍 함백이길 154",
        "phone": "054-851-1071",
        "sources": "https://www.hira.or.kr",
        "verification": "보건복지부/HIRA 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관. 신체억제 없는 존엄케어 지향."
    },
    {
        "id": "6",
        "district": "구미시",
        "name": "근로복지공단 구미의원",
        "type": "의원",
        "inclusion": "공단 직영 외래재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "산재장해인 재활, 직업복귀 프로그램, 외래 물리치료",
        "specialty": "근로복지공단 직영 / 외래전문",
        "recovery": "해당없음",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "경상북도 구미시 인동가산로 14, 6층 (진평동)",
        "phone": "054-717-6000",
        "sources": "https://www.comwel.or.kr/",
        "verification": "근로복지공단 공식 확인",
        "notes": "2025년 4월 개원한 공단 직영 외래 재활 특화 기관. 1:1 개인별 맞춤 치료 및 직업 복귀 평가."
    },
    {
        "id": "7",
        "district": "포항시",
        "name": "에스포항병원",
        "type": "종합병원",
        "inclusion": "재활의학과 보유 종합병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "급성기/입원재활/외래재활",
        "conditions": "뇌혈관 질환 수술 후 재활, 척추 수술 후 재활",
        "specialty": "뇌혈관 전문병원 / 산재 재활인증",
        "recovery": "해당없음",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 포항시 남구 희망대로 352 (이동)",
        "phone": "054-289-9000",
        "sources": "http://www.pssh.kr/",
        "verification": "HIRA/공단 확인",
        "notes": "보건복지부 지정 뇌혈관 전문병원. 급성기 뇌졸중 치료 후 조기 재활 연계 강점."
    },
    {
        "id": "8",
        "district": "포항시",
        "name": "세명재활의학병원",
        "type": "병원",
        "inclusion": "재활의학과 전문병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "뇌졸중, 척수손상, 근골격계 마비 재활",
        "specialty": "재활의학과 전문병원 / 산재 지정",
        "recovery": "해당없음",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 포항시 남구 상공로 60 (상도동)",
        "phone": "054-283-0815",
        "sources": "http://smrm.co.kr/",
        "verification": "HIRA/공단 확인",
        "notes": "포항 내 대표적인 재활 특화 병원. 산재보험 재활인증기관."
    },
    {
        "id": "9",
        "district": "포항시",
        "name": "좋은선린요양병원",
        "type": "요양병원",
        "inclusion": "재활의학과 보유 요양병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌졸중, 척수손상, 소아재활, 수중치료",
        "specialty": "요양병원 재활 특화 / 소아재활",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 포항시 북구 대신로 27 (대신동)",
        "phone": "054-245-6200",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "지역 최대 규모의 재활 인프라. 소아재활치료실 및 수중재활치료풀 보유."
    },
    {
        "id": "10",
        "district": "포항시",
        "name": "포항세명기독병원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래/입원재활",
        "conditions": "급성기 뇌졸중, 근골격계 질환 재활",
        "specialty": "종합병원 재활의학과",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 포항시 남구 포스코대로 351 (대도동)",
        "phone": "054-274-0961",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "포항 지역 대표 종합병원. 재활의학과 진료 및 입원 연계."
    },
    {
        "id": "11",
        "district": "포항시",
        "name": "포항성모병원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래/입원재활",
        "conditions": "급성기 뇌졸중, 척수손상, 근골격계 수술 후 재활",
        "specialty": "종합병원 재활의학과",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 포항시 남구 대잠동길 17 (대잠동)",
        "phone": "054-272-0012",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "종합병원 재활의학과 운영. 급성기 이후 포괄적 재활 치료 제공."
    },
    {
        "id": "12",
        "district": "포항시",
        "name": "포항의료원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래/입원재활",
        "conditions": "뇌졸중, 만성기 통증, 노인성 재활",
        "specialty": "지역 공공의료원 / 재활의학과",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 포항시 북구 용흥로 36 (용흥동)",
        "phone": "054-247-0551",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "경상북도립 포항의료원. 지역 공공보건의료 거점 병원으로 재활의학과 진료."
    },
    {
        "id": "13",
        "district": "포항시",
        "name": "경희요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌졸중, 파킨슨병, 수술 후 재활",
        "specialty": "요양병원 재활",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 포항시 남구 송도로 62 (송도동)",
        "phone": "054-250-2500",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "1:1 맞춤 재활치료 중심 요양병원. 운동치료 및 작업치료 제공."
    },
    {
        "id": "14",
        "district": "포항시",
        "name": "고려대련요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활 특화",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "요양재활/입원재활",
        "conditions": "양한방 협진 재활, 암케어, 투석재활",
        "specialty": "양한방 협진 / 투석가능",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 포항시 북구 흥해읍 대련리",
        "phone": "054-262-6000",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "양·한방 협진 시스템을 통한 재활 및 만성기 환자 케어."
    },
    {
        "id": "15",
        "district": "경주시",
        "name": "동국대학교경주병원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래/입원재활",
        "conditions": "뇌졸중, 척수손상, 근골격계 재활",
        "specialty": "대학병원 재활의학과",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 경주시 동대로 87 (석장동)",
        "phone": "054-770-8000",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "경주 유일의 대학병원 재활의학과. 다학제 협진 및 포괄적 재활 치료 강점."
    },
    {
        "id": "16",
        "district": "경주시",
        "name": "정흥채재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "근골격계 통증 재활, 도수치료, 물리치료",
        "specialty": "통증재활 의원",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "경상북도 경주시 금성로 316 (서부동)",
        "phone": "054-777-7277",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "경주 시내 중심가에 위치한 외래 물리치료 및 도수치료 위주의 재활의학과 의원."
    },
    {
        "id": "17",
        "district": "경주시",
        "name": "늘푸른요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌졸중 후유증, 파킨슨병, 노인성 마비 재활",
        "specialty": "요양병원 재활",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 경주시 유림로13번길 155 (용강동)",
        "phone": "054-749-0002",
        "sources": "http://gyeongjunulpurn.com/",
        "verification": "HIRA/공식 확인",
        "notes": "용강동에 위치한 재활 특화 요양병원. 체계적인 물리치료 및 작업치료 프로그램 운영."
    },
    {
        "id": "18",
        "district": "경주시",
        "name": "경주시립노인전문요양병원",
        "type": "요양병원",
        "inclusion": "공립 노인요양병원 재활",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "요양재활/입원재활",
        "conditions": "치매, 뇌졸중 후유증, 노인성 만성질환 케어",
        "specialty": "공립노인병원 / 치매안심병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "경상북도 경주시 현곡면 충현로 610-120",
        "phone": "054-743-6200",
        "sources": "http://www.kjho.co.kr/",
        "verification": "공식 확인",
        "notes": "경주시립 공공 노인 요양병원. 치매 케어 및 만성기 장기 요양재활 중심."
    },
    {
        "id": "19",
        "district": "김천시",
        "name": "김천제일병원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래/입원재활",
        "conditions": "뇌졸중, 척수손상, 급성기 재활",
        "specialty": "종합병원 재활의학과",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 김천시 신음1길 12 (신음동)",
        "phone": "054-420-9300",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "김천 최대 민간 종합병원. 재활의학과 전문의 진료 및 물리치료실 연동."
    },
    {
        "id": "20",
        "district": "김천시",
        "name": "김천의료원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래/입원재활",
        "conditions": "뇌졸중, 마비재활, 공공의료 연계 재활",
        "specialty": "지역 공공의료원 / 재활의학과",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 김천시 모암길 24 (모암동)",
        "phone": "054-429-8114",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "경상북도립 김천의료원. 취약계층 공공재활 및 표준 재활 서비스 제공."
    },
    {
        "id": "21",
        "district": "영천시",
        "name": "영남대학교의과대학부속영천병원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래/입원재활",
        "conditions": "급성기 이후 뇌손상, 척수마비, 물리치료",
        "specialty": "종합병원 재활의학과",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 영천시 오수1길 10 (오수동)",
        "phone": "054-338-9000",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "영천영대병원. 영천 지역 거점 종합병원으로 재활의학과 진료과 활성화."
    },
    {
        "id": "22",
        "district": "상주시",
        "name": "상주적십자병원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래/입원재활",
        "conditions": "만성 근골격계 질환, 마비재활, 통증치료",
        "specialty": "지역 공공병원 / 적십자병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 상주시 상서문로 53 (남성동)",
        "phone": "054-534-3501",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "지역 공공거점 적십자병원. 재활의학과 및 진료 인프라 운영."
    },
    {
        "id": "23",
        "district": "상주시",
        "name": "상주성모병원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "외래/입원재활",
        "conditions": "뇌졸중 후유증, 수술 후 회복, 통증 물리치료",
        "specialty": "종합병원 재활의학과",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 상주시 냉림서성길 7 (냉림동)",
        "phone": "054-532-5001",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "상주성모병원 종합병원 재활의학과 진료 개별 확인 필요."
    },
    {
        "id": "24",
        "district": "문경시",
        "name": "문경중앙병원",
        "type": "병원",
        "inclusion": "재활의학과 보유 병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래/입원재활",
        "conditions": "근골격계 물리치료, 노인성 재활",
        "specialty": "지역 일반병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 문경시 중앙로 117-18 (모전동)",
        "phone": "054-555-2011",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "문경 지역 거점 병원. 물리치료실 및 재활의학과 진료 연동."
    },
    {
        "id": "25",
        "district": "청도군",
        "name": "청도대남병원",
        "type": "병원",
        "inclusion": "재활의학과 보유 병원",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "외래/입원재활",
        "conditions": "노인성 질환, 통증 물리치료",
        "specialty": "지역 일반병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "경상북도 청도군 화양읍 청화로 79-7",
        "phone": "054-373-0606",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "청도군 중심 병원. 물리치료 위주 외래 진료 가능 여부 사전 확인 권장."
    },
    {
        "id": "26",
        "district": "칠곡군",
        "name": "왜관병원",
        "type": "병원",
        "inclusion": "재활의학과 보유 병원",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "외래/입원재활",
        "conditions": "마비성 통증, 수술 후 회복 물리치료",
        "specialty": "지역 일반병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 칠곡군 왜관읍 군청2길 10",
        "phone": "054-971-1002",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "왜관읍 소재 병원. 물리치료 및 도수치료 외래 가능."
    },
    {
        "id": "27",
        "district": "칠곡군",
        "name": "칠곡혜원요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "노인성 질환, 뇌졸중 후유증, 물리/작업치료",
        "specialty": "요양병원 재활",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 칠곡군 약목면 관호7길 41",
        "phone": "054-979-7223",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "칠곡 약목면에 위치한 요양병원. 고령 및 만성 뇌졸중 환자 물리치료 전문."
    },
    {
        "id": "28",
        "district": "고령군",
        "name": "고령영생요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "요양재활/입원재활",
        "conditions": "치매, 뇌졸중 후유 마비, 노인 요양재활",
        "specialty": "요양병원 재활",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "경상북도 고령군 대가야읍 중앙로 33",
        "phone": "054-955-2661",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "대가야읍에 위치한 노인전문 요양재활 시설."
    },
    {
        "id": "29",
        "district": "울진군",
        "name": "울진군의료원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래/입원재활",
        "conditions": "뇌졸중, 척수손상, 근골격계 외래 물리치료",
        "specialty": "지역 공공의료원 / 재활의학과",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 울진군 울진읍 현내항길 71",
        "phone": "054-785-7000",
        "sources": "http://www.ujmc.or.kr/",
        "verification": "공식 홈페이지 확인",
        "notes": "울진 및 경북 동해안 북부 지역 공공의료 거점. 재활의학과 외래 및 입원 물리치료."
    },
    {
        "id": "30",
        "district": "울진군",
        "name": "울진군립요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 노인재활",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "요양재활/입원재활",
        "conditions": "노인성 치매, 뇌졸중 후기 마비 케어",
        "specialty": "군립 노인요양병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "경상북도 울진군 울진읍 현내항길 71 (의료원과 인접)",
        "phone": "054-785-7000",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "울진군립 공공 요양병원. 만성기 및 노인성 질환의 장기 요양재활 전문."
    },
    {
        "id": "31",
        "district": "영덕군",
        "name": "영덕아산병원",
        "type": "종합병원",
        "inclusion": "종합병원 물리치료실",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "외래/입원재활",
        "conditions": "급성기 수술 후 회복, 물리치료",
        "specialty": "아산재단 지역병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 영덕군 영해면 영덕로 1621",
        "phone": "054-730-0114",
        "sources": "http://www.ydasan.co.kr/",
        "verification": "공식 홈페이지 확인",
        "notes": "영덕 지역 아산재단 종합병원. 외래 물리치료실 운영 확인 필요."
    },
    {
        "id": "32",
        "district": "의성군",
        "name": "의성공립노인전문요양병원",
        "type": "요양병원",
        "inclusion": "공립요양병원 재활",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "요양재활/입원재활",
        "conditions": "치매, 뇌졸중 후유증, 노인성 마비 케어",
        "specialty": "공립노인병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "경상북도 의성군 의성읍 안평의성로 1122-30",
        "phone": "054-834-7400",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "의성군 공립 노인요양병원. 물리치료를 동반한 요양관리 지원."
    },
    {
        "id": "33",
        "district": "성주군",
        "name": "성주효요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "요양재활/입원재활",
        "conditions": "뇌경색/뇌출혈 후유증 요양, 노인성 만성통증",
        "specialty": "요양병원 재활",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "경상북도 성주군 성주읍 성주순환로 239",
        "phone": "054-933-5111",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "성주읍 외곽에 위치하여 쾌적한 환경에서 만성 요양재활 수행."
    },
    {
        "id": "34",
        "district": "예천군",
        "name": "예천권병원",
        "type": "병원",
        "inclusion": "재활의학과 보유 병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래/입원재활",
        "conditions": "척추/관절 수술 후 물리치료, 통증 치료",
        "specialty": "지역 일반병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경상북도 예천군 예천읍 시장로 136",
        "phone": "054-654-6611",
        "sources": "http://yckh.co.kr/",
        "verification": "공식 홈페이지 확인",
        "notes": "예천 최대 로컬병원. 정형/재활 및 물리치료실 활성화."
    },
    {
        "id": "35",
        "district": "봉화군",
        "name": "봉화해성병원",
        "type": "병원",
        "inclusion": "재활의학과 보유 병원",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "외래/입원재활",
        "conditions": "근골격계 물리치료, 노인성 통증 완화",
        "specialty": "지역 일반병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "경상북도 봉화군 봉화읍 보밑길 3",
        "phone": "054-679-1331",
        "sources": "http://gbwp.or.kr/",
        "verification": "공식 홈페이지 확인",
        "notes": "봉화 지역 유일의 준종합급 로컬 병원. 노인 통증 물리치료실 지원."
    },
    {
        "id": "36",
        "district": "청송군",
        "name": "청송군보건의료원",
        "type": "종합병원",
        "inclusion": "공공보건의료원 물리치료실",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "외래재활",
        "conditions": "경증 통증 물리치료, 지역 복귀 공공치료",
        "specialty": "공공의료원 / 보건기관",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "경상북도 청송군 청송읍 의료원길 19",
        "phone": "054-870-7112",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "보건소와 병원 기능이 통합된 청송군 보건의료원. 지역 주민 대상 기본 물리치료 지원."
    },
    {
        "id": "37",
        "district": "영양군",
        "name": "영양군보건의료원",
        "type": "종합병원",
        "inclusion": "공공보건의료원 물리치료실",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "외래재활",
        "conditions": "경증 노인성 관절염, 물리치료",
        "specialty": "공공의료원 / 보건기관",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "경상북도 영양군 영양읍 동서대로 82",
        "phone": "054-680-5151",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "의료 시설이 부족한 영양군의 보건의료원으로, 기초적인 물리치료실 기능 수행."
    },
    {
        "id": "38",
        "district": "울릉군",
        "name": "울릉군보건의료원",
        "type": "종합병원",
        "inclusion": "공공보건의료원 물리치료실",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "외래재활",
        "conditions": "도서지역 주민 물리치료, 기본 재활",
        "specialty": "공공의료원 / 보건기관",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "경상북도 울릉군 울릉읍 울릉순환로 396-18",
        "phone": "054-790-6871",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "울릉도 내 유일의 입원/외래가 가능한 공공의료기관. 기본 관절/근골격계 물리치료실 제공."
    },
    {
        "id": "39",
        "district": "경산시",
        "name": "경산시립요양병원",
        "type": "요양병원",
        "inclusion": "공립 노인요양병원 재활",
        "rehabDept": "있음",
        "specialists": "확인필요",
        "careType": "요양재활/입원재활",
        "conditions": "치매, 뇌졸중 후유 만성마비, 노인성 재활",
        "specialty": "공립노인병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "경상북도 경산시 남천면 협석1길 34",
        "phone": "053-812-7582",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "경산시립노인전문요양병원. 치매 케어 및 만성기 노인성 질환 요양재활 위주."
    },
    {
        "id": "40",
        "district": "구미시",
        "name": "구미시립요양병원",
        "type": "요양병원",
        "inclusion": "공립 노인요양병원 재활",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "요양재활/입원재활",
        "conditions": "뇌경색 후유증 요양, 노인성 만성마비 재활",
        "specialty": "공립노인병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "경상북도 구미시 무을면 삼목길 35-18",
        "phone": "054-440-1000",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "구미시립노인전문요양병원. 쾌적한 자연환경 속 노인성 마비 및 장기 요양재활 중심."
    }
];
