window.REHAB_DATA = [
    {
        "id": "1",
        "district": "완산구",
        "name": "드림솔병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 수술 후 집중재활, 소아재활, 연하 장애",
        "specialty": "보건복지부 지정 회복기 재활의료기관 / 스포츠 재활",
        "recovery": "지정(제3기)",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "전북특별자치도 전주시 완산구 홍산남로 10 (효자동3가)",
        "phone": "063-220-7000",
        "sources": "http://www.jjsol-hospital.co.kr/",
        "verification": "보건복지부/HIRA 확인",
        "notes": "전북특별자치도 내 유일의 보건복지부 지정 제3기 회복기 재활의료기관 (2026.03 ~ 2029.02). 중추신경계 마비 환자 대상 일대일 집중 물리/작업치료 및 간호간병통합서비스 병동 운영."
    },
    {
        "id": "2",
        "district": "완산구",
        "name": "예수병원",
        "type": "종합병원",
        "inclusion": "산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "뇌혈관 질환 마비, 척수손상, 근골격계 손상 재활, 산재 집중 재활",
        "specialty": "근로복지공단 산재 재활인증 / 대형 종합병원 재활센터",
        "recovery": "해당없음",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "전북특별자치도 전주시 완산구 서원로 365 (중화산동1가)",
        "phone": "063-230-8114",
        "sources": "https://www.jesushospital.com/",
        "verification": "근로복지공단 공식 확인",
        "notes": "전북 서남권 거점 공익 종합병원으로, 근로복지공단으로부터 산재보험 재활전문기관 인증을 획득함. 최첨단 재활 로봇 및 다학제 협진 치료 환경을 갖춤."
    },
    {
        "id": "3",
        "district": "완산구",
        "name": "전주병원",
        "type": "종합병원",
        "inclusion": "산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "중추신경계 마비, 수술 후 관절 마비, 통증 재활",
        "specialty": "의료법인 영경의료재단 / 산재 재활인증",
        "recovery": "해당없음",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "전북특별자치도 전주시 완산구 신촌4길 6 (중화산동2가)",
        "phone": "063-220-7200",
        "sources": "http://www.jeonjuhospital.co.kr/",
        "verification": "근로복지공단 공식 확인",
        "notes": "근로복지공단 산재 재활인증 의료기관. 정형외과 및 신경외과 수술 직후 맞춤형 재활 운동 치료 및 물리치료 클리닉 활성화."
    },
    {
        "id": "4",
        "district": "완산구",
        "name": "삼남재활의학과병원",
        "type": "병원",
        "inclusion": "재활 전문 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "뇌졸중(중풍) 후유장애, 척수 손상, 파킨슨병, 뇌성마비, 스포츠 외상",
        "specialty": "입원 재활실 가동 / 중추신경계 치료",
        "recovery": "해당없음",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "전북특별자치도 전주시 완산구 화산천변로 11 (중화산동2가)",
        "phone": "063-228-3000",
        "sources": "http://www.samnamrehab.co.kr/",
        "verification": "공식 홈페이지/심평원 확인",
        "notes": "전주 완산구 중화산동의 오랜 전통을 가진 입원형 재활전문병원. 뇌신경계 전문 재활치료팀을 통한 운동/작업/언어/인지/연하 치료 집중 실시."
    },
    {
        "id": "5",
        "district": "완산구",
        "name": "전주 온고을재활병원",
        "type": "병원",
        "inclusion": "재활 전문 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "뇌경색, 뇌출혈 마비, 척추 디스크 수술 후 회복, 물리치료",
        "specialty": "중추신경계 재활센터 / 연하 및 보행치료",
        "recovery": "해당없음",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "전북특별자치도 전주시 완산구 전주천서로 149 (서완산동2가)",
        "phone": "063-221-7500",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA/심평원 확인",
        "notes": "서완산동에 위치하여 천변 조망의 조용한 입지. 운동치료실, 작업치료실, 보행 분석실을 바탕으로 환자의 신속한 가정 복귀를 도움."
    },
    {
        "id": "6",
        "district": "덕진구",
        "name": "전주고려병원",
        "type": "병원",
        "inclusion": "수술 후 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "관절 및 척추 수술 후 가동 장애, 골절 회복, 물리치료",
        "specialty": "정형·신경외과 수술후 재활 특화 / 통증 관리",
        "recovery": "해당없음",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "전북특별자치도 전주시 덕진구 안덕원로 367 (우아동3가)",
        "phone": "063-240-5000",
        "sources": "http://www.koryohospital.co.kr/",
        "verification": "공식 정보 확인",
        "notes": "우아동에 위치한 종합병원급 인프라의 병원. 수술을 집도한 정형/신경외과와 재활의학과 전문의 간 긴밀한 협진 프로세스로 신속 재활 가능."
    },
    {
        "id": "7",
        "district": "익산시",
        "name": "익산병원",
        "type": "종합병원",
        "inclusion": "종합병원 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "급성기 후 중추신경 마비, 근골격계 통증 조절, 도수치료",
        "specialty": "익산 동부 거점 종합병원 재활센터",
        "recovery": "해당없음",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "전북특별자치도 익산시 무왕로 975 (신동)",
        "phone": "063-840-9114",
        "sources": "http://www.iksan-hosp.co.kr/",
        "verification": "공식 정보 확인",
        "notes": "익산시 신동 소재 거점 종합병원. 재활의학과 전문의 진료 및 물리/작업 치료실 완비로 지역 내 신뢰도가 높음."
    },
    {
        "id": "8",
        "district": "군산시",
        "name": "누가병원",
        "type": "병원",
        "inclusion": "재활치료센터 운영",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "뇌졸중 마비 재활, 연하 장애 치료, 작업치료, 디스크 물리치료",
        "specialty": "군산 지곡동 거점 / 대규모 재활치료센터",
        "recovery": "해당없음",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "전북특별자치도 군산시 대학로 316 (지곡동)",
        "phone": "063-469-8000",
        "sources": "http://www.nuga.or.kr/",
        "verification": "공식 정보 확인",
        "notes": "군산 지곡동 중심가 위치. 쾌적하고 체계적인 대규모 재활치료센터와 낮병동식 외래 재활을 적극적으로 지원함."
    },
    {
        "id": "9",
        "district": "군산시",
        "name": "모세병원",
        "type": "병원",
        "inclusion": "노인성 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "노인성 마비, 척추·관절 보존적 물리치료, 노인 기능 훈련",
        "specialty": "재활의학과 전문 진료 / 노인 기능 유지",
        "recovery": "해당없음",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "전북특별자치도 군산시 조촌로 134 (조촌동)",
        "phone": "063-440-8000",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "군산 시청 인근 조촌동에 위치. 고령 환자들의 활동 보조 및 일상 관절 보존을 돕는 물리재활치료센터 활성화."
    },
    {
        "id": "10",
        "district": "군산시",
        "name": "군산성신병원",
        "type": "병원",
        "inclusion": "수술 후 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "인공관절 치환술 후 재활, 골절 회복 운동치료, 온열 통증 관리",
        "specialty": "척추·관절 수술 후 운동 기능 복원",
        "recovery": "해당없음",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "전북특별자치도 군산시 삼학길 40 (삼학동)",
        "phone": "063-440-2000",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "삼학동 소재 관절 척추 특화 병원. 수술 직후 안전하고 빠른 일상생활 복귀를 돕는 정밀 재활 물리치료 적용."
    },
    {
        "id": "11",
        "district": "군산시",
        "name": "정다운병원",
        "type": "병원",
        "inclusion": "외상/협진 재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "근골격계 통증 조절, 도수치료, 정형 물리재활",
        "specialty": "소룡동 공단지구 거점 외상 및 재활 협진",
        "recovery": "해당없음",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "전북특별자치도 군산시 공단대로 622 (소룡동)",
        "phone": "063-460-7000",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "군산 외곽 소룡동 공단지구 인근 근로자 및 지역 주민의 통증/외상 재활과 비수술 도수치료 제공."
    },
    {
        "id": "12",
        "district": "군산시",
        "name": "동군산병원",
        "type": "종합병원",
        "inclusion": "종합병원 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/입원재활",
        "conditions": "중추신경 손상, 척수 손상, 외상성 통증 조절, 정밀 진단",
        "specialty": "동군산 최대 종합병원 재활의학과",
        "recovery": "해당없음",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "전북특별자치도 군산시 조촌로 115 (조촌동)",
        "phone": "063-400-7000",
        "sources": "http://www.donggunsan.co.kr/",
        "verification": "공식 정보 확인",
        "notes": "조촌동의 대표적 대형 종합의료기관. 정밀 영상장비를 바탕으로 협진하에 정확하고 체계적인 만성 정형/신경계 기능 치료 수행."
    },
    {
        "id": "13",
        "district": "덕진구",
        "name": "전주나은요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 적정성 1등급",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌경색 만성 마비, 인지저하(치매) 인지치료, 온열물리치료",
        "specialty": "심평원 적정성평가 1등급 / 쾌적한 전원 환경",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "전북특별자치도 전주시 덕진구 기린대로 1025 (여의동2가)",
        "phone": "063-211-1000",
        "sources": "http://www.naeunhospital.co.kr/",
        "verification": "HIRA/심평원 적정성평가 1등급 확인",
        "notes": "전주 여의동에 넓게 자리잡은 친환경 요양병원. 건강보험심사평가원 요양병원 적정성 평가 1등급 획득 및 체계적인 기능 보존 물리재활 운영."
    },
    {
        "id": "14",
        "district": "완산구",
        "name": "효자요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 적정성 1등급",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌졸중 마비 집중 치료, 보행 훈련, 연하 장애 치료, 작업치료",
        "specialty": "심평원 적정성평가 1등급 / 대규모 전문 재활치료실",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "전북특별자치도 전주시 완산구 우전로 99 (효자동2가)",
        "phone": "063-228-0900",
        "sources": "http://www.hyojahospital.com/",
        "verification": "HIRA/심평원 적정성평가 1등급 확인",
        "notes": "효자동 중심부에 위치한 고품격 요양병원. 재활의학과 전문의 지도 하에 대규모 전문재활치료실(CNS 치료, 보행훈련, 연하훈련) 운영으로 만족도가 높음."
    },
    {
        "id": "15",
        "district": "익산시",
        "name": "수재활요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "중추신경계 마비 집중 운동, 연하 재활, 도수치료, 작업치료",
        "specialty": "익산 어양동 / 재활 특화형 대규모 요양치료실",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "전북특별자치도 익산시 선화로 386 (어양동)",
        "phone": "063-837-9900",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "익산 어양동 소재 재활 특화 요양병원. 넓은 운동 치료 공간에서 물리치료사의 1대1 매칭을 통한 집중 기능 회복 훈련 제공."
    },
    {
        "id": "16",
        "district": "익산시",
        "name": "익산미소요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 노인재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "파킨슨병 운동 관리, 치매 행동 제한 조절, 물리보조치료",
        "specialty": "인화동 노인성 질환 요양재활 / 정밀 간병",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "전북특별자치도 익산시 평동로 729 (인화동2가)",
        "phone": "063-855-1000",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "익산 인화동 병원 밀집지 위치. 노인성 뇌신경계 질환 환자 맞춤형 동작 유지 관리 및 통증 경감 온열 치료 제공."
    },
    {
        "id": "17",
        "district": "완산구",
        "name": "전주시립요양병원",
        "type": "요양병원",
        "inclusion": "시립/적정성 1등급",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "치매 정서적 안정 치료, 뇌졸중 만성 마비 보조 훈련, 양한방 협진",
        "specialty": "전주시립 공공의료 / 심평원 적정성 1등급",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "전북특별자치도 전주시 완산구 안행5길 26 (삼천동3가)",
        "phone": "063-281-7100",
        "sources": "http://www.jjmc.or.kr/",
        "verification": "HIRA/심평원 적정성평가 1등급 확인",
        "notes": "전주시가 설립한 공공 요양의료기관. 심평원 요양병원 평가 1등급 획득. 치매안심병원 및 표준형 노인 재활 프로그램 운영."
    },
    {
        "id": "18",
        "district": "완산구",
        "name": "연수요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 인증",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "치매 돌봄, 만성 뇌혈관 후유증 마비, 한방 침구 및 물리치료",
        "specialty": "보건복지부 인증 / 양한방 협진 보존재활",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "전북특별자치도 전주시 완산구 용머리로 180 (효자동1가)",
        "phone": "063-220-7575",
        "sources": "http://www.yshospital.com/",
        "verification": "보건복지부 의료기관 평가인증 확인",
        "notes": "보건복지부 인증을 통과한 안심 요양병원. 양방 재활의학과 전문의와 한의사 협진을 바탕으로 종합적인 보존적 관절 케어 제공."
    },
    {
        "id": "19",
        "district": "덕진구",
        "name": "아중요양병원",
        "type": "요양병원",
        "inclusion": "재활/혈액투석 병행",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활/투석재활",
        "conditions": "뇌졸중 마비, 만성 신부전 혈액투석 병행 재활, 보행 유지",
        "specialty": "인공신장실(투석) 운영 / 투석환자 맞춤 재활",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "전북특별자치도 전주시 덕진구 아중로 235 (인후동1가)",
        "phone": "063-247-5200",
        "sources": "http://www.ajunghosp.co.kr/",
        "verification": "HIRA 확인",
        "notes": "전주 아중지구 위치. 인공신장실(투석)을 완비하여 정기 투석이 필요한 고령 뇌졸중 환자의 체력 및 보행 능력 유지 재활에 특화."
    },
    {
        "id": "20",
        "district": "완산구",
        "name": "나눔요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 노인재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "욕창 집중 치료, 만성 노인 질환 물리치료, 일상동작 훈련",
        "specialty": "장기 요양 케어 및 욕창 케어 / 관절 보존",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "전북특별자치도 전주시 완산구 서원로 298 (중화산동2가)",
        "phone": "063-236-0114",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "중화산동 소재 요양병원. 장기 입원 중인 고령 환자들의 신체 강직 방지를 위한 일상적인 소극적 관절 가동 운동 및 물리치료 클리닉 운영."
    },
    {
        "id": "21",
        "district": "덕진구",
        "name": "길재활의학과의원",
        "type": "의원",
        "inclusion": "비수술 통증 전문",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "목·허리 디스크, 어깨 오십견, 관절염 도수치료, 프롤로 테라피",
        "specialty": "인후동 통증/비수술 재활 / 야간진료 운영",
        "recovery": "해당없음",
        "workersComp": "가능",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "전북특별자치도 전주시 덕진구 무삼지로 34 (인후동1가)",
        "phone": "063-247-7585",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "덕진구 인후동 위치. 재활의학과 전문의 진료 하에 외래 중심 1대1 도수치료, 통증 맞춤 프롤로 주사 치료 및 직장인을 위한 야간 진료 제공."
    },
    {
        "id": "22",
        "district": "완산구",
        "name": "탑신경외과재활의학과의원",
        "type": "의원",
        "inclusion": "비수술 통증 전문",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "척추 교정, 체외충격파 치료, 관절 통증 물리치료, 도수치료",
        "specialty": "효자동 백제대로 소재 / 비수술 관절 및 도수재활",
        "recovery": "해당없음",
        "workersComp": "가능",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "전북특별자치도 전주시 완산구 백제대로 264 (효자동1가)",
        "phone": "063-227-0119",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "효자동 백제대로 변에 위치하여 접근성이 용이함. 신경외과 및 재활의학과 협진 시스템으로 정밀한 외래 물리치료 및 도수교정 진행."
    },
    {
        "id": "23",
        "district": "덕진구",
        "name": "덕진재활의학과의원",
        "type": "의원",
        "inclusion": "비수술 통증 전문",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "어깨 및 무릎 만성 통증, 디스크 신경 차단술, 온열 물리치료",
        "specialty": "덕진동 거점 / 1:1 환자 맞춤형 통증 클리닉",
        "recovery": "해당없음",
        "workersComp": "가능",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "전북특별자치도 전주시 덕진구 기린대로 445 (덕진동1가)",
        "phone": "063-255-0365",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "덕진동 기린대로 인근 위치. 오랜 임상 경험을 가진 재활의학과 전문의가 상주하여 비수술적 통증 완화 물리치료실 집중 관리."
    },
    {
        "id": "24",
        "district": "정읍시",
        "name": "정읍시립요양병원",
        "type": "요양병원",
        "inclusion": "시립/적정성 1등급",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌졸중 만성기 재활, 치매 돌봄 프로그램, 한방 침술 협진, 물리치료",
        "specialty": "정읍시립 공공요양병원 / 심평원 적정성 1등급",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "전북특별자치도 정읍시 구룡길 55 (구룡동)",
        "phone": "063-538-8575",
        "sources": "http://www.jcgh.kr/",
        "verification": "HIRA/심평원 적정성평가 1등급 확인",
        "notes": "정읍시가 건립한 공익 요양병원. 심평원 적정성 평가 1등급 요양병원. 치매안심센터와 연계하여 고령 환자 기능 유지 중심의 온화한 재활 치료 제공."
    },
    {
        "id": "25",
        "district": "정읍시",
        "name": "정읍아산병원",
        "type": "종합병원",
        "inclusion": "종합병원 재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "급성기 후 신체 마비 치료, 뇌혈관 후유증 작업 치료, 정형 외상 회복",
        "specialty": "아산사회복지재단 / 서남권 거점 종합병원 재활",
        "recovery": "해당없음",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "전북특별자치도 정읍시 충정로 606-22 (연지동)",
        "phone": "063-530-6114",
        "sources": "https://www.asanfoundation.or.kr/sunghwa/jeongeup/",
        "verification": "공식 정보 확인",
        "notes": "아산재단 산하 정읍 최고의 거점 종합병원. 뇌졸중 초기 및 정형외과 수술 환자를 위한 완성도 높은 전문 재활치료 시설 및 전용 치료센터 구축."
    },
    {
        "id": "26",
        "district": "남원시",
        "name": "남원의료원",
        "type": "종합병원",
        "inclusion": "지방의료원 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "중추신경계 마비 집중 운동, 연하치료, 언어치료, 디스크 물리치료",
        "specialty": "전북특별자치도 도립 거점 남원 지방의료원",
        "recovery": "해당없음",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "전북특별자치도 남원시 충정로 365 (동충동)",
        "phone": "063-620-1114",
        "sources": "http://www.namwonmed.or.kr/",
        "verification": "공식 정보 확인",
        "notes": "남원 및 지리산 인근 영호남 접경 지역의 거점 공공병원. 전문 재활치료팀이 마비 환자 맞춤 운동/작업/언어 치료와 1:1 보행 훈련 프로그램 가동."
    },
    {
        "id": "27",
        "district": "남원시",
        "name": "남원노인요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "노인성 뇌신경 장애 기능 유지, 인지 훈련 물리치료",
        "specialty": "도통동 요양병원 / 재활의학과 전문의 협진",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "전북특별자치도 남원시 요천로 1641 (도통동)",
        "phone": "063-630-1000",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "남원 도통동 소재 요양병원. 치매안심병동을 보유하고 있으며, 재활의학과 협진 하에 고령 마비 환자들의 보존적 일상 재활 운동치료 진행."
    },
    {
        "id": "28",
        "district": "남원시",
        "name": "더조은재활의학과의원",
        "type": "의원",
        "inclusion": "비수술 통증 전문",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "비수술 척추 통증, 디스크 물리치료, 도수치료, 교정 운동",
        "specialty": "남원 금동 소재 / 척추 및 관절 정밀 도수재활",
        "recovery": "해당없음",
        "workersComp": "가능",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "전북특별자치도 남원시 용성로 162 (금동)",
        "phone": "063-625-7582",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "남원시 금동에 위치. 최첨단 견인 치료기 및 도수치료실을 갖추어 척추/관절 질환 비수술 재활 전문 의원으로 평판이 높음."
    },
    {
        "id": "29",
        "district": "김제시",
        "name": "가족사랑요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활/암재활",
        "conditions": "암 통합 면역 보존재활, 노인성 만성 통증, 수술 후 회복 물리치료",
        "specialty": "김제 신풍동 소재 / 암 케어 및 물리재활 연계",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "전북특별자치도 김제시 동비사벌1길 35 (신풍동)",
        "phone": "063-540-8000",
        "sources": "http://www.hyofamily.com/",
        "verification": "공식 정보 확인",
        "notes": "김제 신풍동 소재. 암 통합 면역 케어와 함께 고령 환자를 위한 표준 물리치료 및 노인 행동 안정 재활 프로그램을 병행 제공."
    },
    {
        "id": "30",
        "district": "정읍시",
        "name": "김태진재활의학과의원",
        "type": "의원",
        "inclusion": "비수술 통증 전문",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "디스크 신경 치료, 만성 척추 통증, 체외충격파, 물리치료",
        "specialty": "정읍 수성동 중심가 / 비수술 척추·관절 재활",
        "recovery": "해당없음",
        "workersComp": "가능",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "전북특별자치도 정읍시 중앙로 109 (수성동)",
        "phone": "063-535-3114",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "정읍 수성동 거점 재활클리닉. 비수술적 통증 완화 치료, 자세 정밀교정 도수치료 및 체계적인 고성능 물리재활 기기 완비."
    }
];
