window.REHAB_DATA = [
    {
        "id": "1",
        "district": "서귀포시",
        "name": "제주권역재활병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활/소아재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 소아재활, 근골격계 재활",
        "specialty": "보건복지부 회복기 지정 / 산재 재활인증 / 공공어린이재활센터",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "제주특별자치도 서귀포시 동문로 1 (서귀동)",
        "phone": "064-730-9000",
        "sources": "http://www.jrh.or.kr/",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "제주 유일의 권역재활병원. 보건복지부 지정 제3기 회복기 재활의료기관 (2026.03 ~ 2029.02) 및 제주권 공공어린이재활의료센터로 성인 및 아동 전문 재활을 실시합니다. 간호간병통합서비스 병동 운영."
    },
    {
        "id": "2",
        "district": "제주시",
        "name": "제주대학교병원",
        "type": "종합병원",
        "inclusion": "재활의학과 보유 종합병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "급성기/입원재활/외래재활",
        "conditions": "뇌졸중, 척수손상, 근골격계, 소아재활, 수술 후 조기재활",
        "specialty": "국립대학병원 / 권역심뇌혈관질환센터",
        "recovery": "해당없음",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "제주특별자치도 제주시 아란13길 15 (아라일동)",
        "phone": "064-717-1114",
        "sources": "https://www.jejunuh.co.kr/",
        "verification": "HIRA/공단 확인",
        "notes": "국립대학교병원으로서 권역심뇌혈관질환센터와 긴밀하게 연계하여 뇌신경 및 척수 손상 환자 수술 직후의 고난도 초기 집중 재활치료를 운영합니다."
    },
    {
        "id": "3",
        "district": "제주시",
        "name": "제주한라병원",
        "type": "종합병원",
        "inclusion": "재활의학과 보유 종합병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "급성기/입원재활/외래재활",
        "conditions": "뇌졸중, 척수손상, 수술 후 조기재활, 스포츠 재활, 척추관절",
        "specialty": "권역외상센터 / 권역응급의료센터",
        "recovery": "해당없음",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "제주특별자치도 제주시 도령로 65 (연동)",
        "phone": "064-740-5000",
        "sources": "http://www.hallahosp.co.kr/",
        "verification": "HIRA/공단 확인",
        "notes": "도내 대표 민간 종합병원으로 권역외상센터 기반 급성기 단계 조기 재활치료 및 다양한 질환군 대상의 개인별 맞춤 재활 프로그램을 가동합니다."
    },
    {
        "id": "4",
        "district": "제주시",
        "name": "제주한국병원",
        "type": "종합병원",
        "inclusion": "재활의학과 진료 연동 종합병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/물리치료",
        "conditions": "척추 디스크, 관절염, 만성 통증 물리치료, 수술 후 회복",
        "specialty": "관절·척추센터 / 뇌신경 센터 협진",
        "recovery": "해당없음",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "제주특별자치도 제주시 서광로 193 (삼도일동)",
        "phone": "064-750-0114",
        "sources": "http://www.hk-hosp.co.kr/",
        "verification": "HIRA 확인",
        "notes": "삼도동 소재 중견 종합병원. 관절/척추센터 및 뇌신경 진료과와 유기적으로 연계된 물리재활치료실 가동."
    },
    {
        "id": "5",
        "district": "서귀포시",
        "name": "서귀포의료원",
        "type": "종합병원",
        "inclusion": "재활의학과 보유 종합병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "급성기/입원재활/외래재활",
        "conditions": "뇌졸중 후유장애, 중추신경계 재활, 근골격계 통증, 외상후 재활",
        "specialty": "지역 거점 공공병원 / 긴급의료",
        "recovery": "해당없음",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "제주특별자치도 서귀포시 장수로 47 (동홍동)",
        "phone": "064-730-3000",
        "sources": "http://www.jjsmc.or.kr/",
        "verification": "HIRA/공단 확인",
        "notes": "서귀포 지역 거점 공공의료기관으로 재활의학과 전문의 진료 하에 외래 물리치료 및 급성기 퇴원 후 통합 재활 서비스를 제공합니다."
    },
    {
        "id": "6",
        "district": "제주시",
        "name": "제주의료원부속요양병원",
        "type": "요양병원",
        "inclusion": "공공 요양재활 전문",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/외래재활",
        "conditions": "뇌졸중 후유증, 치매 및 노인성 질환, 인지재활, 기능 유지 재활",
        "specialty": "도립 공공요양병원 / 제주의료원 협진",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "미운영",
        "address": "제주특별자치도 제주시 산천단남길 10 (아라일동)",
        "phone": "064-720-2222",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "제주의료원과 부지 내 인접하여 긴밀한 의료 협진 체계를 갖추었으며, 노인성 질환 환자를 위한 전산화 인지재활 및 신체 기능 유지 재활에 특화되어 있습니다."
    },
    {
        "id": "7",
        "district": "제주시",
        "name": "늘봄재활요양병원",
        "type": "요양병원",
        "inclusion": "요양재활/투석가능 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/외래재활",
        "conditions": "뇌경색, 뇌출혈, 파킨슨, 척수손상, 신부전(투석), 수술 후 요양재활",
        "specialty": "재활치료실 운영 / 인공신장실(투석) 병행",
        "recovery": "해당없음",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "제주특별자치도 제주시 서광로 126 (삼도이동)",
        "phone": "064-727-2000",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "제주시 중심가에 위치한 재활 특화 요양병원입니다. 집중 물리치료 및 운동치료실을 완비하였으며 인공신장실을 함께 갖추어 투석 중 재활치료가 가능합니다."
    },
    {
        "id": "8",
        "district": "제주시",
        "name": "제주제일요양병원",
        "type": "요양병원",
        "inclusion": "요양재활 전문",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/외래재활",
        "conditions": "중추신경계 재활, 치매, 노인성 질환, 관절 전치환술 후 재활요양",
        "specialty": "고령 환자 특화 케어 / 물리재활",
        "recovery": "해당없음",
        "workersComp": "산재지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "제주특별자치도 제주시 신대로 155 (연동)",
        "phone": "064-745-9988",
        "sources": "http://www.jejufirsth.co.kr/",
        "verification": "HIRA 확인",
        "notes": "쾌적한 요양 병상과 체계적인 재활치료실을 갖춘 요양병원으로, 장기 케어가 필요한 환자들의 관절 가동범위 확보 및 운동성 회복 치료를 병행합니다."
    },
    {
        "id": "9",
        "district": "제주시",
        "name": "토마토요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활의학과 상주",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/물리치료",
        "conditions": "뇌졸중 마비, 노인성 만성 통증, 치매 요양, 보행 회복",
        "specialty": "재활의학과 전문의 상주 / 체계적 물리치료실",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "제주특별자치도 제주시 동광로 42 (이도이동)",
        "phone": "064-724-7575",
        "sources": "http://www.tomatohospital.com/",
        "verification": "HIRA 확인",
        "notes": "이도동 법원 인근에 위치. 재활의학과 전문의 진료 및 만성 질환 환자를 위한 맞춤형 온열치료 및 운동물리치료 병행."
    },
    {
        "id": "10",
        "district": "제주시",
        "name": "아라요양병원",
        "type": "요양병원",
        "inclusion": "요양재활 전문",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/외래재활",
        "conditions": "뇌졸중 후유 장애, 연하 장애, 인지 기능 회복, 노인성 만성질환",
        "specialty": "운동치료 / 작업치료 / 인지재활 프로그램",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "제주특별자치도 제주시 아란3길 78 (아라일동)",
        "phone": "064-702-8000",
        "sources": "http://www.arahosp.com/",
        "verification": "HIRA 확인",
        "notes": "아라동의 조용하고 자연 친화적인 입지 조건을 갖추었으며 뇌병변 환자들의 일상 복귀를 위한 성인 운동재활치료실 및 작업치료 프로그램을 활발히 가동합니다."
    },
    {
        "id": "11",
        "district": "제주시",
        "name": "제주춘강의원",
        "type": "의원",
        "inclusion": "공익 재활의학과 전문의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "뇌성마비, 소아발달지연, 아동 발달재활, 성인 뇌질환 외래 재활",
        "specialty": "사회복지법인 춘강 운영 / 소아재활 특화",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "제주특별자치도 제주시 아연로 213 (오라삼동)",
        "phone": "064-747-8100",
        "sources": "http://www.jejurh.com/",
        "verification": "공식 확인",
        "notes": "사회복지법인 춘강에서 운영하여 공익성이 강한 재활 전문 의원입니다. 특히 영유아 및 어린이 발달 지연 아동 대상의 소아재활 및 감각통합치료 분야에서 높은 신뢰를 받습니다."
    },
    {
        "id": "12",
        "district": "제주시",
        "name": "제주연합재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문외래",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "척추·관절 통증, 디스크, 도수치료, 비수술 체형교정, 물리치료",
        "specialty": "일대일 맞춤 도수치료 / 통증 클리닉",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "가능",
        "dayRehab": "미운영",
        "address": "제주특별자치도 제주시 동광로 123 (이도이동)",
        "phone": "064-726-2114",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "제주시 이도이동에 위치하여 통원 접근성이 높고, 정형재활 및 통증 비수술 요법, 도수치료를 일대일 맞춤형으로 시행하는 전문 외래 기관입니다."
    },
    {
        "id": "13",
        "district": "제주시",
        "name": "고영호재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문외래",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "만성 통증, 디스크, 오십견, 관절염 비수술 재활, 물리치료",
        "specialty": "척추·관절 보존적 치료 / 외래 물리치료",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "가능",
        "dayRehab": "미운영",
        "address": "제주특별자치도 제주시 용담로 64 (용담일동)",
        "phone": "064-758-5275",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "용담동 지역에서 오랜 임상 경험을 가진 전문의 진료 하에 퇴행성 관절 질환 및 척추 질환의 보존적 재활과 외래 물리치료에 특화되어 있습니다."
    },
    {
        "id": "14",
        "district": "서귀포시",
        "name": "서귀포재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 전문외래",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "근골격계 손상, 자세 불균형 교정, 도수치료, 스포츠 물리치료",
        "specialty": "서귀포 도심부 외래재활 / 도수치료실 운영",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "가능",
        "dayRehab": "미운영",
        "address": "제주특별자치도 서귀포시 중앙로 73, 2층 (서귀동)",
        "phone": "064-733-8875",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "서귀포 동홍동/서귀동 인근 시민들을 위한 재활의학과 통원 치료 의원으로, 목/허리 통증 완화를 위한 체계적인 물리치료 및 수기 도수치료를 시행합니다."
    }
];
