window.REHAB_DATA = [
    {
        "id": "1",
        "district": "연수구",
        "name": "경인권역재활병원",
        "type": "병원",
        "inclusion": "권역재활 거점 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활/낮병동",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 소아재활, 수중치료, 근골격계 재활",
        "specialty": "인천 최초 권역별 재활병원 / 수중재활치료실 운영",
        "recovery": "해당없음",
        "workersComp": "산재 지정",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "인천광역시 연수구 벚꽃로 115 (청학동)",
        "phone": "032-899-9000",
        "sources": "http://www.rch.or.kr/ https://www.hira.or.kr/ https://www.nrc.go.kr/",
        "verification": "보건복지부/HIRA/국립재활원 확인",
        "notes": "보건복지부와 인천광역시가 설립하고 대한적십자사가 수탁 운영하는 인천 최초의 권역재활병원. 첨단 로봇 및 수중재활 설비 보유."
    },
    {
        "id": "2",
        "district": "부평구",
        "name": "근로복지공단 인천병원",
        "type": "종합병원",
        "inclusion": "공단 직영 재활 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활/낮병동",
        "conditions": "산재 재활, 뇌졸중, 척수손상, 근골격계 재활, 수중치료, 직업복귀",
        "specialty": "근로복지공단 직영 종합병원 / 초대형 재활전문센터",
        "recovery": "해당없음",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "인천광역시 부평구 무네미로 446 (구산동)",
        "phone": "032-500-0114",
        "sources": "https://www.comwel.or.kr/incheon/ https://www.hira.or.kr/",
        "verification": "근로복지공단/HIRA 확인",
        "notes": "근로복지공단 직영 대표 병원. 약 1,000평 규모의 대형 전문재활센터와 국내 최고 수준의 수중재활치료풀을 보유하여 산재 및 일반 재활에 최적화."
    },
    {
        "id": "3",
        "district": "남동구",
        "name": "미추홀병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활/낮병동",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 근골격계 재활, 수술 후 재활",
        "specialty": "보건복지부 회복기 지정 / 산재 재활인증",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "인천광역시 남동구 남동대로 748 (구월동)",
        "phone": "032-430-3000",
        "sources": "http://www.mchhospital.co.kr/ https://www.hira.or.kr/",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관(2026.03 ~ 2029.02). 6인의 재활의학과 전문의가 상주하며 간호간병통합서비스 병동 운영."
    },
    {
        "id": "4",
        "district": "남동구",
        "name": "브래덤재활병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활/낮병동",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 통증 및 중추신경계 마비 재활",
        "specialty": "보건복지부 회복기 지정 / 산재 재활인증",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "인천광역시 남동구 인하로 545 (구월동)",
        "phone": "032-456-1100",
        "sources": "http://www.braddom.co.kr/ https://www.hira.or.kr/",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관. 뇌신경계 마비 환자 집중재활 프로그램 및 스마트 재활 기기 보유."
    },
    {
        "id": "5",
        "district": "계양구",
        "name": "서송병원",
        "type": "병원",
        "inclusion": "회복기 지정/소아재활 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활/낮병동",
        "conditions": "뇌졸중, 척수손상, 소아재활, 뇌성마비, 근골격계 집중재활",
        "specialty": "보건복지부 회복기 지정 / 어린이 재활 특화",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "인천광역시 계양구 계양대로 102 (작전동)",
        "phone": "032-552-3000",
        "sources": "http://www.xn--om3bn2foli5o.kr/ https://www.hira.or.kr/",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관. 인천 유일의 대규모 어린이재활 전문 시스템 구축 및 통원 낮병동 운영."
    },
    {
        "id": "6",
        "district": "남동구",
        "name": "위드미요양병원",
        "type": "요양병원",
        "inclusion": "재활의학과 보유 요양병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활/로봇재활",
        "conditions": "뇌신경계 마비 재활, 근골격계 통증, 노인성 질환 관리",
        "specialty": "심평원 적정성평가 1등급 / 워크봇(Walkbot) 로봇재활 보유",
        "recovery": "해당없음",
        "workersComp": "산재 지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "인천광역시 남동구 경인로 712 (간석동)",
        "phone": "032-421-2200",
        "sources": "http://www.withme-medi.com/ https://www.hira.or.kr/",
        "verification": "HIRA 적정성평가 1등급 확인",
        "notes": "5회 연속 HIRA 적정성평가 1등급 획득 요양병원. 로봇보행재활 치료기(워크봇) 등 첨단 재활 장비와 1:1 맞춤형 치료사 매핑."
    },
    {
        "id": "7",
        "district": "남동구",
        "name": "인천로뎀요양병원",
        "type": "요양병원",
        "inclusion": "재활의학과 보유 요양병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌졸중, 파킨슨병, 루게릭병, 인공호흡기 케어, 중증 신경계재활",
        "specialty": "의료인력 1등급 유지 / 신경외과 및 재활의학과 협진",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "인천광역시 남동구 석정로 502 (간석동)",
        "phone": "032-438-7575",
        "sources": "http://www.therodem.com/ https://www.hira.or.kr/",
        "verification": "HIRA 의료인력 1등급 확인",
        "notes": "뇌신경계 중증 만성 질환 특화 요양병원. 환자 맞춤형 잔존 기능 유지를 위한 장기 재활 및 한방 치료 연계."
    },
    {
        "id": "8",
        "district": "미추홀구",
        "name": "퍼스트병원",
        "type": "병원",
        "inclusion": "재활의학과 전문병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활/도수치료",
        "conditions": "뇌졸중, 척수손상, 편마비, 파킨슨 재활, 근골격계 통증",
        "specialty": "보행로봇재활실 운영 / 1:1 전담 재활치료",
        "recovery": "해당없음",
        "workersComp": "산재 지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "인천광역시 미추홀구 인주대로 438 (주안동)",
        "phone": "032-220-7575",
        "sources": "http://www.xn--om3bn0iuzdksp71a.com/ https://www.hira.or.kr/",
        "verification": "HIRA 확인",
        "notes": "1:1 중추신경계 발달재활치료 전문. 고성능 보행재활 로봇 도입으로 집중 보행 훈련 프로그램 강점."
    },
    {
        "id": "9",
        "district": "서구",
        "name": "청담재활요양병원",
        "type": "요양병원",
        "inclusion": "재활의학과 보유 요양병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활/격리재활",
        "conditions": "편마비 재활, 파킨슨병, 암 재활, 감염병동(CRE/VRE) 격리치료",
        "specialty": "VRE/CRE 감염환자 격리 재활치료센터 운영",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "인천광역시 서구 가남로 75 (가좌동)",
        "phone": "032-581-7979",
        "sources": "http://www.cdhosp.com/ https://www.hira.or.kr/",
        "verification": "HIRA 확인/개별 점검",
        "notes": "감염 환자(CRE, VRE)를 위한 넓은 격리 치료 공간과 전담 물리치료사를 배치하여 안전한 격리 재활 환경 제공."
    },
    {
        "id": "10",
        "district": "남동구",
        "name": "인천나은요양병원",
        "type": "요양병원",
        "inclusion": "재활의학과 보유 요양병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌신경계 질환, 편마비 재활, 노인 만성 질환 치료",
        "specialty": "한·양방 협진 시스템 / 소래포구역 인근",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "인천광역시 남동구 아암대로1503번길 21 (논현동)",
        "phone": "032-441-1114",
        "sources": "http://naeunhospital.co.kr/ https://www.hira.or.kr/",
        "verification": "HIRA 확인",
        "notes": "뇌신경계 집중재활센터 및 투석 클리닉 보유. 서구 소재 '나은병원' 종합병원과는 별개의 요양병원으로 확인 필요."
    },
    {
        "id": "11",
        "district": "남동구",
        "name": "효민요양병원",
        "type": "요양병원",
        "inclusion": "재활의학과 보유 요양병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌경색·뇌출혈 후유재활, 근골격계 노인 재활, 한방 치료",
        "specialty": "HIRA 적정성평가 1등급 획득 / 쾌적한 신축 시설",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "인천광역시 남동구 서창남순환로216번길 36",
        "phone": "032-463-2114",
        "sources": "http://www.hyominhospital.com/ https://www.hira.or.kr/",
        "verification": "HIRA 적정성평가 1등급 확인",
        "notes": "쾌적한 서창2지구에 위치. 넓은 운동 치료 구역 및 한방 침구 진료를 아우르는 전인적 요양재활 시행."
    },
    {
        "id": "12",
        "district": "부평구",
        "name": "이편안인천요양병원",
        "type": "요양병원",
        "inclusion": "재활의학과 보유 요양병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활/통원치료",
        "conditions": "수술 후 재활, 마비 환자 도수치료, 작업치료 및 연하재활",
        "specialty": "부평구 관내 대형 재활요양 / 환자 1:1 맞춤 관리",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "인천광역시 부평구 경인로 884",
        "phone": "032-868-9988",
        "sources": "http://www.8689988.co.kr/ https://www.hira.or.kr/",
        "verification": "HIRA 확인",
        "notes": "부평삼거리역 인근. 정형 및 신경 손상 후 단계적 1:1 관리를 수행하는 전문 물리치료사 배치."
    },
    {
        "id": "13",
        "district": "부평구",
        "name": "가톨릭대학교 인천성모병원",
        "type": "종합병원",
        "inclusion": "상급종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "급성기/단기입원재활/외래진료",
        "conditions": "뇌졸중 초기 급성기 재활, 뇌신경 장애, 연하 곤란 재활",
        "specialty": "상급종합병원 수준의 뇌질환 초기 협진 정밀 케어",
        "recovery": "해당없음",
        "workersComp": "산재 지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "인천광역시 부평구 동수로 56 (부평동)",
        "phone": "1544-9008",
        "sources": "https://www.cmcism.or.kr/ https://www.hira.or.kr/",
        "verification": "HIRA 확인",
        "notes": "대학병원 전문 의료진에 의한 고도화된 급성기 초기 재활치료. 급성기 경과 후 재활의료기관 연계 체계 작동."
    },
    {
        "id": "14",
        "district": "중구",
        "name": "인하대학교의과대학부속병원",
        "type": "종합병원",
        "inclusion": "상급종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "급성기/단기입원재활/외래진료",
        "conditions": "뇌신경 손상 재활, 스포츠 손상, 소아재활, 신경근육 희귀질환",
        "specialty": "인천 대표 상급종합병원 / 다방면 임상 연구 및 전문 재활",
        "recovery": "해당없음",
        "workersComp": "산재 지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "인천광역시 중구 인하로 27 (신흥동3가)",
        "phone": "032-890-2114",
        "sources": "https://www.inha.com/ https://www.hira.or.kr/",
        "verification": "HIRA 확인",
        "notes": "정형·신경·소아 전문 세분화된 진료팀 운영. 고난도 중증 장애 환자에 대한 다학제 협진 및 1등급 의료 장비 구축."
    },
    {
        "id": "15",
        "district": "남동구",
        "name": "가천대 길병원",
        "type": "종합병원",
        "inclusion": "상급종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "급성기/단기입원재활/외래진료",
        "conditions": "뇌혈관 수술 후 초기 재활, 척수 손상, 암환자 스포츠 재활",
        "specialty": "인천 최대 의료 인프라 / 권역외상·뇌혈관센터 연계 조기 재활",
        "recovery": "해당없음",
        "workersComp": "산재 지정",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "인천광역시 남동구 남동대로 774번길 21 (구월동)",
        "phone": "1577-2299",
        "sources": "https://www.gilhospital.com/ https://www.hira.or.kr/",
        "verification": "HIRA 확인",
        "notes": "권역응급 및 외상센터 연계형 급성기 집중 재활. 조기 침상 재활부터 로봇 훈련까지 다양한 연계 프로그램 가동."
    },
    {
        "id": "16",
        "district": "미추홀구",
        "name": "인천사랑병원",
        "type": "종합병원",
        "inclusion": "재활의학과 보유 종합병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활/도수치료",
        "conditions": "뇌졸중 후유 재활, 관절 수술 후 재활, 요통 및 척추 관절 치료",
        "specialty": "미추홀구 거점 종합병원 / 맞춤 재활치료센터 운영",
        "recovery": "해당없음",
        "workersComp": "산재 지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "인천광역시 미추홀구 경인로 372 (주안동)",
        "phone": "032-427-0114",
        "sources": "http://www.saranghospital.com/ https://www.hira.or.kr/",
        "verification": "HIRA 확인",
        "notes": "정형·신경 질환 맞춤형 종합 진단 후 1:1 맞춤형 치료사 배치. 단계별 운동 및 작업 치료실 구비."
    },
    {
        "id": "17",
        "district": "남동구",
        "name": "인천힘찬종합병원",
        "type": "종합병원",
        "inclusion": "재활의학과 보유 종합병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활/도수치료",
        "conditions": "인공관절 수술 후 운동치료, 척수 손상, 만성 통증 조절",
        "specialty": "척추·관절 정형외과 협진 강점 / 힘찬병원 그룹 노하우",
        "recovery": "해당없음",
        "workersComp": "산재 지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "인천광역시 남동구 논고개로 87 (논현동)",
        "phone": "1899-2224",
        "sources": "http://www.himchangeneral.com/ https://www.hira.or.kr/",
        "verification": "HIRA 확인",
        "notes": "정형 외과 및 관절 치료 특화 종합병원으로 수술 직후 정밀 운동 재활 프로그램 및 1:1 도수치료 연계 시스템 우수."
    },
    {
        "id": "18",
        "district": "계양구",
        "name": "인천세종병원",
        "type": "종합병원",
        "inclusion": "재활의학과 보유 종합병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활/심장호흡재활",
        "conditions": "심장 재활, 호흡 재활, 신경마비성 장애, 근골격계 손상",
        "specialty": "보건복지부 지정 심장전문병원 연계 심장 및 호흡기 재활 특화",
        "recovery": "해당없음",
        "workersComp": "산재 지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "인천광역시 계양구 계양문화로 20 (작전동)",
        "phone": "1599-0900",
        "sources": "http://www.sejongh.co.kr/ https://www.hira.or.kr/",
        "verification": "HIRA 확인",
        "notes": "뇌/척수 신경재활 뿐만 아니라, 국내 최고 수준의 심장 재활 치료실 및 호흡 재활 치료팀을 운영하여 복합 장애 극복 기여."
    },
    {
        "id": "19",
        "district": "서구",
        "name": "서울대효청라요양병원",
        "type": "요양병원",
        "inclusion": "재활의학과 보유 요양병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌신경계 질환, 뇌졸중(뇌경색/뇌출혈) 재활, 외상성 뇌손상, 양한방 협진",
        "specialty": "뇌신경계 질환 특화 재활치료 / 양한방 협진",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "인천광역시 서구 염곡로464번길 11 (가정동, 루원탑프라자 4~8층)",
        "phone": "032-724-7114",
        "sources": "http://www.seouldhc.co.kr/ https://www.hira.or.kr/",
        "verification": "HIRA 확인",
        "notes": "뇌신경계 집중재활치료 솔루션 운영. 입원 초기부터 1:1 맞춤 치료사 배정을 통한 집중적인 회복 치료 제공."
    },
    {
        "id": "20",
        "district": "남동구",
        "name": "라이온요양병원",
        "type": "요양병원",
        "inclusion": "재활의학과 보유 요양병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌졸중(뇌경색/뇌출혈), 파킨슨병, 근골격계 질환, 노인 만성 질환",
        "specialty": "뇌질환 특성화 재활치료센터 운영 / 침구 한방 협진",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "인천광역시 남동구 경인로 520, 탑프라자2차 5~10층 (간석동)",
        "phone": "032-426-7575",
        "sources": "http://www.lionhospital.co.kr/ https://www.hira.or.kr/",
        "verification": "HIRA 확인",
        "notes": "환자의 일상 조기 복귀를 돕는 운동 치료 및 작업 치료 세분화. 한방 침구 및 면역력 강화 병행 치료 시행."
    },
    {
        "id": "21",
        "district": "남동구",
        "name": "새인천요양병원",
        "type": "요양병원",
        "inclusion": "재활의학과 보유 요양병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌경색·뇌출혈 후유재활, 근골격계 통증 조절, 한양방 요양케어",
        "specialty": "뇌혈관 질환 후유장해 치료 전문 재활치료실 및 한방 협진",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "인천광역시 남동구 논고개로123번길 17, 아이플렉스 11층 (논현동)",
        "phone": "032-719-7874",
        "sources": "http://newincheonhospital.com/ https://www.hira.or.kr/",
        "verification": "HIRA 확인",
        "notes": "수술 후 신체 기능 회복과 통증 경감을 목표로 하는 집중 운동 치료실 운영 및 전문 치료 프로그램 진행."
    },
    {
        "id": "22",
        "district": "서구",
        "name": "청라베스트요양병원",
        "type": "요양병원",
        "inclusion": "재활의학과 보유 요양병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "중추신경계 마비 재활, 척수 손상, 인공관절 수술 후 운동장애, 양한방 통합",
        "specialty": "재활치료 전문 층별 독립 재활실 보유 및 다양한 협진 진료",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "인천광역시 서구 봉오재3로110번길 7, 가정봄프라자 6~9층 (가정동)",
        "phone": "032-220-1500",
        "sources": "http://www.cheongnabest.com/ https://www.hira.or.kr/",
        "verification": "HIRA 확인",
        "notes": "재활의학과, 가정의학과, 한방과 전문의 협진 시스템 가동. 최신 물리/작업 치료기기 및 넓은 재활 훈련장 보유."
    },
    {
        "id": "23",
        "district": "서구",
        "name": "천진요양병원",
        "type": "요양병원",
        "inclusion": "재활의학과 보유 요양병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활/투석재활",
        "conditions": "뇌신경 장애 재활, 투석 동반 환자 재활치료, 근골격계 통증",
        "specialty": "인공신장센터 및 집중치료실 연계 신장투석 동반 복합 재활",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "인천광역시 서구 건지로 264, 인하메디컬센터 4~6층 (가좌동)",
        "phone": "032-577-9777",
        "sources": "http://www.cjnh.co.kr/ https://www.hira.or.kr/",
        "verification": "HIRA 확인",
        "notes": "신장내과 및 재활의학과 협진을 통하여 만성 투석 환자도 안심하고 전문적인 신체 운동 및 기능 훈련을 병행 가능."
    }
];
