window.REHAB_DATA = [
    {
        "id": "1",
        "district": "양평군",
        "name": "국립교통재활병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활/낮병동",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 소아재활, 근골격계 재활",
        "specialty": "국토교통부 설립 / 서울대병원 위탁 운영",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "경기도 양평군 양평읍 중앙로 260",
        "phone": "031-580-5555",
        "sources": "http://ntrh.or.kr/",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "국토교통부가 설립하고 서울대학교병원이 위탁 운영하는 최고 수준의 재활병원. 보건복지부 제3기 회복기 재활의료기관 및 산재 전문재활인증 동시 획득. 소아 및 로봇재활 특화."
    },
    {
        "id": "2",
        "district": "의정부시",
        "name": "로체스터병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 근골격계 재활, 통증재활",
        "specialty": "보건복지부 제3기 회복기 재활의료기관",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 의정부시 호국로1519번길 2-29 (금오동)",
        "phone": "031-879-7575",
        "sources": "http://rochester.kr/",
        "verification": "보건복지부/HIRA 확인",
        "notes": "경기 북부 의정부 금오동에 위치한 집중 재활병원. 보건복지부 지정 회복기 의료기관으로서 맞춤형 1대1 집중 재활 치료 및 쾌적한 간호간병통합서비스 병동 운영."
    },
    {
        "id": "3",
        "district": "용인시",
        "name": "린병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활/낮병동",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 근골격계 재활, 연하장애",
        "specialty": "보건복지부 회복기 지정 / 연하(삼킴)재활 특화",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "경기도 용인시 수지구 포은대로59번길 15 (상현동, 광교복합의료센터)",
        "phone": "031-8005-1300",
        "sources": "http://rhinhospital.com/",
        "verification": "보건복지부/HIRA 확인",
        "notes": "광교신도시 인근에 위치한 회복기 재활병원. 연하장애(삼킴 장애) 재활 치료실 및 뇌신경 집중치료실 운영. 간호간병통합서비스 적용으로 간병비 부담 경감."
    },
    {
        "id": "4",
        "district": "의정부시",
        "name": "마스터플러스병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 파킨슨병, 수술 후 재활",
        "specialty": "보건복지부 제3기 회복기 재활의료기관",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 의정부시 신흥로 84 (호원동)",
        "phone": "031-879-2200",
        "sources": "http://masterplus.co.kr/",
        "verification": "보건복지부/HIRA 확인",
        "notes": "의정부 호원동 소재. 양한방 협진 시스템을 바탕으로 급성기 수술 후 집중 재활치료를 수행하는 보건복지부 지정 회복기 병원."
    },
    {
        "id": "5",
        "district": "용인시",
        "name": "바로웰병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 관절 수술 후 재활, 도수치료",
        "specialty": "보건복지부 제3기 회복기 재활의료기관",
        "recovery": "지정(제3기)",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 용인시 수지구 현암로 72 (죽전동)",
        "phone": "031-266-8005",
        "sources": "http://barowellhospital.com/",
        "verification": "보건복지부/HIRA 확인",
        "notes": "용인 수지 죽전동에 위치하며, 뇌신경계 질환 환자 및 정형외과적 관절 수술 환자의 빠른 사회 복귀를 위한 집중 재활치료를 전문으로 합니다."
    },
    {
        "id": "6",
        "district": "수원시",
        "name": "베데스다재활병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활/낮병동",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 소아재활, 성인집중재활",
        "specialty": "보건복지부 회복기 지정 / 소아재활 특화",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "경기도 수원시 영통구 봉영로 1623 (영통동, 드림피아빌딩 6~9층)",
        "phone": "1544-7955",
        "sources": "http://bedesdacare.co.kr/",
        "verification": "보건복지부/HIRA 확인",
        "notes": "수원 영통에 위치한 전문 재활병원. 성인 집중재활은 물론 소아재활클리닉과 소아/성인 낮병동을 체계적으로 구축하여 지역사회 소아 재활 거점 역할 수행."
    },
    {
        "id": "7",
        "district": "성남시",
        "name": "분당베스트병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활/낮병동",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 로봇보행재활, 인공관절 수술 후 재활",
        "specialty": "보건복지부 회복기 지정 / 산재 재활인증 / 로봇재활",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "경기도 성남시 분당구 성남대로926번길 6 (야탑동, 대덕프라자 7~8층)",
        "phone": "1899-0175",
        "sources": "http://okbest.kr/",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "성남 분당 야탑역 역세권에 위치. 보건복지부 지정 회복기 병원 및 산재 전문재활인증 기관. 첨단 보행보조 로봇 재활 시스템과 대규모 물리/작업치료실 완비."
    },
    {
        "id": "8",
        "district": "수원시",
        "name": "수원센텀병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 뼈/관절 골절 및 수술 후 재활",
        "specialty": "보건복지부 제3기 회복기 재활의료기관",
        "recovery": "지정(제3기)",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 수원시 권선구 호매실로90번길 76 (호매실동, 2~5층)",
        "phone": "1899-0333",
        "sources": "http://suwoncentum.com/",
        "verification": "보건복지부/HIRA 확인",
        "notes": "수원 호매실 지구에 위치하며 정형외과·신경외과와의 긴밀한 협진이 강점. 수술 후 관절 재활과 중추신경계 집중 치료를 균형 있게 제공함."
    },
    {
        "id": "9",
        "district": "광주시",
        "name": "에스알씨(SRC)재활병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활/낮병동",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 소아재활, 호흡재활, 암재활, 언어치료",
        "specialty": "보건복지부 회복기 지정 / 산재 재활인증 / 대규모 치료센터",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "경기도 광주시 초월읍 경수길 25",
        "phone": "031-760-3636",
        "sources": "http://srchospital.com/",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "70년 이상의 역사를 지닌 사회복지법인 SRC 산하의 대한민국 대표 재활병원. 보건복지부 지정 회복기 기관 및 산재 전문재활인증 의료기관. 호흡재활, 연하재활, 로봇 치료 특화."
    },
    {
        "id": "10",
        "district": "성남시",
        "name": "위례재활의학과병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활/낮병동",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 파킨슨병, 스포츠 손상 재활",
        "specialty": "보건복지부 제3기 회복기 재활의료기관",
        "recovery": "지정(제3기)",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "경기도 성남시 수정구 위례서일로 6 (창곡동, 6층~9층)",
        "phone": "031-751-0660",
        "sources": "https://www.hira.or.kr",
        "verification": "보건복지부/HIRA 확인",
        "notes": "성남 위례신도시에 위치한 재활의학과 전문 병원. 중추신경계 집중 치료를 위한 쾌적한 입원실 및 1:1 맞춤 운동치료, 작업치료, 인지치료실 운영."
    },
    {
        "id": "11",
        "district": "수원시",
        "name": "윤강병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 정형외과 수술 후 관절 재활",
        "specialty": "보건복지부 제3기 회복기 재활의료기관",
        "recovery": "지정(제3기)",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 수원시 영통구 덕영대로1483번길 12 (망포동)",
        "phone": "031-217-3000",
        "sources": "https://www.hira.or.kr",
        "verification": "보건복지부/HIRA 확인",
        "notes": "수원 영통 망포역 근처에 위치. 재활의학과 전문의 및 전문 물리치료사와의 긴밀한 1:1 환자 케어 매칭을 통해 보건복지부 회복기 기관 자격 유지."
    },
    {
        "id": "12",
        "district": "고양시",
        "name": "일산복음재활병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활/낮병동",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 중추신경계 집중재활, 스포츠재활",
        "specialty": "보건복지부 회복기 지정 / 산재 재활인증 / 로봇보행",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "경기도 고양시 일산동구 고양대로 760, 나동 (중산동)",
        "phone": "031-977-6633",
        "sources": "http://isgrh.co.kr/",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "고양 일산 중산동에 위치. 대규모 재활치료 공간을 확보하고 치료사 1:1 맞춤 도수/기능훈련 및 로봇 보행 보조 시스템 적용. 간호간병통합서비스 우수 등급 획득."
    },
    {
        "id": "13",
        "district": "고양시",
        "name": "일산중심재활병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활/낮병동",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 근골격계 관절 재활, 소아재활",
        "specialty": "보건복지부 회복기 지정 / 산재 재활인증 / 연하장애치료",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "경기도 고양시 일산서구 미래로 227 (덕이동)",
        "phone": "031-810-2000",
        "sources": "http://centerh.co.kr/",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "일산 덕이동 위치. 뇌신경재활, 소아재활, 성인 및 소아 낮병동을 완비. 보행훈련 로봇 및 상지재활 로봇 기기를 다수 운용하는 경기 북부 거점 회복기 지정병원."
    },
    {
        "id": "14",
        "district": "구리시",
        "name": "카이저재활병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 근골격계 집중재활, 신경계 질환",
        "specialty": "보건복지부 제3기 회복기 재활의료기관",
        "recovery": "지정(제3기)",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 구리시 건원대로 44 (인창동, 태영프라자 5~7층)",
        "phone": "031-554-7727",
        "sources": "http://kaiserh.co.kr/",
        "verification": "보건복지부/HIRA 확인",
        "notes": "구리역 인근 위치. 구리/남양주 권역 내 보건복지부 지정 3기 회복기 의료기관. 환자별 맞춤 집중 치료계획을 바탕으로 신속한 기능적 일상 회복에 집중."
    },
    {
        "id": "15",
        "district": "수원시",
        "name": "해성병원",
        "type": "병원",
        "inclusion": "회복기 지정 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 노인성 만성질환 재활",
        "specialty": "보건복지부 제3기 회복기 재활의료기관",
        "recovery": "지정(제3기)",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 수원시 팔달구 경수대로 542 (인계동)",
        "phone": "031-222-7511",
        "sources": "http://hshospital.kr/",
        "verification": "보건복지부/HIRA 확인",
        "notes": "수원 인계동 사거리에 위치. 재활의학과 전문의 및 숙련된 재활치료팀이 배치된 회복기 지정 재활병원으로, 간호간병통합서비스 병동 적용으로 안전하고 간병 걱정 없는 환경 제공."
    },
    {
        "id": "16",
        "district": "부천시",
        "name": "휴앤유병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활/낮병동",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 근골격계 수술 후 재활, 파킨슨",
        "specialty": "보건복지부 회복기 지정 / 산재 재활인증",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "경기도 부천시 소사구 심곡로10번길 63 (송내동)",
        "phone": "032-202-0114",
        "sources": "http://hunu.co.kr/",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "부천 소사구 송내동에 위치한 대표적인 대형 전문재활병원. 보건복지부 회복기 지정 및 근로복지공단 산재 전문재활인증기관. 개인 맞춤형 체계적 프로그램 운영."
    },
    {
        "id": "17",
        "district": "성남시",
        "name": "분당러스크재활병원",
        "type": "병원",
        "inclusion": "산재 재활인증 / 특화 재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활/낮병동",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 언어치료, 연하장애재활",
        "specialty": "근로복지공단 산재 재활인증병원",
        "recovery": "해당없음",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "경기도 성남시 분당구 정자일로 156번길 6 (정자동, 뉴본타워)",
        "phone": "031-716-0007",
        "sources": "http://www.rusk.or.kr",
        "verification": "HIRA/공단/홈페이지 확인",
        "notes": "분당 정자동에 위치한 산재 지정 전문 재활인증 병원. 뇌졸중 및 척수손상 초기부터 중기 이후 환자의 장단기 맞춤식 집중 재활을 선도적으로 제공."
    },
    {
        "id": "18",
        "district": "용인시",
        "name": "광교참좋은병원",
        "type": "병원",
        "inclusion": "특화 재활 / 요양입원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "뇌손상, 척수손상, 파킨슨병, 노인성 질환 재활",
        "specialty": "중증 재활 치료실 및 인공관절 재활",
        "recovery": "해당없음",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 용인시 수지구 광교중앙로 311 (상현동, 희성빌딩 3~9층)",
        "phone": "031-216-9888",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "광교신도시에 인접한 재활 특화 요양 성격의 병원. 정밀 평가 후 맞춤 도수치료 및 작업치료 제공. 장기 및 집중 재활 병동 분리 운영."
    },
    {
        "id": "19",
        "district": "안산시",
        "name": "안산베스트힐스요양병원",
        "type": "요양병원",
        "inclusion": "재활요양 / 1등급 요양병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/입원재활",
        "conditions": "뇌졸중, 파킨슨병, 노인성 질환, 인공호흡기 케어",
        "specialty": "HIRA 요양병원 적정성 평가 1등급",
        "recovery": "해당없음",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 안산시 상록구 선진안길 17 (사동)",
        "phone": "031-415-2300",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "안산 사동 위치. 요양병원 적정성 평가 1등급 의료기관으로 재활의학과 전문의가 상주하며 투석 및 인공호흡기 보유 병동과 재활치료실을 균형 있게 운영."
    },
    {
        "id": "20",
        "district": "부천시",
        "name": "고려수재활요양병원",
        "type": "요양병원",
        "inclusion": "재활요양 / 양한방 협진",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌외상, 파킨슨병, 양한방 통합 재활",
        "specialty": "재활 집중 병동 및 한방재활 연계",
        "recovery": "해당없음",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 부천시 부일로 504 (심곡동)",
        "phone": "032-347-2300",
        "sources": "http://www.krsh.co.kr",
        "verification": "HIRA/홈페이지 확인",
        "notes": "부천 심곡동 부천역 인근 위치. 넓은 규모 of 집중 재활치료실에서 양·한방 협진을 통한 다각적 기능 복귀 프로그램 가동. 만성기 환자 장기 입원 용이."
    },
    {
        "id": "21",
        "district": "안양시",
        "name": "하늘빛재활의학병원",
        "type": "병원",
        "inclusion": "특화 재활 / 중추신경재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "뇌졸중, 척수손상, 뇌성마비, 근골격계 통증 재활",
        "specialty": "안양 지역 거점 재활 전문병원",
        "recovery": "해당없음",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 안양시 동안구 경수대로 887 (비산동)",
        "phone": "031-451-0090",
        "sources": "http://skyrehab.co.kr",
        "verification": "HIRA/홈페이지 확인",
        "notes": "안양 비산동 위치. 재활의학과 전문의 및 임상 경험이 풍부한 치료사들이 배치되어 중추신경계 손상 환자들에게 체계적 입원 치료를 제공하는 지역 거점 병원."
    },
    {
        "id": "22",
        "district": "용인시",
        "name": "경기도립노인전문용인병원",
        "type": "요양병원",
        "inclusion": "도립 공공요양병원 / 노인재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/완화재활",
        "conditions": "치매, 파킨슨병, 노인성 뇌신경 질환, 와상환자 간호",
        "specialty": "경기도 설립 공공 의료기관 / 치매안심병원",
        "recovery": "해당없음",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 용인시 기흥구 중부대로 940 (상하동)",
        "phone": "031-288-0400",
        "sources": "https://www.hira.or.kr",
        "verification": "경기도/HIRA 확인",
        "notes": "경기도가 설립하여 공공 의료를 제공하는 도립 노인전문병원. 치매 집중 치료 및 만성기 노인 환자를 위한 생활 밀착형 유지 재활 프로그램 제공."
    },
    {
        "id": "23",
        "district": "여주시",
        "name": "경기도립노인전문여주병원",
        "type": "요양병원",
        "inclusion": "도립 공공요양병원 / 노인재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/완화재활",
        "conditions": "뇌졸중 후유증, 파킨슨병, 만성 노인성 질환",
        "specialty": "경기도 설립 공공 의료기관 / 노인 적정성 우수",
        "recovery": "해당없음",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 여주시 북내면 도예로 361-14",
        "phone": "031-886-4100",
        "sources": "https://www.hira.or.kr",
        "verification": "경기도/HIRA 확인",
        "notes": "여주 지역 공공 노인 의료 체계의 중추. 치매 및 고령 만성 질환 환자의 장기 케어와 근력 유지 중심의 온화한 물리치료/작업치료 지원."
    },
    {
        "id": "24",
        "district": "평택시",
        "name": "경기도립노인전문평택병원",
        "type": "요양병원",
        "inclusion": "도립 공공요양병원 / 노인재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/완화재활",
        "conditions": "뇌경색/뇌출혈 마비, 노인성 퇴행성 질환",
        "specialty": "경기도 설립 공공 의료기관",
        "recovery": "해당없음",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 평택시 브레인시티로 89 (도일동)",
        "phone": "031-669-9988",
        "sources": "https://www.hira.or.kr",
        "verification": "경기도/HIRA 확인",
        "notes": "평택 및 인근 경기 남부 지역 공립 요양 의료기관. 정기적인 전문의 진단을 바탕으로 인지 재활 및 물리적 관절 가동성 유지 재활을 충실히 수행."
    },
    {
        "id": "25",
        "district": "시흥시",
        "name": "경기도립노인전문시흥병원",
        "type": "요양병원",
        "inclusion": "도립 공공요양병원 / 노인재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/완화재활",
        "conditions": "치매, 뇌신경계 마비 질환, 노화 기능 저하",
        "specialty": "경기도 설립 공공 의료기관 / 적정성 평가 우수",
        "recovery": "해당없음",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 시흥시 하중로 285 (광석동)",
        "phone": "031-500-7100",
        "sources": "https://www.hira.or.kr",
        "verification": "경기도/HIRA 확인",
        "notes": "시흥시 및 안산 서부권 공립 요양 의료 인프라. 전문적인 치매 케어 안심 병동과 더불어 잔존 기능 극대화를 목표로 하는 노인 특화 재활치료 진행."
    },
    {
        "id": "26",
        "district": "남양주시",
        "name": "경기도립노인전문남양주병원",
        "type": "요양병원",
        "inclusion": "도립 공공요양병원 / 노인재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/완화재활",
        "conditions": "치매, 노인성 질환, 중풍 마비, 욕창 케어",
        "specialty": "경기도 설립 공공 의료기관 / 안심 케어",
        "recovery": "해당없음",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 남양주시 수동면 외방로172번길 32",
        "phone": "031-590-5000",
        "sources": "http://www.gngh.or.kr",
        "verification": "경기도/HIRA 확인",
        "notes": "남양주 수동면에 위치한 공립 요양병원. 청정 환경 속에서 중풍/마비 환자 대상의 온열 물리치료 및 구축 예방용 관절 가동 재활을 장기적으로 운영."
    },
    {
        "id": "27",
        "district": "동두천시",
        "name": "경기도립노인전문동두천병원",
        "type": "요양병원",
        "inclusion": "도립 공공요양병원 / 노인재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/완화재활",
        "conditions": "만성 노인성 질환, 노인 치매 케어, 관절 구축",
        "specialty": "경기도 설립 공공 의료기관",
        "recovery": "해당없음",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 동두천시 탑신로 536 (탑동동)",
        "phone": "031-860-4114",
        "sources": "http://www.gdsilver.co.kr",
        "verification": "경기도/HIRA 확인",
        "notes": "동두천 및 연천, 양주 등 경기 극북부 공립 요양 거점. 쾌적한 의료 환경 속에서 거동이 불편한 고령 환자들의 욕창 방지 및 수동식 물리치료 재활 병동 운영."
    },
    {
        "id": "28",
        "district": "남양주시",
        "name": "매그너스요양병원",
        "type": "요양병원",
        "inclusion": "재활요양 / 로봇 재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/입원재활",
        "conditions": "뇌졸중, 척수손상, 파킨슨병, 로봇 재활 치료",
        "specialty": "로봇 보행 재활기 도입 및 암재활 병동",
        "recovery": "해당없음",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 남양주시 수동면 지둔로445번길 33-51",
        "phone": "031-595-0600",
        "sources": "http://www.magnushospital.co.kr",
        "verification": "HIRA/홈페이지 확인",
        "notes": "남양주 친환경 수동 권역에 위치하며, 요양병원 급 최초 수준의 로봇 보행 치료기 도입. 뇌신경계 마비 환자용 집중 물리치료 및 작업치료 특화."
    },
    {
        "id": "29",
        "district": "김포시",
        "name": "김포서울대효요양병원",
        "type": "요양병원",
        "inclusion": "재활요양 / 양한방 협진",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/입원재활",
        "conditions": "뇌경색, 뇌출혈, 파킨슨병, 척추/관절 수술 후 재활",
        "specialty": "서울대효병원 네트워크 / 양한방 협진",
        "recovery": "해당없음",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 김포시 고촌읍 장차로5번길 5-17 (중원빌딩)",
        "phone": "031-988-8275",
        "sources": "http://www.seouldhp.co.kr",
        "verification": "HIRA/홈페이지 확인",
        "notes": "김포 고촌읍 소재. 서울대학교 의과대학 동문 협력 병원으로, 뇌신경계 질환 환자 맞춤형 양한방 통합 재활 치료 프로그램을 주도적으로 제공함."
    },
    {
        "id": "30",
        "district": "김포시",
        "name": "김포다올요양병원",
        "type": "요양병원",
        "inclusion": "재활요양 / 중증재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/입원재활",
        "conditions": "뇌졸중 후유장애, 척수손상, 수술 후 회복 재활",
        "specialty": "중증 환자 전용 집중재활 및 투석 연계",
        "recovery": "해당없음",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 김포시 김포한강10로133번길 67 (구래동)",
        "phone": "031-989-7587",
        "sources": "http://www.daolhospital.com",
        "verification": "HIRA/홈페이지 확인",
        "notes": "김포 구래동 한강신도시에 위치. 넓은 운동 치료 공간에서 환자 잔존 기능 수준별 작업 치료와 마비 근육 자극용 특수 물리 치료 제공."
    },
    {
        "id": "31",
        "district": "화성시",
        "name": "삼성진재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 의원 / 통증재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "뇌신경 재활, 근골격계 통증, 체외충격파, 도수치료",
        "specialty": "동탄 재활 및 통증 도수치료 특화",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 화성시 동탄중심상가2길 32, 3층",
        "phone": "031-613-9985",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "화성 동탄 신도시에 위치한 재활의학과 의원. 근골격계 통증 치료 및 1:1 맞춤 도수치료, 스포츠 재활 프로그램 운영."
    },
    {
        "id": "32",
        "district": "화성시",
        "name": "화성제일병원",
        "type": "병원",
        "inclusion": "종합재활치료 / 입원재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 근골격계 재활",
        "specialty": "성인재활센터 운영",
        "recovery": "해당없음",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 화성시 팔탄면 온천로 29",
        "phone": "031-370-0010",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "화성시 팔탄면에 위치하며, 성인재활센터를 통해 중추신경계 손상 환자 대상의 1:1 맞춤 재활치료와 입원 병실을 함께 지원."
    },
    {
        "id": "33",
        "district": "평택시",
        "name": "연세재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 의원 / 소아재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "소아발달지연, 근골격계 재활, 도수치료",
        "specialty": "평택역 인근 재활의학과 전문 진료",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 평택시 평택로 41 (평택동)",
        "phone": "031-656-5111",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "평택역 인근에 위치하며 소아 발달 및 뇌성마비 재활, 성인 근골격계 통증 도수치료를 전문 진료하는 의원."
    },
    {
        "id": "34",
        "district": "파주시",
        "name": "김재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "근골격계 통증, 자세교정, 도수치료",
        "specialty": "파주 금촌동 재활의학과 전문의 진료",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 파주시 시청로 25, 506호 (금촌동, 광우프라자)",
        "phone": "031-941-1554",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "파주 시청 인근 금촌동에 위치하여 척추·골반 교정 및 만성 근골격계 통증, 비수술적 재활치료 전문 의원."
    },
    {
        "id": "35",
        "district": "광명시",
        "name": "김상윤재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "척추관절 통증, 도수치료, 스포츠 재활",
        "specialty": "광명사거리역 재활의학과 전문의 진료",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 광명시 오리로 947, 401호 (광명동)",
        "phone": "02-2060-2585",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "광명동 광명사거리역 위치. 자세 교정 및 스포츠 손상 재활, 만성 관절 통증의 비수술적 도수/물리치료 제공."
    },
    {
        "id": "36",
        "district": "군포시",
        "name": "차재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 / 입원실 보유",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활/입원재활",
        "conditions": "뇌신경 마비재활, 척추디스크, 수술 후 통증재활",
        "specialty": "산본동 입원실 보유 재활의학과의원",
        "recovery": "해당없음",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 군포시 금산로 104, 2~5층 (산본동, 태영빌딩)",
        "phone": "031-392-4573",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "군포 산본동에 위치하며, 일반 외래 통증치료뿐 아니라 중추신경계 환자를 위한 입원 및 집중 재활치료실을 동시 가동하는 특화 의원."
    },
    {
        "id": "37",
        "district": "하남시",
        "name": "하남재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "오십견, 디스크, 도수/물리치료, 관절염",
        "specialty": "하남 신장동 재활의학과 전문의 진료",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 하남시 신평로 57, 2층 (신장동)",
        "phone": "031-792-7975",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "하남시 신장동에 위치한 정통 재활의학 진료 의원. 1:1 도수치료 및 비수술적 통증 완화 물리치료 시스템 구축."
    },
    {
        "id": "38",
        "district": "이천시",
        "name": "이천엘리야병원",
        "type": "병원",
        "inclusion": "종합재활 / 지역 거점 병원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "뇌졸중, 척수손상, 정형외과 수술 후 재활, 도수치료",
        "specialty": "이천 남부권 거점 병원 / 재활의학과 전문의 진료",
        "recovery": "해당없음",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 이천시 장호원읍 서동대로 8793",
        "phone": "1800-4275",
        "sources": "http://elijahhospital.com/",
        "verification": "HIRA/홈페이지 확인",
        "notes": "이천시 장호원읍에 위치한 거점 병원으로, 정형외과/재활의학과 협진을 기반으로 급성기 치료 후 입원 재활과 통원 도수치료를 원스톱 지원."
    },
    {
        "id": "39",
        "district": "포천시",
        "name": "포천 진요양병원",
        "type": "요양병원",
        "inclusion": "재활요양 / 장기 요양케어",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/완화재활",
        "conditions": "노인성 뇌신경 질환, 파킨슨병, 중풍 후유증 재활",
        "specialty": "포천 지역 집중 재활요양",
        "recovery": "해당없음",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 포천시 소흘읍 호국로 515",
        "phone": "031-544-7701",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "포천 소흘읍에 위치한 요양병원. 노인성 중풍, 치매, 파킨슨 환자를 위한 장기 요양 간호 서비스와 일상생활 가동성 유지 목적 of 물리재활치료실 운영."
    },
    {
        "id": "40",
        "district": "안성시",
        "name": "고려재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "척추디스크, 오십견, 체형교정, 도수치료",
        "specialty": "안성 석정동 재활의학과 전문 진료",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 안성시 중앙로 370, 204~205호 (석정동, 하평플리스)",
        "phone": "031-676-9152",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "안성시 석정동 중심가에 위치하여 지역 주민들의 척추·관절 질환 비수술적 재활 및 체형 교정 도수치료를 주로 진료하는 의원."
    },
    {
        "id": "41",
        "district": "양주시",
        "name": "한양연합재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "근골격계 질환, 비수술 관절 치료, 도수치료",
        "specialty": "양주 남면 재활의학과 전문의 진료",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 양주시 남면 개나리길 37, 1층",
        "phone": "031-867-7582",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "양주시 남면에 위치하여 농·어촌 지역 주민의 만성 퇴행성 관절염, 디스크 등 비수술적 통증 주사 및 물리치료를 전담하는 안심 의원."
    },
    {
        "id": "42",
        "district": "의왕시",
        "name": "예스재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "척추 신경차단술, 도수치료, 만성 통증 재활",
        "specialty": "의왕 포일동 재활의학과 전문의 진료",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 의왕시 포일세거리로 3, 404호 (포일동, 파레사타워)",
        "phone": "031-423-8875",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "의왕 포일동 인근 아파트 단지 상가에 위치하며 디스크 신경 차단술 및 1:1 맞춤형 척추관절 도수재활 치료 전문 의원."
    },
    {
        "id": "43",
        "district": "가평군",
        "name": "강변요양병원",
        "type": "요양병원",
        "inclusion": "재활요양 / 자연 친화 케어",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양입원/완화재활",
        "conditions": "노인성 질환, 뇌졸중 후유재활, 근력 유지 물리치료",
        "specialty": "북한강변 자연 속 재활요양",
        "recovery": "해당없음",
        "workersComp": "일반지정",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 가평군 가평읍 북한강변로 160",
        "phone": "031-582-8858",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "가평읍 북한강변에 위치하여 쾌적한 자연환경 속에서 만성 노인성 질환 환자들의 욕창 간호와 관절 구축 방지 물리치료를 병행하는 요양병원."
    },
    {
        "id": "44",
        "district": "연천군",
        "name": "연천군보건의료원",
        "type": "병원",
        "inclusion": "공공 보건의료원 / 물리치료",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "근골격계 통증, 퇴행성 관절염, 물리치료",
        "specialty": "공공 물리치료실 및 한방진료실 연계",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "경기도 연천군 전곡읍 평화로 693",
        "phone": "031-839-4000",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "연천군 전곡읍에 위치한 공공 보건의료기관. 연천 관내 주민들을 위한 외래 중심의 물리치료실 및 근골격계 통증 재활 클리닉을 활발히 운영."
    }
];
