window.REHAB_DATA = [
    {
        "id":  "1",
        "district":  "중구",
        "name":  "경북대학교병원",
        "type":  "상급종합병원",
        "inclusion":  "재활의학과 보유 상급종합병원",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "급성기/외래·입원 재활",
        "conditions":  "뇌졸중, 뇌손상, 척수손상, 근골격계 수술 후 재활",
        "specialty":  "상급종합병원 재활의학과",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "외래/입원 중심",
        "address":  "대구광역시 중구 동덕로 130",
        "phone":  "1666-0114",
        "sources":  "https://www.knuh.kr/index.asp",
        "verification":  "공식 홈페이지 확인",
        "notes":  "5기 상급종합병원(경북권역). 재활의학과 진료과 존재 확인. 전문의 수/산재 여부 전화 확인 필요"
    },
    {
        "id":  "2",
        "district":  "중구",
        "name":  "계명대학교 대구동산병원",
        "type":  "종합병원",
        "inclusion":  "재활의학과 보유 종합병원(2차병원)",
        "rehabDept":  "있음(2025.3 신설)",
        "specialists":  "확인필요",
        "careType":  "외래 중심(별관)",
        "conditions":  "대구광역시 공공어린이재활의료센터 연계, 소아재활 등",
        "specialty":  "공공어린이재활의료센터(별관) 운영",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 중구 달성로 56",
        "phone":  "053-250-8114",
        "sources":  "나무위키(계명대학교 대구동산병원)",
        "verification":  "위키/공식 확인",
        "notes":  "2025년 3월 재활의학과 신규 개설, 어린이재활의료센터 별관에서 진료. 성인 재활 범위 전화 확인 필요"
    },
    {
        "id":  "3",
        "district":  "중구",
        "name":  "남산병원",
        "type":  "병원",
        "inclusion":  "회복기 재활의료기관(제3기)+산재 재활인증",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "회복기/입원재활",
        "conditions":  "뇌졸중, 뇌손상 등 중추신경계 회복기 재활",
        "specialty":  "보건복지부 제3기 회복기 재활의료기관",
        "recovery":  "지정(제1~3기 연속)",
        "workersComp":  "근로복지공단 재활인증의료기관",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 중구 남산로13길 9",
        "phone":  "053-250-1100",
        "sources":  "의학신문(제3기 재활의료기관 명단)/근로복지공단 재활인증 현황",
        "verification":  "언론보도/공단 확인",
        "notes":  "회복기 재활의료기관. 산재 재활인증 여부는 공단 현황에서 재확인 필요"
    },
    {
        "id":  "4",
        "district":  "동구",
        "name":  "대구파티마병원",
        "type":  "종합병원",
        "inclusion":  "재활의학과 보유 종합병원",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "외래/입원 재활",
        "conditions":  "뇌졸중, 근골격계 수술 후 재활 등",
        "specialty":  "종합병원 재활의학과",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 동구 아양로 99 (신암동)",
        "phone":  "1688-7770",
        "sources":  "https://www.fatima.or.kr/",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "재활의학과 진료과 개설 확인. 상세주소·전문의 수 전화 확인 필요"
    },
    {
        "id":  "5",
        "district":  "동구",
        "name":  "대구한의대학교부속 대구한방병원",
        "type":  "한방병원",
        "inclusion":  "한방재활의학과+재활의학과(한·양방 협진)",
        "rehabDept":  "해당없음(한방재활의학과 별도 운영)",
        "specialists":  "확인필요",
        "careType":  "외래 한방재활+양방 재활의학과",
        "conditions":  "중풍재활, 척추·관절질환, 안면마비, 추나요법 등",
        "specialty":  "한방재활의학과/중풍재활·순환신경센터",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 동구 혁신대로 430",
        "phone":  "053-770-2000",
        "sources":  "https://daegu.dhu.ac.kr/",
        "verification":  "공식 홈페이지 확인",
        "notes":  "대구·경북 유일 대학 한방병원. 2024.10 수성구 상동에서 동구 혁신도시로 이전. 한방재활의학과·재활의학과 모두 진료과 개설"
    },
    {
        "id":  "6",
        "district":  "동구",
        "name":  "수월한방병원(동구점)",
        "type":  "한의원/한방병원",
        "inclusion":  "한방재활의학과 전문의 보유",
        "rehabDept":  "해당없음",
        "specialists":  "한방재활의학과 전문의 1명 이상",
        "careType":  "외래 한방재활",
        "conditions":  "척추·관절 통증, 교통사고 후유증, 수술 후 재활",
        "specialty":  "한방재활의학과",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "대구광역시 동구 안심로 358, 2~4층 (동호동)",
        "phone":  "053-957-5000",
        "sources":  "https://suwol.kr/",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "한방재활의학과 전문의 진료 확인. 상세주소·전화 전화확인 필요"
    },
    {
        "id":  "7",
        "district":  "서구",
        "name":  "대구의료원",
        "type":  "종합병원(공공)",
        "inclusion":  "재활의학과 보유 공공병원",
        "rehabDept":  "있음(HIRA)",
        "specialists":  "확인필요",
        "careType":  "외래/입원 재활",
        "conditions":  "뇌졸중, 근골격계 등 지역 공공재활",
        "specialty":  "대구서남권 책임의료기관",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 서구 평리로 157",
        "phone":  "053-560-7575",
        "sources":  "HIRA 병원정보(hospInfoAjax)",
        "verification":  "HIRA 확인",
        "notes":  "대구서남권 책임의료기관으로 지정. HIRA상 재활의학과 확인"
    },
    {
        "id":  "8",
        "district":  "서구",
        "name":  "대구제이병원",
        "type":  "병원",
        "inclusion":  "재활치료 전문병원(요양병원 아님을 표방)",
        "rehabDept":  "확인필요",
        "specialists":  "확인필요",
        "careType":  "입원재활/외래재활",
        "conditions":  "근골격계·신경계 재활치료",
        "specialty":  "재활전문병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 서구 달구벌대로 1677",
        "phone":  "053-571-6000",
        "sources":  "http://www.j-hospital.com/",
        "verification":  "공식 홈페이지 확인",
        "notes":  "\"요양병원이 아닌 재활치료 병원\"으로 소개. 재활의학과 전문의 수 전화 확인 필요"
    },
    {
        "id":  "9",
        "district":  "서구",
        "name":  "대구광역시서부노인전문병원",
        "type":  "요양병원(공공)",
        "inclusion":  "요양재활/뇌졸중·치매 재활치료 후보",
        "rehabDept":  "확인필요",
        "specialists":  "확인필요",
        "careType":  "입원재활/요양재활",
        "conditions":  "뇌졸중, 치매, 노인성 질환 재활치료",
        "specialty":  "공립 노인전문병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 서구 와룡로 298-13 (중리동)",
        "phone":  "053-570-7600",
        "sources":  "Daum 팁(dgsbgh.daegumc.co.kr 인용)",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "대구의료원 계열 공립 요양병원으로 추정. 전화 확인 필요"
    },
    {
        "id":  "10",
        "district":  "남구",
        "name":  "영남대학교병원",
        "type":  "상급종합병원",
        "inclusion":  "재활의학과 보유 상급종합병원",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "급성기/외래·입원 재활",
        "conditions":  "뇌졸중, 척수손상, 근골격계 수술 후 재활",
        "specialty":  "상급종합병원 재활의학과",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 남구 현충로 170",
        "phone":  "1522-3114",
        "sources":  "위키백과(영남대학교병원)/공식 홈페이지",
        "verification":  "위키/공식 확인",
        "notes":  "5기 상급종합병원(경북권역). 재활의학과 전문의 수 전화 확인 필요"
    },
    {
        "id":  "11",
        "district":  "남구",
        "name":  "대구가톨릭대학교병원",
        "type":  "상급종합병원",
        "inclusion":  "재활의학과 보유 상급종합병원",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "급성기/외래·입원 재활",
        "conditions":  "뇌졸중, 척수손상, 근골격계 수술 후 재활",
        "specialty":  "상급종합병원 재활의학과",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 남구 두류공원로17길 33",
        "phone":  "1688-0077",
        "sources":  "https://www.dcmc.co.kr/",
        "verification":  "공식 홈페이지 확인",
        "notes":  "5기 상급종합병원(경북권역). 재활의학과 전문의 수 전화 확인 필요"
    },
    {
        "id":  "12",
        "district":  "남구",
        "name":  "대구대학교 재활의원",
        "type":  "의원(대학부속)",
        "inclusion":  "재활의학과 전문 의원",
        "rehabDept":  "있음",
        "specialists":  "재활의학과 전문의(정확한 인원 확인필요)",
        "careType":  "외래 중심",
        "conditions":  "소아재활(뇌성마비, 발달장애), 성인재활(중풍, 척추손상)",
        "specialty":  "대학부속 재활의원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "대구광역시 남구 명덕로8길 70 (대명동)",
        "phone":  "053-650-8080",
        "sources":  "https://durc.daegu.ac.kr/",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "물리치료사 9명, 작업치료사 6명, 언어치료사 2명 확인(홈페이지). 소아·성인 재활 모두 진료"
    },
    {
        "id":  "13",
        "district":  "남구",
        "name":  "경대연합재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 외래",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "외래 중심",
        "conditions":  "근골격계 통증, 물리치료",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "대구광역시 남구 성당로 184",
        "phone":  "053-624-7100",
        "sources":  "하이닥 병원정보",
        "verification":  "하이닥 확인",
        "notes":  "진료과목 재활의학과 확인. 전문의 수 전화 확인 필요"
    },
    {
        "id":  "14",
        "district":  "남구",
        "name":  "대구요양병원",
        "type":  "요양병원",
        "inclusion":  "요양재활 후보",
        "rehabDept":  "확인필요",
        "specialists":  "확인필요",
        "careType":  "입원재활/요양재활",
        "conditions":  "노인성 질환, 장기요양",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 남구 현충로184",
        "phone":  "053-625-3000",
        "sources":  "http://www.dgtsh.co.kr/",
        "verification":  "후보/전화확인",
        "notes":  "재활의학과 전문의 여부·물리치료실 규모 전화 확인 필요"
    },
    {
        "id":  "15",
        "district":  "남구",
        "name":  "뉴영대요양병원",
        "type":  "요양병원",
        "inclusion":  "요양재활 후보",
        "rehabDept":  "확인필요",
        "specialists":  "확인필요",
        "careType":  "입원재활/요양재활",
        "conditions":  "노인성 질환, 장기요양",
        "specialty":  "요양병원(영남대병원 인근)",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 남구 대명로 275",
        "phone":  "053-215-0119",
        "sources":  "http://www.nydshospital.com/",
        "verification":  "후보/전화확인",
        "notes":  "영남대병원 인근 위치. 재활치료 프로그램 전화 확인 필요"
    },
    {
        "id":  "16",
        "district":  "북구",
        "name":  "칠곡경북대학교병원",
        "type":  "상급종합병원",
        "inclusion":  "재활의학과 보유+산재 재활인증",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "급성기/외래·입원 재활",
        "conditions":  "뇌졸중, 척수손상 등",
        "specialty":  "상급종합병원 재활의학과/산재 재활인증의료기관",
        "recovery":  "해당없음",
        "workersComp":  "근로복지공단 재활인증의료기관",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 북구 호국로 807",
        "phone":  "053-200-2064",
        "sources":  "근로복지공단 재활인증의료기관 현황(대구북부지사)",
        "verification":  "공단 확인",
        "notes":  "산재 재활인증의료기관 명단 대구북부지사 확인"
    },
    {
        "id":  "17",
        "district":  "북구",
        "name":  "대구가톨릭대학교 칠곡가톨릭병원",
        "type":  "종합병원",
        "inclusion":  "재활의학과 보유 종합병원 후보",
        "rehabDept":  "확인필요",
        "specialists":  "확인필요",
        "careType":  "외래/입원 재활 후보",
        "conditions":  "근골격계, 뇌혈관질환 후보",
        "specialty":  "종합병원 후보",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 북구 칠곡중앙대로 440 (읍내동)",
        "phone":  "053-320-2500",
        "sources":  "http://www.tcmcch.co.kr/",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "재활의학과 개설 여부 및 전문의 수 전화 확인 필요"
    },
    {
        "id":  "18",
        "district":  "북구",
        "name":  "근로복지공단 대구병원",
        "type":  "병원(공단 직영)",
        "inclusion":  "산재 재활 전문(로봇재활·수중재활·운전재활)",
        "rehabDept":  "있음(다수)",
        "specialists":  "확인필요",
        "careType":  "입원재활/외래재활",
        "conditions":  "산재근로자 재활, 로봇재활, 운전재활",
        "specialty":  "근로복지공단 소속 재활전문병원",
        "recovery":  "해당없음",
        "workersComp":  "근로복지공단 소속(산재보험 적용)",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 북구 학정로 515",
        "phone":  "053-715-7773",
        "sources":  "메디우스/근로복지공단",
        "verification":  "공식/공단 확인",
        "notes":  "근로복지공단 직영 산재 재활전문병원. 공단 현황 전화번호 반영"
    },
    {
        "id":  "19",
        "district":  "북구",
        "name":  "대구보건대학교병원",
        "type":  "병원",
        "inclusion":  "회복기 재활의료기관(제3기)+산재 재활인증",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "회복기/입원재활",
        "conditions":  "뇌졸중, 뇌손상, 척수손상 등 회복기 재활",
        "specialty":  "보건복지부 제3기 회복기 재활의료기관",
        "recovery":  "지정",
        "workersComp":  "근로복지공단 재활인증의료기관",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 북구 팔거천동로 209",
        "phone":  "053-320-1909",
        "sources":  "의학신문(제3기 재활의료기관 명단)/근로복지공단 재활인증 현황",
        "verification":  "언론보도/공단 확인",
        "notes":  "회복기+산재 재활인증 중복 핵심기관. 공단 현황 전화번호 반영"
    },
    {
        "id":  "20",
        "district":  "북구",
        "name":  "케이병원",
        "type":  "병원",
        "inclusion":  "회복기 재활의료기관(제3기)+산재 재활인증",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "회복기/입원재활",
        "conditions":  "뇌졸중, 뇌손상 등 회복기 재활",
        "specialty":  "보건복지부 제3기 회복기 재활의료기관",
        "recovery":  "지정",
        "workersComp":  "근로복지공단 재활인증의료기관",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 북구 칠곡중앙대로 357",
        "phone":  "053-310-7114",
        "sources":  "의학신문(제3기 재활의료기관 명단)/근로복지공단 재활인증 현황",
        "verification":  "언론보도/공단 확인",
        "notes":  "회복기+산재 재활인증 중복 핵심기관. 공단 현황 전화번호 반영"
    },
    {
        "id":  "21",
        "district":  "북구",
        "name":  "미래병원",
        "type":  "병원",
        "inclusion":  "회복기 재활의료기관(제3기)+산재 재활인증",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "회복기/입원재활",
        "conditions":  "뇌졸중, 뇌손상 등 회복기 재활",
        "specialty":  "보건복지부 제3기 회복기 재활의료기관",
        "recovery":  "지정",
        "workersComp":  "근로복지공단 재활인증의료기관",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 북구 신암로 55",
        "phone":  "053-259-8800",
        "sources":  "의학신문(제3기 재활의료기관 명단)/근로복지공단 재활인증 현황",
        "verification":  "언론보도/공단 확인",
        "notes":  "회복기+산재 재활인증 중복 핵심기관. 공단 현황 전화번호 반영"
    },
    {
        "id":  "22",
        "district":  "북구",
        "name":  "영대연합재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 외래",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "외래 중심",
        "conditions":  "척추통증, 어깨통증, 오십견, 신경통증, 두통",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "대구광역시 북구 침산남로 140, MB플라자 3층",
        "phone":  "053-353-9698",
        "sources":  "Daum 팁(pamfreeclinic.com 인용)",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "상세주소·전화 전화확인 필요"
    },
    {
        "id":  "23",
        "district":  "북구",
        "name":  "대구박병원",
        "type":  "병원",
        "inclusion":  "정형외과 재활치료센터 후보",
        "rehabDept":  "확인필요",
        "specialists":  "확인필요",
        "careType":  "외래 중심",
        "conditions":  "인공관절·척추 수술 후 재활, 스포츠재활, 관절경 후 재활",
        "specialty":  "정형외과/재활치료센터",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "대구광역시 북구 대학로 143 (산격동)",
        "phone":  "053-957-0075",
        "sources":  "Daum 팁(parkhospital.co.kr 인용)",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "재활의학과 전문의 여부 전화 확인 필요"
    },
    {
        "id":  "24",
        "district":  "북구",
        "name":  "뉴라이프병원",
        "type":  "병원",
        "inclusion":  "재활/가정의학과/정형외과 후보",
        "rehabDept":  "확인필요",
        "specialists":  "확인필요",
        "careType":  "외래/입원 후보",
        "conditions":  "근골격계 재활 후보",
        "specialty":  "재활 후보",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 북구 공항로 15 (복현동)",
        "phone":  "053-384-9119",
        "sources":  "Daum 팁(newlife9119.co.kr 인용)",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "재활의학과 전문의 여부 전화 확인 필요"
    },
    {
        "id":  "25",
        "district":  "수성구",
        "name":  "더좋은병원",
        "type":  "병원",
        "inclusion":  "회복기 재활의료기관(제3기, 수성구 유일)+산재 재활인증",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "회복기/입원재활+로봇재활",
        "conditions":  "뇌졸중, 중추신경계 재활, 로봇재활치료",
        "specialty":  "보건복지부 제3기 회복기 재활의료기관/한국로봇산업진흥원 국책사업 선정",
        "recovery":  "지정(수성구 유일)",
        "workersComp":  "근로복지공단 재활인증의료기관",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 수성구 명덕로 443 (수성동3가)",
        "phone":  "053-740-1000",
        "sources":  "의학신문/양파티브이뉴스/근로복지공단 재활인증 현황",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "수성구 유일 회복기 재활의료기관지정병원. 간호간병통합병동 3개 운영(언론보도)"
    },
    {
        "id":  "26",
        "district":  "달서구",
        "name":  "계명대학교 동산병원",
        "type":  "상급종합병원",
        "inclusion":  "재활의학과 보유+산재 재활인증",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "급성기/외래·입원 재활",
        "conditions":  "뇌졸중, 척수손상 등",
        "specialty":  "상급종합병원 재활의학과/산재 재활인증의료기관",
        "recovery":  "해당없음",
        "workersComp":  "근로복지공단 재활인증의료기관",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 달서구 달구벌대로 1035 (신당동)",
        "phone":  "1577-6622",
        "sources":  "위키백과(계명대학교 동산병원)/근로복지공단 재활인증 현황",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "2019년 신당동 이전, 대구경북권 최대 규모 상급종합병원(930병상)"
    },
    {
        "id":  "27",
        "district":  "달서구",
        "name":  "대구경상병원",
        "type":  "병원",
        "inclusion":  "회복기 재활의료기관(제3기)",
        "rehabDept":  "있음(홈페이지 의료진 확인)",
        "specialists":  "3명 이상(홈페이지 기준)",
        "careType":  "회복기/입원재활",
        "conditions":  "뇌졸중 후유증, 중추신경계 재활, 혈액투석·인공신장실 병행",
        "specialty":  "보건복지부 제3기 회복기 재활의료기관",
        "recovery":  "지정",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 달서구 달구벌대로 1762",
        "phone":  "053-620-7339",
        "sources":  "의학신문(제3기 재활의료기관 명단)/공식 홈페이지(의료진)",
        "verification":  "언론보도/공식 확인",
        "notes":  "재활의학과 전문의 3명 이상 홈페이지에서 확인(김영현·이소현·양호철 등)"
    },
    {
        "id":  "28",
        "district":  "달서구",
        "name":  "더나은병원",
        "type":  "병원",
        "inclusion":  "산재 재활인증",
        "rehabDept":  "확인필요",
        "specialists":  "확인필요",
        "careType":  "입원재활/외래재활 후보",
        "conditions":  "근골격계·신경계 재활 후보",
        "specialty":  "근로복지공단 재활인증의료기관",
        "recovery":  "해당없음",
        "workersComp":  "근로복지공단 재활인증의료기관",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 달서구 달구벌대로 1576",
        "phone":  "053-563-1000",
        "sources":  "근로복지공단 재활인증의료기관 현황(대구서부지사)",
        "verification":  "공단 확인",
        "notes":  "산재 재활인증의료기관. 재활의학과 전문의 수 HIRA/전화 확인 필요"
    },
    {
        "id":  "29",
        "district":  "달서구",
        "name":  "해성병원",
        "type":  "병원",
        "inclusion":  "산재 재활인증",
        "rehabDept":  "확인필요",
        "specialists":  "확인필요",
        "careType":  "입원재활/외래재활 후보",
        "conditions":  "근골격계·신경계 재활 후보",
        "specialty":  "근로복지공단 재활인증의료기관",
        "recovery":  "해당없음",
        "workersComp":  "근로복지공단 재활인증의료기관",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 달서구 계대동문로 96 (이곡동)",
        "phone":  "053-760-1000",
        "sources":  "근로복지공단 재활인증의료기관 현황(대구서부지사)",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "재활의학과 전문의 수 전화 확인 필요"
    },
    {
        "id":  "30",
        "district":  "중구",
        "name":  "더채움재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 의원 후보",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "외래 중심",
        "conditions":  "근골격계 통증, 도수·물리치료, 초음파 등",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "대구광역시 중구 달구벌대로 2094, 901호 (남산동)",
        "phone":  "053-423-3105",
        "sources":  "https://my-doctor.io/dept-hub/%EC%9E%AC%ED%99%9C%EC%9D%98%ED%95%99%EA%B3%BC/%EB%8C%80%EA%B5%AC",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "기존 원본 누락. 대구 재활의학과 목록에 확인되어 추가"
    },
    {
        "id":  "31",
        "district":  "중구",
        "name":  "닥터굿재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 의원 후보",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "외래 중심",
        "conditions":  "근골격계 통증, 물리치료 후보",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "대구광역시 중구 국채보상로 582, 미도빌딩 2층 (남일동)",
        "phone":  "053-210-1234",
        "sources":  "https://my-doctor.io/dept-hub/%EC%9E%AC%ED%99%9C%EC%9D%98%ED%95%99%EA%B3%BC/%EB%8C%80%EA%B5%AC",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "기존 원본 누락. 주소·전화 HIRA 재확인 필요"
    },
    {
        "id":  "32",
        "district":  "남구",
        "name":  "몸편한재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 의원",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "외래 중심",
        "conditions":  "근골격계 통증, 물리치료",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "대구광역시 남구 명덕로 66",
        "phone":  "053-621-0222",
        "sources":  "https://mobile.hidoc.co.kr/find/result/view/H0000162624",
        "verification":  "HIRA기반/전화확인",
        "notes":  "하이닥 병원정보상 HIRA 기반, 진료과목 재활의학과 확인"
    },
    {
        "id":  "33",
        "district":  "남구",
        "name":  "고은재활요양병원",
        "type":  "요양병원",
        "inclusion":  "재활요양 후보",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "입원재활/요양재활 후보",
        "conditions":  "신경계·노인성 질환 재활 후보",
        "specialty":  "요양병원/재활요양",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 남구 현충로 236, 2~6층 (대명동)",
        "phone":  "053-213-2300",
        "sources":  "https://my-doctor.io/dept-hub/%EC%9E%AC%ED%99%9C%EC%9D%98%ED%95%99%EA%B3%BC/%EB%8C%80%EA%B5%AC",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "재활의학과 진료과목 노출. HIRA 상세와 전화 확인 필요"
    },
    {
        "id":  "34",
        "district":  "동구",
        "name":  "등편한재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 의원",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "외래 중심",
        "conditions":  "척추·관절 통증, 물리치료",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "대구광역시 동구 동촌로 225 지상3층",
        "phone":  "053-985-0075",
        "sources":  "https://mobile.hidoc.co.kr/find/result/view/H0000161322",
        "verification":  "HIRA기반/전화확인",
        "notes":  "하이닥 병원정보상 HIRA 기반, 진료과목 재활의학과 확인"
    },
    {
        "id":  "35",
        "district":  "동구",
        "name":  "율하재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 의원",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "외래 중심",
        "conditions":  "근골격계 통증, 도수치료, 물리치료",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "대구광역시 동구 안심로22길 40-1, 5층",
        "phone":  "053-710-9975",
        "sources":  "https://medieus.com/sub_detail/hospital_detail.asp?hos_num=83920",
        "verification":  "보강/전화확인",
        "notes":  "메디우스 병원정보상 주소·전화 확인"
    },
    {
        "id":  "36",
        "district":  "동구",
        "name":  "동대구요양병원",
        "type":  "요양병원",
        "inclusion":  "요양재활 후보",
        "rehabDept":  "있음(진료과목)",
        "specialists":  "확인필요",
        "careType":  "입원재활/요양재활 후보",
        "conditions":  "노인성 질환, 신경계 재활 후보",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 동구 신암남로 159",
        "phone":  "053-957-7551",
        "sources":  "https://www.welfarehello.com/recommend-policy/situation/emergency/%EB%8F%99%EB%8C%80%EA%B5%AC%EC%9A%94%EC%96%91%EB%B3%91%EC%9B%90--15791",
        "verification":  "후보/전화확인",
        "notes":  "진료과목 재활의학과 노출. 전문의 수는 HIRA 재확인 필요"
    },
    {
        "id":  "37",
        "district":  "서구",
        "name":  "경대재활요양병원",
        "type":  "요양병원",
        "inclusion":  "재활요양/요양병원",
        "rehabDept":  "있음",
        "specialists":  "재활의학과 2명",
        "careType":  "입원재활/요양재활",
        "conditions":  "재활치료, 물리치료, 양한방협진",
        "specialty":  "요양병원/재활치료",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 서구 국채보상로 223, 대원빌딩 4~10층 (평리동)",
        "phone":  "053-262-2626",
        "sources":  "https://ddoga.co.kr/ltch/13/JDQ4MTYyMiM4MSMkMSMkMCMkOTkkNTgxMzUxIzIxIyQxIyQ1IyQ5MiQ0NjEwMDIjNDEjJDEjJDgjJDgz/W01",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "또가/공공데이터 기반 정보상 재활의학과 전문의 2명, 요양병원 평가 4등급"
    },
    {
        "id":  "38",
        "district":  "서구",
        "name":  "경북신경외과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 진료과목 보유 후보",
        "rehabDept":  "있음(진료과목)",
        "specialists":  "확인필요",
        "careType":  "외래 중심",
        "conditions":  "통증·근골격계 재활 후보",
        "specialty":  "신경외과/재활의학과 진료과목",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "대구광역시 서구 국채보상로 429, 2/4층 (비산동)",
        "phone":  "053-572-9222",
        "sources":  "https://my-doctor.io/dept-hub/%EC%9E%AC%ED%99%9C%EC%9D%98%ED%95%99%EA%B3%BC/%EB%8C%80%EA%B5%AC",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "재활의학과 전문의가 아닌 진료과목 보유 후보일 수 있어 HIRA 확인 필요"
    },
    {
        "id":  "39",
        "district":  "북구",
        "name":  "마디척재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 의원",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "외래 중심",
        "conditions":  "척추·관절 통증, 재활치료",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "대구광역시 북구 침산남로 155 1,4층",
        "phone":  "053-353-9698",
        "sources":  "https://medieus.com/sub_detail/hospital_detail.asp?hos_num=13497",
        "verification":  "보강/전화확인",
        "notes":  "메디우스 병원정보상 주소·전화 확인"
    },
    {
        "id":  "40",
        "district":  "북구",
        "name":  "참재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 의원",
        "rehabDept":  "있음",
        "specialists":  "전문의 1명",
        "careType":  "외래 중심",
        "conditions":  "척추·관절 통증, 물리치료",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "대구광역시 북구 침산로 168, 5층 502·503호",
        "phone":  "053-357-0033",
        "sources":  "https://widocs.com/finder/hospital/%EC%B0%B8%EC%9E%AC%ED%99%9C%EC%9D%98%ED%95%99%EA%B3%BC%EC%9D%98%EC%9B%90-%EB%8C%80%EA%B5%AC%EB%B6%81%EA%B5%AC/",
        "verification":  "보강/전화확인",
        "notes":  "의료진 1명/전문의 1명으로 노출. HIRA 재확인 필요"
    },
    {
        "id":  "41",
        "district":  "수성구",
        "name":  "닥터드림재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 의원",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "외래 중심",
        "conditions":  "근골격계 통증, 물리치료",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "대구 수성구 두산동/범어4동 권역",
        "phone":  "053-759-8275",
        "sources":  "https://www.footmed.or.kr/bbs/board.php?bo_table=s65\u0026sca=%EF%BF%BD%EB%B1%B8\u0026wr_id=25",
        "verification":  "보강/전화확인",
        "notes":  "재활의학과 전문의 의원으로 노출. 현 위치·주소 HIRA 확인 필요"
    },
    {
        "id":  "42",
        "district":  "수성구",
        "name":  "수성나무재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 의원",
        "rehabDept":  "있음",
        "specialists":  "재활의학과 전문의 1명",
        "careType":  "외래 중심",
        "conditions":  "근골격계 통증, 물리치료",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "대구 수성구 수성로 193 2층",
        "phone":  "053-766-1357",
        "sources":  "https://mobile.hidoc.co.kr/find/result/view/H0000239276",
        "verification":  "HIRA기반/전화확인",
        "notes":  "하이닥 병원정보상 HIRA 기반, 재활의학과 및 전문의 정보 확인"
    },
    {
        "id":  "43",
        "district":  "수성구",
        "name":  "신통재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 의원",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "외래 중심",
        "conditions":  "도수치료, 증식치료 등",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "대구광역시 수성구 지범로 202 (범물동)",
        "phone":  "053-784-9698",
        "sources":  "https://www.modoodoc.com/hospital/43394/%EC%8B%A0%ED%86%B5%EC%9E%AC%ED%99%9C%EC%9D%98%ED%95%99%EA%B3%BC%EC%9D%98%EC%9B%90-%EB%8C%80%EA%B5%AC-%EB%B2%94%EB%AC%BC%EB%8F%99",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "모두닥 병원정보 확인. 전화·전문의 수 HIRA 확인 필요"
    },
    {
        "id":  "44",
        "district":  "수성구",
        "name":  "김신요양병원",
        "type":  "요양병원",
        "inclusion":  "재활요양/요양병원",
        "rehabDept":  "있음",
        "specialists":  "재활의학과 1명",
        "careType":  "입원재활/요양재활",
        "conditions":  "노인성 질환, 신경계 질환, 재활치료",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 수성구 수성로 228 (중동)",
        "phone":  "053-766-5555",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkMCMkOTkkNTgxMzUxIzIxIyQxIyQ1IyQ4MiQzNjE0ODEjNTEjJDEjJDIjJDgz",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "HIRA 병원정보상 재활의학과 전문의 1명, 물리치료사 34명·작업치료사 19명 확인"
    },
    {
        "id":  "45",
        "district":  "수성구",
        "name":  "한패밀리요양병원",
        "type":  "요양병원",
        "inclusion":  "재활요양/요양병원",
        "rehabDept":  "있음",
        "specialists":  "재활의학과 1명",
        "careType":  "입원재활/요양재활",
        "conditions":  "도심형 요양/재활, 노인성 질환",
        "specialty":  "요양병원/재활병원 표방",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 수성구 지산동",
        "phone":  "053-763-2000",
        "sources":  "https://www.hanfamily.or.kr/introduction/overview.html",
        "verification":  "보강/전화확인",
        "notes":  "공식 홈페이지상 도심속 요양/재활병원 표기. 전문의 수는 보조 출처 기준으로 재확인 필요"
    },
    {
        "id":  "46",
        "district":  "수성구",
        "name":  "대구광역시시지노인전문병원",
        "type":  "요양병원(공공)",
        "inclusion":  "요양재활 후보",
        "rehabDept":  "있음",
        "specialists":  "재활의학과 전문의 후보",
        "careType":  "입원재활/요양재활",
        "conditions":  "노인성 질환, 치매, 재활치료 후보",
        "specialty":  "공립 노인전문병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 수성구 유니버시아드로 365 (욱수동)",
        "phone":  "053-819-2004",
        "sources":  "https://my-doctor.io/hospital/deptHub/list/region/%EC%9E%AC%ED%99%9C%EC%9D%98%ED%95%99%EA%B3%BC-%EC%A0%84%EC%B2%B4-%EB%8C%80%EA%B5%AC-%EC%88%98%EC%84%B1%EA%B5%AC",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "수성구 재활의학과 전체 목록에 노출. HIRA 상세 확인 필요"
    },
    {
        "id":  "47",
        "district":  "달서구",
        "name":  "척편한재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 의원",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "외래 중심",
        "conditions":  "척추·관절 통증, 도수/물리치료",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "대구광역시 달서구 월배로 168, 아보스타워 3층 (상인동)",
        "phone":  "053-633-7979",
        "sources":  "https://my-doctor.io/dept-hub/%EC%9E%AC%ED%99%9C%EC%9D%98%ED%95%99%EA%B3%BC/%EC%A0%84%EC%B2%B4%EB%B3%91%EC%9B%90/%EB%8C%80%EA%B5%AC-%EB%8B%AC%EC%84%9C%EA%B5%AC",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "달서구 재활의학과 목록에 확인되어 추가"
    },
    {
        "id":  "48",
        "district":  "달서구",
        "name":  "오상호재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 의원",
        "rehabDept":  "있음",
        "specialists":  "재활의학과 전문의 1명",
        "careType":  "외래 중심",
        "conditions":  "근골격계 통증, 물리치료",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "대구광역시 달서구 달구벌대로 1545, 골든뷰 메디타워 404호 (죽전동)",
        "phone":  "053-562-7582",
        "sources":  "https://my-doctor.io/dept-hub/%EC%9E%AC%ED%99%9C%EC%9D%98%ED%95%99%EA%B3%BC/%EC%A0%84%EC%B2%B4%EB%B3%91%EC%9B%90/%EB%8C%80%EA%B5%AC-%EB%8B%AC%EC%84%9C%EA%B5%AC",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "달서구 재활의학과 목록상 재활의학과 전문의 1명으로 노출"
    },
    {
        "id":  "49",
        "district":  "달서구",
        "name":  "원팀재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 의원",
        "rehabDept":  "있음",
        "specialists":  "재활의학과 전문의",
        "careType":  "외래 중심",
        "conditions":  "재활치료, 척추측만증, 자세교정, 산전·산후 재활",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "대구광역시 달서구 장기로 217, 6층",
        "phone":  "053-525-7570",
        "sources":  "https://oneteam-rehab.com/hospitalInfo/timeAddress",
        "verification":  "공식/전화확인",
        "notes":  "공식 홈페이지상 주소·진료과목 확인"
    },
    {
        "id":  "50",
        "district":  "달서구",
        "name":  "보강병원",
        "type":  "병원",
        "inclusion":  "재활의학과 보유 병원 후보",
        "rehabDept":  "있음",
        "specialists":  "재활의학과 전문의",
        "careType":  "외래/입원 재활 후보",
        "conditions":  "척추·관절, 수술 후 재활 후보",
        "specialty":  "병원/재활의학과",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 달서구 월배로 102 (진천동)",
        "phone":  "053-641-9200",
        "sources":  "https://my-doctor.io/dept-hub/%EC%9E%AC%ED%99%9C%EC%9D%98%ED%95%99%EA%B3%BC/%EC%A0%84%EC%B2%B4%EB%B3%91%EC%9B%90/%EB%8C%80%EA%B5%AC-%EB%8B%AC%EC%84%9C%EA%B5%AC",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "달서구 재활의학과 목록상 재활의학과 전문의 기관으로 노출"
    },
    {
        "id":  "51",
        "district":  "달서구",
        "name":  "휴요양병원",
        "type":  "요양병원",
        "inclusion":  "재활요양/요양병원 후보",
        "rehabDept":  "있음",
        "specialists":  "재활의학과 전문의",
        "careType":  "입원재활/요양재활 후보",
        "conditions":  "노인성 질환, 재활요양 후보",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 달서구 성당로 215 (두류동)",
        "phone":  "053-652-2220",
        "sources":  "https://my-doctor.io/dept-hub/%EC%9E%AC%ED%99%9C%EC%9D%98%ED%95%99%EA%B3%BC/%EC%A0%84%EC%B2%B4%EB%B3%91%EC%9B%90/%EB%8C%80%EA%B5%AC-%EB%8B%AC%EC%84%9C%EA%B5%AC",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "달서구 재활의학과 목록상 재활의학과 전문의 요양병원으로 노출"
    },
    {
        "id":  "52",
        "district":  "달서구",
        "name":  "대구에스한방병원",
        "type":  "한방병원",
        "inclusion":  "한방재활/양방 재활의학과 진료과목 후보",
        "rehabDept":  "있음(진료과목)",
        "specialists":  "확인필요",
        "careType":  "외래/입원 한방재활 후보",
        "conditions":  "교통사고, 척추·관절, 한방재활",
        "specialty":  "한방병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 달서구 달구벌대로 1666, 감삼스퀘어 8~10층 (감삼동)",
        "phone":  "053-637-3375",
        "sources":  "https://my-doctor.io/dept-hub/%EC%9E%AC%ED%99%9C%EC%9D%98%ED%95%99%EA%B3%BC/%EB%8C%80%EA%B5%AC",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "진료과목에 재활의학과·한방재활 관련 과목 노출. HIRA 확인 필요"
    },
    {
        "id":  "53",
        "district":  "달서구",
        "name":  "수월한방병원(월배점)",
        "type":  "한방병원",
        "inclusion":  "한방재활 후보",
        "rehabDept":  "있음(진료과목)",
        "specialists":  "확인필요",
        "careType":  "외래/입원 한방재활 후보",
        "conditions":  "교통사고 후유증, 척추·관절, 추나",
        "specialty":  "한방병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 달서구 조암로 17, 이래타워 2~4층 (월성동)",
        "phone":  "053-643-5000",
        "sources":  "https://my-doctor.io/dept-hub/%EC%9E%AC%ED%99%9C%EC%9D%98%ED%95%99%EA%B3%BC/%EC%A0%84%EC%B2%B4%EB%B3%91%EC%9B%90/%EB%8C%80%EA%B5%AC-%EB%8B%AC%EC%84%9C%EA%B5%AC",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "동구점 외 달서구 월성동 병원 후보로 보강. 지점명 확인 필요"
    },
    {
        "id":  "54",
        "district":  "달서구",
        "name":  "창한방병원",
        "type":  "한방병원",
        "inclusion":  "한방재활/재활의학과 진료과목 후보",
        "rehabDept":  "있음(진료과목)",
        "specialists":  "확인필요",
        "careType":  "외래/입원 한방재활 후보",
        "conditions":  "교통사고, 척추·관절, 한방재활",
        "specialty":  "한방병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 달서구 달구벌대로 1616 (감삼동)",
        "phone":  "053-556-9900",
        "sources":  "https://my-doctor.io/dept-hub/%EC%9E%AC%ED%99%9C%EC%9D%98%ED%95%99%EA%B3%BC/%EB%8C%80%EA%B5%AC",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "대구 재활의학과 목록에 진료과목으로 노출"
    },
    {
        "id":  "55",
        "district":  "달서구",
        "name":  "잘보는한방병원",
        "type":  "한방병원",
        "inclusion":  "한방재활/재활의학과 진료과목 후보",
        "rehabDept":  "있음(진료과목)",
        "specialists":  "확인필요",
        "careType":  "외래/입원 한방재활 후보",
        "conditions":  "교통사고, 척추·관절, 한방재활",
        "specialty":  "한방병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 달서구 달구벌대로 1653 (감삼동)",
        "phone":  "053-559-7777",
        "sources":  "https://my-doctor.io/dept-hub/%EC%9E%AC%ED%99%9C%EC%9D%98%ED%95%99%EA%B3%BC/%EB%8C%80%EA%B5%AC",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "대구 재활의학과 목록에 진료과목으로 노출"
    },
    {
        "id":  "56",
        "district":  "달성군",
        "name":  "가창삼성요양병원",
        "type":  "요양병원",
        "inclusion":  "요양재활/한방재활 후보",
        "rehabDept":  "있음(진료과목)",
        "specialists":  "확인필요",
        "careType":  "입원재활/요양재활 후보",
        "conditions":  "노인성 질환, 만성질환, 한방재활",
        "specialty":  "요양병원/양한방협진",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 달성군 가창면 가창로57길 50 (삼산리)",
        "phone":  "053-762-1400",
        "sources":  "https://my-doctor.io/dept-hub/%EC%9E%AC%ED%99%9C%EC%9D%98%ED%95%99%EA%B3%BC/%EB%8C%80%EA%B5%AC",
        "verification":  "HIRA·공식정보 확인",
        "notes":  "대구 재활의학과 목록에 재활의학과·한방재활의학과 진료과목 노출"
    },
    {
        "id":  "57",
        "district":  "달성군",
        "name":  "달성요양병원",
        "type":  "요양병원",
        "inclusion":  "요양병원/물리치료 후보",
        "rehabDept":  "없음 또는 미확인",
        "specialists":  "재활의학과 전문의 없음(보조 출처 기준)",
        "careType":  "입원요양/물리치료 후보",
        "conditions":  "노인성 질환, 장기요양",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "대구광역시 달성군 논공읍 달성군청로1길 8",
        "phone":  "053-626-9988",
        "sources":  "https://ddoga.co.kr/ltch/13/JDQ4MTYyMiM4MSMkMSMkMCMkOTkkNTgxMzUxIzIxIyQxIyQxIyQ5OSQzNjEyMjIjNTEjJDEjJDYjJDgz/W01",
        "verification":  "후보/전화확인",
        "notes":  "재활의학과 전문의는 확인되지 않아 보호자 안내 시 재활전문기관으로 분류 금지"
    },
    {
        "id":  "58",
        "district":  "군위군",
        "name":  "고려마취통증의학과의원",
        "type":  "의원",
        "inclusion":  "군위군 재활의학과 대체 후보(통증/물리치료)",
        "rehabDept":  "재활의학과 없음",
        "specialists":  "해당없음",
        "careType":  "외래 통증/물리치료 후보",
        "conditions":  "근골격계 통증, 통증치료",
        "specialty":  "마취통증의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "대구광역시 군위군 군위읍 중앙길 100",
        "phone":  "054-382-0922",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxOTYxIzIxIyQyIyQ5IyQwMCQzNjE4MzIjNDEjJDEjJDQjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "군위군은 재활의학과 기관이 거의 없어 대체 통증·물리치료 후보로만 분류"
    }
];