window.REHAB_DATA = [
    {
        "district":  "창원시",
        "name":  "근로복지공단 창원병원",
        "type":  "종합병원",
        "inclusion":  "재활의학과 보유 종합병원+산재 재활인증 핵심",
        "rehabDept":  "있음",
        "specialists":  "3명",
        "careType":  "외래/입원 재활",
        "conditions":  "산재·근골격계·뇌손상 등",
        "specialty":  "근로복지공단 병원",
        "recovery":  "해당없음",
        "workersComp":  "재활인증",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 창원시 성산구 창원대로 721",
        "phone":  "055-280-7619",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkODkkMzgxMzUxIzExIyQxIyQzIyQ3MiQyNjEwMDIjNzEjJDEjJDgjJDgz",
        "verification":  "HIRA/공단 확인",
        "notes":  "근로복지공단 직영 산재재활 집중의료기관. 재활의학과 전문의 3명 상주.",
        "id":  "1"
    },
    {
        "district":  "창원시",
        "name":  "희연재활병원",
        "type":  "병원",
        "inclusion":  "회복기/산재 재활인증 핵심 후보",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "회복기/입원재활",
        "conditions":  "뇌졸중, 뇌손상, 근골격계 수술 후 재활",
        "specialty":  "재활병원",
        "recovery":  "지정(제3기)",
        "workersComp":  "재활인증",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 창원시 성산구 원이대로393번길 25",
        "phone":  "055-270-2500",
        "sources":  "https://www.comwel.or.kr/comwel/comp/trmt/rein02.jsp",
        "verification":  "HIRA/공단/공식 지정 확인",
        "notes":  "보건복지부 지정 제3기 회복기 재활의료기관 (2026.03 ~ 2029.02). 근로복지공단 산재 재활인증의료기관.",
        "id":  "2"
    },
    {
        "district":  "창원시",
        "name":  "푸른요양병원",
        "type":  "요양병원",
        "inclusion":  "재활의학과/요양재활 후보+산재 재활인증",
        "rehabDept":  "있음",
        "specialists":  "2명",
        "careType":  "요양재활/입원재활",
        "conditions":  "요양·만성기 재활, 산재 재활 후보",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "재활인증",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 창원시 성산구 창원천로94번길 82-18, 푸른요양병원(B동)",
        "phone":  "055-270-8888",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzExIyQxIyQ3IyQ3OSQ0NjEwMDIjNDEjJDEjJDgjJDgz",
        "verification":  "HIRA/공단 확인",
        "notes":  "건강보험심사평가원(HIRA) 등록 기준 재활의학과 전문의 2명 상주. 전문적인 요양재활 치료실 운영.",
        "id":  "3"
    },
    {
        "district":  "창원시",
        "name":  "바른병원",
        "type":  "병원",
        "inclusion":  "재활병원 후보",
        "rehabDept":  "있음",
        "specialists":  "4명",
        "careType":  "입원재활/외래재활",
        "conditions":  "중추신경계·근골격계 재활 후보",
        "specialty":  "재활병원",
        "recovery":  "지정(제3기)",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 창원시 성산구 창원천로94번길 82-18, 푸른요양병원(A동)",
        "phone":  "055-270-8802",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkMzgxMzUxIzMxIyQxIyQ3IyQ3OSQyNjEwMDIjNTEjJDEjJDYjJDgz",
        "verification":  "HIRA/공식 지정 확인",
        "notes":  "보건복지부 지정 제3기 회복기 재활의료기관 (2026.03 ~ 2029.02). 재활의학과 전문의 4명 협진.",
        "id":  "4"
    },
    {
        "district":  "창원시",
        "name":  "창원파티마병원",
        "type":  "종합병원",
        "inclusion":  "재활의학과 보유 종합병원",
        "rehabDept":  "있음",
        "specialists":  "1명",
        "careType":  "외래/입원 재활",
        "conditions":  "급성기 이후 재활, 근골격계·신경계",
        "specialty":  "종합병원 재활의학과",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 창원시 의창구 창이대로 45-45",
        "phone":  "055-270-1000",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?isNewWindow=Y\u0026isPopupYn=Y\u0026ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkODkkMzgxMzUxIzExIyQxIyQzIyQ4OSQyNjEwMDIjODEjJDEjJDIjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "종합병원 개설 재활의학과. 전문의 1명 상주하여 외래 및 병동 협진 재활 진행.",
        "id":  "5"
    },
    {
        "district":  "창원시",
        "name":  "삼성창원병원",
        "type":  "상급종합병원",
        "inclusion":  "재활의학과 보유 상급종합병원",
        "rehabDept":  "있음",
        "specialists":  "3명",
        "careType":  "급성기/외래·입원 재활",
        "conditions":  "뇌졸중, 신경계, 암/심폐 등 급성기 재활",
        "specialty":  "상급종합병원 재활의학과",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 창원시 마산회원구 팔용로 158-158",
        "phone":  "055-233-8899",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkODkkMzgxMzUxIzExIyQxIyQzIyQ3MiQyNjEyMjIjNjEjJDEjJDQjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "대학병원급 상급종합병원 재활의학과. 전문의 3명 상주 및 다학제 협진 재활 제공.",
        "id":  "6"
    },
    {
        "district":  "창원시",
        "name":  "의료법인석영의료재단 창원제일종합병원",
        "type":  "종합병원",
        "inclusion":  "재활의학과 전문의 확인된 종합병원",
        "rehabDept":  "있음",
        "specialists":  "1",
        "careType":  "외래/입원 재활",
        "conditions":  "근골격계·신경계 재활 후보",
        "specialty":  "종합병원 재활의학과",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 창원시 마산합포구 3·15대로 238",
        "phone":  "055-223-9000",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkODkkMzgxMzUxIzExIyQyIyQzIyQwMCQ0NjE0ODEjNDEjJDEjJDQjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "HIRA snippet상 재활의학과 1명",
        "id":  "7"
    },
    {
        "district":  "창원시",
        "name":  "마산우리요양병원",
        "type":  "요양병원",
        "inclusion":  "재활의학과+한방재활의학과 포함 요양재활",
        "rehabDept":  "있음",
        "specialists":  "2",
        "careType":  "요양재활/입원재활",
        "conditions":  "뇌졸중, 만성기 재활, 요양환자 재활",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 창원시 마산합포구 해안대로 35",
        "phone":  "055-220-7500",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzIxIyQxIyQ1IyQ4OSQ0NjE0ODEjNTEjJDEjJDIjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "HIRA상 일반병상 214, 물리치료실 7 등 표시",
        "id":  "8"
    },
    {
        "district":  "창원시",
        "name":  "잘본병원",
        "type":  "병원",
        "inclusion":  "마산권 뇌졸중·뇌경색 집중재활 표방",
        "rehabDept":  "있음",
        "specialists":  "4명",
        "careType":  "입원재활/외래재활",
        "conditions":  "뇌졸중, 뇌경색 집중재활",
        "specialty":  "재활병원 후보",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 창원시 마산권(상세주소 확인필요)",
        "phone":  "055-253-2000",
        "sources":  "https://www.zalbon.co.kr/",
        "verification":  "공식 홈페이지 확인",
        "notes":  "재활의학과 전문의 4명 상주하여 집중적인 운동치료, 작업치료, 도수치료 프로그램 운영.",
        "id":  "9"
    },
    {
        "district":  "창원시",
        "name":  "시티요양병원",
        "type":  "요양병원",
        "inclusion":  "재활의학과 전문의 2명으로 검색되는 요양재활 후보",
        "rehabDept":  "있음",
        "specialists":  "2명",
        "careType":  "요양입원/외래",
        "conditions":  "뇌졸중·근골격계·요양재활",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 창원시 의창구 대봉로26번길 12-3 (봉림동)",
        "phone":  "055-270-5500",
        "sources":  "http://www.thecityhos.com/",
        "verification":  "HIRA/공식 홈페이지 확인",
        "notes":  "건강보험심사평가원(HIRA) 등록 기준 재활의학과 전문의 2명 상주. 양·한방 협진 및 통증·도수치료실 운영.",
        "id":  "10"
    },
    {
        "district":  "창원시",
        "name":  "행복한요양병원",
        "type":  "요양병원",
        "inclusion":  "재활의학과 진료과 포함 요양병원 후보",
        "rehabDept":  "있음",
        "specialists":  "2명",
        "careType":  "요양입원/외래",
        "conditions":  "요양·만성기 재활 후보",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 창원시 의창구 북면 천주로 785 (동전리)",
        "phone":  "055-259-1111",
        "sources":  "http://www.happy2008.co.kr",
        "verification":  "HIRA/공식 홈페이지 확인",
        "notes":  "건강보험심사평가원(HIRA) 적정성 평가 1등급 획득 요양병원. 보바스 재활치료 및 로봇재활치료실 등 운영.",
        "id":  "11"
    },
    {
        "district":  "진주시",
        "name":  "예손재활의학과병원",
        "type":  "병원",
        "inclusion":  "재활의학과병원+산재 재활인증",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "입원재활/외래재활",
        "conditions":  "중추신경계·근골격계 재활",
        "specialty":  "재활의학과병원",
        "recovery":  "지정(제3기)",
        "workersComp":  "재활인증",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 진주시 진주대로 839",
        "phone":  "055-791-7575",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkMzgxMzUxIzIxIyQxIyQ1IyQ2MiQ0NjEwMDIjODEjJDEjJDYjJDgz",
        "verification":  "HIRA/공단/공식 지정 확인",
        "notes":  "보건복지부 지정 제3기 회복기 재활의료기관 (2026.03 ~ 2029.02). 근로복지공단 산재 재활인증의료기관.",
        "id":  "12"
    },
    {
        "district":  "진주시",
        "name":  "한빛재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 전문의 확인 의원",
        "rehabDept":  "있음",
        "specialists":  "1",
        "careType":  "외래재활",
        "conditions":  "근골격계·신경계 외래재활",
        "specialty":  "재활의학과의원",
        "recovery":  "해당없음",
        "workersComp":  "해당없음",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "경상남도 진주시 동진로 146, 2층",
        "phone":  "055-757-7550",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMiMkNCMkMDAkMzgxMTkxIzUxIyQxIyQ1IyQ4MiQ0NjE0ODEjODEjJDEjJDYjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "외래 중심",
        "id":  "13"
    },
    {
        "district":  "진주시",
        "name":  "진주재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 전문의 확인 의원",
        "rehabDept":  "있음",
        "specialists":  "1",
        "careType":  "외래재활",
        "conditions":  "근골격계·신경계 외래재활",
        "specialty":  "재활의학과의원",
        "recovery":  "해당없음",
        "workersComp":  "해당없음",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "경상남도 진주시 대신로 325",
        "phone":  "055-753-6228",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMiMkNCMkMDAkMzgxMTkxIzIxIyQxIyQxIyQ3OSQyNjE4MzIjNDEjJDEjJDQjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "HIRA snippet 전화번호는 지역번호 없이 표기되어 055 보강",
        "id":  "14"
    },
    {
        "district":  "거제시",
        "name":  "사회복지법인내원 마하재활병원",
        "type":  "병원",
        "inclusion":  "거제권 재활병원 핵심",
        "rehabDept":  "있음",
        "specialists":  "1명",
        "careType":  "입원재활/외래재활",
        "conditions":  "뇌병변·장애인·중추신경계 재활 후보",
        "specialty":  "재활병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 거제시 동부면 율포로 555-11",
        "phone":  "055-633-3000",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkMzgxMzUxIzIxIyQxIyQ1IyQ3OSQzNjEwMDIjNzEjJDEjJDgjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "사회복지법인내원 직영 재활특화 병원. 재활의학과 전문의 1명 상주 및 전문 치료실 운영.",
        "id":  "15"
    },
    {
        "district":  "거제시",
        "name":  "신동훈재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 전문 의원",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "외래재활",
        "conditions":  "근골격계·신경계 외래재활",
        "specialty":  "재활의학과의원",
        "recovery":  "해당없음",
        "workersComp":  "해당없음",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "경상남도 거제시 거제중앙로 1941, 로이빌딩 5층",
        "phone":  "055-632-0013",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMiMkNCMkMDAkNDgxOTYxIzExIyQxIyQzIyQ4OSQzNjE0ODEjODEjJDEjJDYjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "외래 중심",
        "id":  "16"
    },
    {
        "district":  "거제시",
        "name":  "거제요양병원",
        "type":  "요양병원",
        "inclusion":  "요양재활 후보",
        "rehabDept":  "있음",
        "specialists":  "없음",
        "careType":  "요양재활/입원재활",
        "conditions":  "요양·만성기 재활, 물리치료",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 거제시 거제대로 2975",
        "phone":  "055-682-5555",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzIxIyQxIyQ1IyQxMyQyNjEwMDIjNTEjJDEjJDYjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "양·한방 협진 요양병원. 침구과, 한방재활 및 일반 물리치료실 운영.",
        "id":  "17"
    },
    {
        "district":  "거제시",
        "name":  "맑은샘병원",
        "type":  "종합병원",
        "inclusion":  "거제 종합병원 재활/전원 후보",
        "rehabDept":  "없음",
        "specialists":  "없음",
        "careType":  "외래/입원 연계 후보",
        "conditions":  "급성기·수술 후 연계 후보",
        "specialty":  "종합병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 거제시 연초면 거제대로 4477",
        "phone":  "055-736-1004",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkODkkMzgxMzUxIzExIyQxIyQzIyQ3MiQzNjE4MzIjNjEjJDEjJDgjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "종합병원 물리치료실 운영. 재활의학과 전문의 상근 여부는 문의 필요.",
        "id":  "18"
    },
    {
        "district":  "고성군",
        "name":  "고성제일요양병원",
        "type":  "요양병원",
        "inclusion":  "요양재활 후보",
        "rehabDept":  "없음",
        "specialists":  "없음",
        "careType":  "요양재활/물리치료",
        "conditions":  "만성기·노인성 질환 요양, 물리치료",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 고성군 고성읍 일대(상세주소 HIRA 확인필요)",
        "phone":  "확인필요",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzIxIyQxIyQ1IyQ5OSQyNjE4MzIjODEjJDEjJDYjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "요양병원 물리치료실 운영. 재활의학과 전문의 상근 여부는 문의 필요.",
        "id":  "19"
    },
    {
        "district":  "고성군",
        "name":  "고성요양병원",
        "type":  "요양병원",
        "inclusion":  "요양재활/물리치료 후보",
        "rehabDept":  "없음",
        "specialists":  "없음",
        "careType":  "요양입원",
        "conditions":  "요양·만성기 재활 후보",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 고성군 고성읍 남해안대로 2607",
        "phone":  "055-672-3100",
        "sources":  "http://고성요양병원.com/",
        "verification":  "공식 홈페이지 확인",
        "notes":  "물리치료실 및 한방 요양 협진 운영. 재활의학과 전문의 진료 여부는 방문 전 대표번호로 문의 필요.",
        "id":  "20"
    },
    {
        "district":  "밀양시",
        "name":  "밀양요양병원",
        "type":  "요양병원",
        "inclusion":  "요양재활/물리치료 후보",
        "rehabDept":  "없음",
        "specialists":  "없음",
        "careType":  "요양재활/입원재활",
        "conditions":  "노인성·만성기 재활, 물리치료",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 밀양시 용평로6길 8",
        "phone":  "055-355-5599",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzIxIyQxIyQ5IyQ3OSQyNjEwMDIjNjEjJDEjJDAjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "요양병원 물리치료실 운영. 재활의학과 전문의 상근 여부는 문의 필요.",
        "id":  "21"
    },
    {
        "district":  "함안군",
        "name":  "의료법인 시영의료재단 함안요양병원",
        "type":  "요양병원",
        "inclusion":  "요양재활/물리치료 후보",
        "rehabDept":  "없음",
        "specialists":  "없음",
        "careType":  "요양재활/입원재활",
        "conditions":  "노인성·만성기 재활, 물리치료",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 함안군 칠원읍 용산2길 45-13, 4층",
        "phone":  "055-586-5009",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzIxIyQxIyQxIyQ4MiQzNjE0ODEjNDEjJDEjJDQjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "요양병원 물리치료실 운영. 재활의학과 전문의 상근 여부는 문의 필요.",
        "id":  "22"
    },
    {
        "district":  "거창군",
        "name":  "거창군립 노인요양병원",
        "type":  "요양병원",
        "inclusion":  "공립 요양재활/물리치료 후보",
        "rehabDept":  "없음",
        "specialists":  "없음",
        "careType":  "요양재활/입원재활",
        "conditions":  "노인성·만성기 재활, 물리치료",
        "specialty":  "공립 노인전문 요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 거창군 거창읍 운정3길 180",
        "phone":  "055-943-3333",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzExIyQyIyQzIyQwMCQ0NjEwMDIjNjEjJDEjJDgjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "거창군립 요양병원. 일반 물리치료실 운영. 재활의학과 전문의 상근 여부는 문의 필요.",
        "id":  "23"
    },
    {
        "district":  "사천시",
        "name":  "사천시원재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 의원",
        "rehabDept":  "있음",
        "specialists":  "1명(확인)",
        "careType":  "외래재활",
        "conditions":  "근골격계 통증, 도수치료, 프롤로, 체외충격파",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "가능성 높음",
        "dayRehab":  "해당없음",
        "address":  "경상남도 사천시 정동면 옥산로 46, 201호",
        "phone":  "055-820-8899",
        "sources":  "http://4000sione.com/",
        "verification":  "공식 홈페이지 확인",
        "notes":  "재활의학과 전문의 진료. 통증 치료 및 물리치료 전문",
        "id":  "24"
    },
    {
        "district":  "창녕군",
        "name":  "경남요양병원",
        "type":  "요양병원",
        "inclusion":  "요양병원 재활",
        "rehabDept":  "없음",
        "specialists":  "없음",
        "careType":  "요양재활/입원재활",
        "conditions":  "뇌졸중, 치매, 파킨슨 등 노인성 질환 재활",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 창녕군 남지읍 남지중앙로 45",
        "phone":  "055-526-2200",
        "sources":  "http://www.kn-hospital.com/",
        "verification":  "공식 정보 확인",
        "notes":  "요양병원 물리치료실 운영. 재활의학과 전문의 상근 여부는 문의 필요.",
        "id":  "25"
    },
    {
        "district":  "창녕군",
        "name":  "로얄힐스요양병원",
        "type":  "요양병원",
        "inclusion":  "양·한방 협진 요양재활",
        "rehabDept":  "있음",
        "specialists":  "없음",
        "careType":  "요양재활/암재활",
        "conditions":  "암수술 후 재활, 도수치료, 물리치료",
        "specialty":  "암재활 요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 창녕군 부곡면 온천중앙로 115",
        "phone":  "055-520-2200",
        "sources":  "http://royalhills.kr/",
        "verification":  "공식 홈페이지 확인",
        "notes":  "양·한방 협진 요양병원. 암 수술 후 재활 및 한방재활, 도수치료실 운영.",
        "id":  "26"
    },
    {
        "district":  "의령군",
        "name":  "의령군립노인전문병원",
        "type":  "요양병원",
        "inclusion":  "군립 노인전문 요양재활",
        "rehabDept":  "없음",
        "specialists":  "없음",
        "careType":  "요양재활/입원재활",
        "conditions":  "노인성 질환 및 만성기 물리치료",
        "specialty":  "군립 노인전문병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 의령군 의령읍 중동리 234-1",
        "phone":  "055-573-0500",
        "sources":  "HIRA 확인",
        "verification":  "HIRA 확인",
        "notes":  "의령군립 요양병원. 일반 물리치료실 운영. 재활의학과 전문의 상근 여부는 문의 필요.",
        "id":  "27"
    },
    {
        "district":  "의령군",
        "name":  "의령사랑요양병원",
        "type":  "요양병원",
        "inclusion":  "노인성 질환 요양재활",
        "rehabDept":  "없음",
        "specialists":  "없음",
        "careType":  "요양재활/입원재활",
        "conditions":  "노인성 질환 및 만성 관리",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 의령군 의령읍 벽화로 815",
        "phone":  "055-574-0012",
        "sources":  "HIRA 확인",
        "verification":  "HIRA 확인",
        "notes":  "요양병원 물리치료실 운영. 재활의학과 전문의 상근 여부는 문의 필요.",
        "id":  "28"
    },
    {
        "district":  "남해군",
        "name":  "남해군립노인전문병원",
        "type":  "요양병원",
        "inclusion":  "군립 노인전문 요양재활",
        "rehabDept":  "없음",
        "specialists":  "없음",
        "careType":  "요양재활/입원재활",
        "conditions":  "뇌졸중, 치매, 노인성 질환 물리치료",
        "specialty":  "군립 노인전문병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 남해군 남해읍 화전로 173-1",
        "phone":  "055-864-2201",
        "sources":  "HIRA 확인",
        "verification":  "HIRA 확인",
        "notes":  "남해군립 요양병원. 일반 물리치료실 운영. 재활의학과 전문의 상근 여부는 문의 필요.",
        "id":  "29"
    },
    {
        "district":  "하동군",
        "name":  "하동우리들병원",
        "type":  "요양병원",
        "inclusion":  "노인전문 및 정신/요양재활",
        "rehabDept":  "없음",
        "specialists":  "없음",
        "careType":  "요양재활/입원재활",
        "conditions":  "노인성 질환 및 만성 물리치료",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 하동군 금남면 경충로 953",
        "phone":  "055-883-7575",
        "sources":  "HIRA 확인",
        "verification":  "HIRA 확인",
        "notes":  "일반 병원 물리치료실 운영. 재활의학과 전문의 상근 여부는 문의 필요.",
        "id":  "30"
    },
    {
        "district":  "산청군",
        "name":  "산청요양병원",
        "type":  "요양병원",
        "inclusion":  "양·한방 협진 요양재활",
        "rehabDept":  "없음",
        "specialists":  "없음",
        "careType":  "요양재활/암재활",
        "conditions":  "암 통합 치료 및 노인성 만성 질환 물리치료",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 산청군 금서면 친환경로2605번길 69",
        "phone":  "055-970-9000",
        "sources":  "HIRA 확인",
        "verification":  "HIRA 확인",
        "notes":  "요양병원 물리치료실 운영. 재활의학과 전문의 상근 여부는 문의 필요.",
        "id":  "31"
    },
    {
        "district":  "함양군",
        "name":  "함양성심병원",
        "type":  "병원",
        "inclusion":  "지역 거점 병원 재활",
        "rehabDept":  "없음",
        "specialists":  "없음",
        "careType":  "외래/입원 물리치료",
        "conditions":  "척추·관절 질환, 정형외과 물리치료",
        "specialty":  "병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 함양군 함양읍 고운로 60",
        "phone":  "055-962-1111",
        "sources":  "http://hysungsim.com/",
        "verification":  "공식 홈페이지 확인",
        "notes":  "함양 지역 병원. 일반 물리치료실 운영. 재활의학과 전문의 상근 여부는 문의 필요.",
        "id":  "32"
    },
    {
        "district":  "합천군",
        "name":  "합천요양병원",
        "type":  "요양병원",
        "inclusion":  "양·한방 협진 요양재활",
        "rehabDept":  "없음",
        "specialists":  "없음",
        "careType":  "요양재활/입원재활",
        "conditions":  "노인성 질환 및 만성기 한방재활 협진",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 합천군 합천읍 신소양2길 40",
        "phone":  "055-932-2600",
        "sources":  "HIRA 확인",
        "verification":  "HIRA 확인",
        "notes":  "요양병원 물리치료실 운영. 재활의학과 전문의 상근 여부는 문의 필요.",
        "id":  "33"
    },
    {
        "district":  "합천군",
        "name":  "합천고려요양병원",
        "type":  "요양병원",
        "inclusion":  "노인성 질환 요양재활",
        "rehabDept":  "없음",
        "specialists":  "없음",
        "careType":  "요양재활/입원재활",
        "conditions":  "치매, 중풍, 노인 만성 질환 물리치료",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 합천군 대양면 대야로 737-20",
        "phone":  "055-933-7000",
        "sources":  "HIRA 확인",
        "verification":  "HIRA 확인",
        "notes":  "요양병원 물리치료실 운영. 재활의학과 전문의 상근 여부는 문의 필요.",
        "id":  "34"
    },
    {
        "district":  "김해시",
        "name":  "의료법인환명의료재단 조은금강병원",
        "type":  "종합병원",
        "inclusion":  "재활의학과 보유 종합병원",
        "rehabDept":  "있음",
        "specialists":  "1명(HIRA 확인)",
        "careType":  "외래/입원 재활 가능성",
        "conditions":  "뇌졸중 후유증, 근골격계, 수술 후 재활, 보행장애, 통증",
        "specialty":  "종합병원 재활의학과",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경남 김해시 김해대로 1814-37",
        "phone":  "055-330-0300",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkODkkMzgxMzUxIzExIyQxIyQzIyQ2MiQ0NjEwMDIjNjEjJDEjJDQjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "HIRA에서 재활의학과 전문의 1명 확인. 입원재활 세부 운영은 전화확인 필요",
        "id":  "35"
    },
    {
        "district":  "김해시",
        "name":  "김해굿모닝병원",
        "type":  "병원",
        "inclusion":  "재활의학과 보유 병원",
        "rehabDept":  "있음",
        "specialists":  "1명(HIRA 검색결과)",
        "careType":  "외래/입원 재활 가능성",
        "conditions":  "근골격계, 수술 후 재활, 통증, 보행장애",
        "specialty":  "병원 재활의학과",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경남 김해시 분성로 444",
        "phone":  "055-333-9522",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkMzgxMzUxIzIxIyQxIyQ1IyQ4OSQyNjEwMDIjNDEjJDEjJDgjJDgz",
        "verification":  "HIRA 검색결과 확인",
        "notes":  "검색결과상 재활의학과(1) 표기. HIRA 세부 전문의 현황 재확인 권장",
        "id":  "36"
    },
    {
        "district":  "김해시",
        "name":  "구샘재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 의원",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "외래 중심",
        "conditions":  "근골격계 통증, 도수/물리치료, 신경계 후유증, 보행/운동재활",
        "specialty":  "재활의학과 외래",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "경남 김해시 진영읍 김해대로361번길 16, 3층",
        "phone":  "055-343-1345",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMiMkNCMkMDAkNDgxMzUxIzMxIyQxIyQ3IyQ5MiQ0NjE0ODEjODEjJDEjJDIjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "전문의 수는 세부 진료과목 현황 재확인 필요",
        "id":  "37"
    },
    {
        "district":  "김해시",
        "name":  "의료법인희원의료재단 래봄병원",
        "type":  "병원",
        "inclusion":  "재활병원/재활의학과 전문의 후보",
        "rehabDept":  "있음",
        "specialists":  "2명(HIRA 확인)",
        "careType":  "입원재활/외래재활",
        "conditions":  "뇌졸중, 뇌손상, 척수손상, 파킨슨, 근골격계, 로봇재활, 일상생활동작",
        "specialty":  "재활치료센터/로봇재활",
        "recovery":  "제3기 지정",
        "workersComp":  "산재 재활인증기관 확인(근로복지공단)",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경남 김해시 분성로 202",
        "phone":  "1644-8765",
        "sources":  "https://www.rebom.or.kr/ / https://www.comwel.or.kr/comwel/comp/trmt/rein02.jsp",
        "verification":  "공식+공단 확인",
        "notes":  "보건복지부 지정 제3기 회복기 재활의료기관 (2026.03 ~ 2029.02). 근로복지공단 산재재활인증의료기관.",
        "id":  "38"
    },
    {
        "district":  "김해시",
        "name":  "의료법인푸른솔의료재단 김해한솔재활요양병원",
        "type":  "요양병원",
        "inclusion":  "재활요양병원/재활의학과 전문의",
        "rehabDept":  "있음",
        "specialists":  "4명(요양병원 정보 확인)",
        "careType":  "입원재활/요양재활",
        "conditions":  "뇌손상, 척수손상, 로봇재활, 근골격계/통증, 소아재활, 호흡재활",
        "specialty":  "재활요양/로봇재활",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 김해시 흥동로 111 (흥동)",
        "phone":  "055-329-3340",
        "sources":  "https://www.ghhansol.co.kr/ / https://ddoga.co.kr/ltch/13/JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzExIyQxIyQzIyQ5MiQyNjE0ODEjNDEjJDEjJDgjJDgz/W01",
        "verification":  "공식+요양정보 확인",
        "notes":  "기관 홈페이지에 뇌손상/척수손상/로봇재활 등 표기, 전문의 수는 HIRA 재확인 권장",
        "id":  "39"
    },
    {
        "district":  "김해시",
        "name":  "(의)밀성학원의료재단 성모아하브요양병원",
        "type":  "요양병원",
        "inclusion":  "요양병원/물리치료실 보유",
        "rehabDept":  "없음",
        "specialists":  "없음",
        "careType":  "요양재활 가능성",
        "conditions":  "노인성질환, 기능저하, 물리치료, 만성기 관리",
        "specialty":  "요양병원",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "경상남도 김해시 김해대로 2479-1 (삼정동)",
        "phone":  "055-320-2080",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzIxIyQxIyQ1IyQ4OSQzNjE4MzIjNjEjJDEjJDAjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "요양병원 물리치료실 운영. 재활의학과 전문의 상근 여부는 문의 필요.",
        "id":  "40"
    },
    {
        "district":  "김해시",
        "name":  "의료법인한서의료재단 진영병원",
        "type":  "병원",
        "inclusion":  "재활의학과 진료과목 후보/정형·신경계 외래",
        "rehabDept":  "없음",
        "specialists":  "없음",
        "careType":  "외래/입원 가능성",
        "conditions":  "정형외과, 신경외과, 영상의학 기반 재활 연계 가능성",
        "specialty":  "재활의학과 전문의 없음",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "경남 김해시 진영읍 김해대로334번길 9",
        "phone":  "055-340-3700",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkMzgxMzUxIzIxIyQxIyQ5IyQ3OSQyNjEyMjIjODEjJDEjJDYjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "일반 병원 물리치료실 운영. 재활의학과 전문의 상근 여부는 문의 필요.",
        "id":  "41"
    },
    {
        "district":  "양산시",
        "name":  "양산부산대학교병원",
        "type":  "상급종합병원",
        "inclusion":  "재활의학과 보유 상급종합병원",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "급성기/외래/입원재활",
        "conditions":  "뇌졸중, 뇌손상, 척수손상, 소아재활, 암재활, 근골격계, 보조기",
        "specialty":  "상급종합 재활의학과",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "외래/입원 중심",
        "address":  "경상남도 양산시 물금읍 금오로 20",
        "phone":  "055-360-1000",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?isNewWindow=Y\u0026isPopupYn=Y\u0026ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkODkkMzgxMzUxIzExIyQxIyQzIyQ3MiQyNjE0ODEjODEjJDEjJDYjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "전문의 수는 HIRA 진료과목 세부현황 재확인 필요",
        "id":  "42"
    },
    {
        "district":  "양산시",
        "name":  "양산제일병원",
        "type":  "병원",
        "inclusion":  "재활의학과 보유 병원",
        "rehabDept":  "있음",
        "specialists":  "2명(검색결과)",
        "careType":  "외래/입원 재활 가능성",
        "conditions":  "근골격계, 수술 후 재활, 통증, 신경계 후유증",
        "specialty":  "병원 재활의학과",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "경상남도 양산시 동면 금오로 255 (양산에이치타워)",
        "phone":  "055-904-7575",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkMzgxMzUxIzMxIyQxIyQzIyQ4OSQzNjE0ODEjODEjJDEjJDYjJDgz / https://my-doctor.io/hospital/deptHub/region/재활의학과-경남-양산시",
        "verification":  "HIRA+검색결과 확인",
        "notes":  "검색결과상 재활의학과 전문의 2명. HIRA 세부 재확인 권장",
        "id":  "43"
    },
    {
        "district":  "양산시",
        "name":  "양산서울요양병원",
        "type":  "요양병원",
        "inclusion":  "재활요양병원/재활의학과 보유",
        "rehabDept":  "있음",
        "specialists":  "1명(HIRA 확인)",
        "careType":  "입원재활/요양재활",
        "conditions":  "뇌졸중, 노인성질환, 정형외과 수술 후, 신경계 후유증, 한방협진",
        "specialty":  "재활요양/양한방",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "경상남도 양산시 삼성7길 11-14 (북정동)",
        "phone":  "055-364-1000",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzIxIyQxIyQ1IyQwMyQ0NjEwMDIjNDEjJDEjJDgjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "HIRA상 재활의학과 전문의 1명 확인",
        "id":  "44"
    },
    {
        "district":  "양산시",
        "name":  "양산아이재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 의원/아동특화",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "외래 중심",
        "conditions":  "소아·아동 재활, 발달평가, 언어/인지/운동 발달, 신경계 질환",
        "specialty":  "아동 특화 재활의학과",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "경상남도 양산시 물금읍 청운로 185, 오즈시티 203호",
        "phone":  "055-381-1236",
        "sources":  "https://yangsani.co.kr/ / https://doctorindex.co.kr/clinic/경상남도-양산시-양산아이재활의학과의원/",
        "verification":  "공식+공공데이터",
        "notes":  "2025.05.13 개설 자료. HIRA 최신개설상태 재확인 필요",
        "id":  "45"
    },
    {
        "district":  "양산시",
        "name":  "양산더존한방병원",
        "type":  "한방병원",
        "inclusion":  "한방재활의학과 전문의/한방재활",
        "rehabDept":  "해당없음",
        "specialists":  "해당없음",
        "careType":  "외래/입원 가능성",
        "conditions":  "추나, 한방재활, 교통사고 후유증, 척추·관절 통증",
        "specialty":  "한방재활의학과 전문의",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "자동차보험 확인필요",
        "dayRehab":  "확인필요",
        "address":  "경남 양산시 물금읍 청운로 349",
        "phone":  "055-785-0000",
        "sources":  "https://www.kmspecialist.org/community/bbs/kmspecialist.php?guest=true\u0026mb_id=soal86 / https://yangsan.thezoneh.com/kwa-40122",
        "verification":  "전문의 공식 확인",
        "notes":  "한방재활의학과 전문의 김형구 표기. 의과 재활의학과와 구분 필요",
        "id":  "46"
    },
    {
        "district":  "양산시",
        "name":  "양산부산대학교한방병원",
        "type":  "한방병원",
        "inclusion":  "한방재활의학과/공립 한방병원",
        "rehabDept":  "해당없음",
        "specialists":  "해당없음",
        "careType":  "외래/입원 가능성",
        "conditions":  "한방재활, 추나, 근골격계, 중풍 후유증, 통증",
        "specialty":  "공립 한방병원",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "자동차보험 확인필요",
        "dayRehab":  "확인필요",
        "address":  "경남 양산시 물금읍 금오로 20",
        "phone":  "055-360-5555",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?isNewWindow=Y\u0026ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkMTMkMzgxMTkxIzExIyQxIyQzIyQ5OSQ0NjE0ODEjNDEjJDEjJDQjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "한방병원으로 의과 재활의학과 전문의와 별도 구분",
        "id":  "47"
    }
];
