window.REHAB_DATA = [
    {
        "id": "1",
        "district": "춘천시",
        "name": "강원특별자치도재활병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 소아재활, 근골격계 재활",
        "specialty": "보건복지부 회복기 지정 / 산재 재활인증",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "강원특별자치도 춘천시 충열로142번길 24-16 (우두동)",
        "phone": "033-248-7700",
        "sources": "https://www.grh.or.kr",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "강원권역 공공 재활병원. 보건복지부 지정 제3기 회복기 재활의료기관 (2026.03 ~ 2029.02). 춘천강원권 공공어린이재활의료센터 운영."
    },
    {
        "id": "2",
        "district": "원주시",
        "name": "영광재활병원",
        "type": "병원",
        "inclusion": "회복기/산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "회복기/입원재활/외래재활",
        "conditions": "뇌졸중, 뇌손상, 척수손상, 근골격계 재활, 수술 후 집중재활",
        "specialty": "보건복지부 회복기 지정 / 산재 재활인증",
        "recovery": "지정(제3기)",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "운영",
        "address": "강원특별자치도 원주시 오리현길 236 (행구동)",
        "phone": "033-746-4100",
        "sources": "http://ykrh.co.kr/",
        "verification": "보건복지부/HIRA/공단 확인",
        "notes": "보건복지부 지정 제3기 회복기 재활의료기관. 근로복지공단 산재 재활인증의료기관. 집중 재활 및 사회복귀 특화 병원."
    },
    {
        "id": "3",
        "district": "태백시",
        "name": "근로복지공단 태백병원",
        "type": "종합병원",
        "inclusion": "산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "산재 장해 재활, 근골격계 재활, 직업 복귀 평가",
        "specialty": "근로복지공단 직영 / 산재 재활인증",
        "recovery": "해당없음",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "강원특별자치도 태백시 보드미길 8 (장성동)",
        "phone": "033-580-3114",
        "sources": "https://www.comwel.or.kr",
        "verification": "근로복지공단 공식 확인",
        "notes": "근로복지공단 직영 병원. 산재환자 맞춤형 집중 재활 프로그램 및 전문 재활치료센터 운영."
    },
    {
        "id": "4",
        "district": "동해시",
        "name": "근로복지공단 동해병원",
        "type": "종합병원",
        "inclusion": "산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "산재 장해 재활, 근골격계 물리치료, 직업복귀 프로그램",
        "specialty": "근로복지공단 직영 / 산재 재활인증",
        "recovery": "해당없음",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "강원특별자치도 동해시 하평로 11 (평릉동)",
        "phone": "033-530-3100",
        "sources": "https://www.comwel.or.kr",
        "verification": "근로복지공단 공식 확인",
        "notes": "영동지역 최대 규모의 재활전문센터 보유. 수중운동치료풀 등 특화 시설 구비."
    },
    {
        "id": "5",
        "district": "삼척시",
        "name": "삼척의료원",
        "type": "종합병원",
        "inclusion": "산재 재활인증 핵심",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "뇌졸중 후유증, 급성기 이후 재활, 산재 재활",
        "specialty": "지역 거점 공공병원 / 산재 재활인증",
        "recovery": "해당없음",
        "workersComp": "재활인증",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "강원특별자치도 삼척시 오십천로 418 (남양동)",
        "phone": "033-572-1141",
        "sources": "http://www.samcheokmc.or.kr/",
        "verification": "HIRA/공단 확인",
        "notes": "강원특별자치도립 삼척의료원. 지역 공공 의료 거점 병원으로서 산재 재활인증을 획득하여 전문 물리치료 지원."
    },
    {
        "id": "6",
        "district": "춘천시",
        "name": "강원대학교병원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "급성기/입원재활/외래재활",
        "conditions": "뇌신경 재활, 척수손상 재활, 전기진단검사, 소아재활",
        "specialty": "국립대학교병원 / 권역심뇌혈관센터 연계",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "강원특별자치도 춘천시 백령로 156 (효자동)",
        "phone": "033-258-2000",
        "sources": "https://www.knuh.or.kr",
        "verification": "HIRA 확인",
        "notes": "강원 지역 거점 국립대병원. 권역심뇌혈관센터와의 긴밀한 연계로 급성기 마비 환자의 조기 재활 치료 강점."
    },
    {
        "id": "7",
        "district": "원주시",
        "name": "원주세브란스기독병원",
        "type": "종합병원",
        "inclusion": "상급종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "급성기/입원재활/외래재활",
        "conditions": "뇌혈관 수술 후 재활, 척수 손상, 중추신경계 마비, 소아재활",
        "specialty": "상급종합병원 / 대학병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "강원특별자치도 원주시 일산로 20 (일산동)",
        "phone": "033-741-0114",
        "sources": "https://wch.or.kr/",
        "verification": "HIRA 확인",
        "notes": "강원 지역 유일의 상급종합병원 중 하나로 정밀하고 체계적인 다학제 재활의학과 협진 가능."
    },
    {
        "id": "8",
        "district": "강릉시",
        "name": "강릉아산병원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "급성기/입원재활/외래재활",
        "conditions": "뇌졸중, 척추관련 통증, 관절 수술 후 재활",
        "specialty": "아산재단 대형종합병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "강원특별자치도 강릉시 사천면 방동길 38",
        "phone": "033-610-3114",
        "sources": "https://www.gnah.co.kr",
        "verification": "HIRA 확인",
        "notes": "영동 지역 의료 거점 종합병원. 넓고 쾌적한 재활치료센터를 통해 고품질의 물리/작업치료 지원."
    },
    {
        "id": "9",
        "district": "강릉시",
        "name": "강릉동인병원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "뇌신경 재활, 근골격계 수술 후 재활, 통증 치료",
        "specialty": "종합병원 재활의학과",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "강원특별자치도 강릉시 강릉대로419번길 42 (포남동)",
        "phone": "033-650-6000",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "강릉 포남동 소재 종합병원. 재활의학과 전문의 상주 및 근전도검사, 신경재활 전문 물리치료실 제공."
    },
    {
        "id": "10",
        "district": "원주시",
        "name": "강원특별자치도 원주의료원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "입원재활/외래재활",
        "conditions": "급성기 이후 뇌손상, 척수 손상, 노인성 재활치료",
        "specialty": "지역 거점 공공병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "강원특별자치도 원주시 서원대로 387 (개운동)",
        "phone": "033-760-4500",
        "sources": "https://www.kwmc.or.kr/",
        "verification": "공식 홈페이지 확인",
        "notes": "지역 공공 보건의료를 담당하는 의료원으로, 재활치료센터를 통해 표준적이며 경제적인 물리/작업치료 운영."
    },
    {
        "id": "11",
        "district": "춘천시",
        "name": "한림대학교 춘천성심병원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래/입원재활",
        "conditions": "뇌졸중, 파킨슨병, 척추·관절 수술 후 마비 회복",
        "specialty": "대학병원 재활의학과",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "강원특별자치도 춘천시 삭주로 77 (교동)",
        "phone": "033-240-5000",
        "sources": "https://chuncheon.hallym.or.kr/",
        "verification": "HIRA 확인",
        "notes": "춘천 시내 교동에 위치한 대학병원. 급성기 뇌혈관 질환에 대한 집중 물리치료 및 맞춤 재활 처방."
    },
    {
        "id": "12",
        "district": "강릉시",
        "name": "강원특별자치도 강릉의료원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래/입원재활",
        "conditions": "뇌경색/뇌출혈 후유마비, 만성 관절 통증",
        "specialty": "지역 거점 공공병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "강원특별자치도 강릉시 경강로 2007 (남문동)",
        "phone": "033-610-1200",
        "sources": "https://www.gwdmc.or.kr/",
        "verification": "HIRA 확인",
        "notes": "공공보건의료 거점 기관. 재활의학과 개설로 영동지역 주민에게 밀착형 재활 의료 서비스 제공."
    },
    {
        "id": "13",
        "district": "속초시",
        "name": "강원특별자치도 속초의료원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래/입원재활",
        "conditions": "뇌졸중 후유증, 노인성 마비 케어, 척추 디스크 물리치료",
        "specialty": "지역 거점 공공병원 / 재활치료센터",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "강원특별자치도 속초시 영랑호반길 3 (영랑동)",
        "phone": "033-630-6000",
        "sources": "https://www.sokchomc.or.kr/",
        "verification": "공식 홈페이지 확인",
        "notes": "속초 및 설악권 거점 공공의료원. 재활치료센터(직통 033-630-6084)를 통해 도수치료 및 작업치료 운영."
    },
    {
        "id": "14",
        "district": "영월군",
        "name": "강원특별자치도 영월의료원",
        "type": "종합병원",
        "inclusion": "종합병원 재활의학과",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "외래재활",
        "conditions": "만성 근골격계 질환, 경증 마비성 통증, 기본 물리치료",
        "specialty": "지역 거점 공공병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 영월군 영월읍 중앙1로 59",
        "phone": "033-370-9101",
        "sources": "https://www.ywmch.or.kr/",
        "verification": "공식 홈페이지 확인",
        "notes": "영월 지역의 대표 거점 의료원. 의료진 변동이 있을 수 있어 방문 전 재활의학과 전문의 진료 여부를 대표전화로 확인 권장."
    },
    {
        "id": "15",
        "district": "춘천시",
        "name": "춘천시노인전문병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌경색 후유증, 파킨슨병, 치매 노인성 재활",
        "specialty": "시립 노인전문병원 / 보건복지부 치매안심",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "강원특별자치도 춘천시 동면 세실로 252",
        "phone": "033-240-7500",
        "sources": "http://www.ccgeriatric.co.kr/",
        "verification": "공식 홈페이지 확인",
        "notes": "춘천시가 설립한 시립노인전문요양병원. 쾌적한 인프라에서 고령 환자를 위한 노인성 요양 및 물리치료 병행."
    },
    {
        "id": "16",
        "district": "춘천시",
        "name": "춘천요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활 특화",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌졸중, 척수마비 후유증 요양, 수술 후 회복",
        "specialty": "요양병원 재활",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "강원특별자치도 춘천시 동면 춘천로 527-34",
        "phone": "033-260-7114",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "동면에 위치한 민간 요양병원. 재활의학과 전문의 지도하에 체계적인 운동/작업 재활실 운영."
    },
    {
        "id": "17",
        "district": "동해시",
        "name": "동해요양병원",
        "type": "요양병원",
        "inclusion": "요양병원 재활",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "요양재활/입원재활",
        "conditions": "치매, 만성 노인 질환, 마비성 통증 완화",
        "specialty": "요양병원 재활",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "확인필요",
        "dayRehab": "확인필요",
        "address": "강원특별자치도 동해시 중앙로 218 (천곡동)",
        "phone": "033-531-2500",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "동해 천곡동 시내에 위치하여 접근성 우수. 기본적인 물리치료실과 노인 케어 서비스 제공."
    },
    {
        "id": "18",
        "district": "강릉시",
        "name": "강원특별자치도립강릉요양병원",
        "type": "요양병원",
        "inclusion": "공립 요양병원 재활",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "요양재활/입원재활",
        "conditions": "뇌졸중 만성 마비 요양, 파킨슨병, 중증 치매",
        "specialty": "도립 공공요양병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "강원특별자치도 강릉시 경강로 2007 (남문동)",
        "phone": "033-640-8800",
        "sources": "https://www.gwdgeriatric.or.kr/",
        "verification": "공식 홈페이지 확인",
        "notes": "강릉의료원 위탁 운영 도립요양병원. 재활의학과 협진을 통한 만성기 노인 재활 물리치료 특화."
    },
    {
        "id": "19",
        "district": "춘천시",
        "name": "권재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "근골격계 통증, 도수치료, 척추교정, 물리치료",
        "specialty": "통증재활 의원",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 춘천시 중앙로 104 (중앙로3가)",
        "phone": "033-244-3465",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "춘천 중앙로 시내 중심가 위치. 오랜 경험의 전문의가 상주하는 외래 중심의 대표적 통증/교정 의원."
    },
    {
        "id": "20",
        "district": "춘천시",
        "name": "리온재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "스포츠 손상 재활, 도수치료, 비수술적 통증 치료",
        "specialty": "비수술 통증재활 특화",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 춘천시 춘천로 188, 메가시티 4층 (효자동)",
        "phone": "033-241-3322",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "효자동 메가시티 빌딩 소재. 넓은 도수치료실 및 운동재활 시설을 보유한 정밀 통증 클리닉."
    },
    {
        "id": "21",
        "district": "춘천시",
        "name": "최병기재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "허리디스크 통증, 어깨 관절통, 도수 물리치료",
        "specialty": "통증재활 의원",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 춘천시 안마산로 36 (퇴계동)",
        "phone": "033-256-5559",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "퇴계동 CGV 인근 소재. 척추 협착, 퇴행성 관절염 통증 완화를 위한 전문 기계 물리치료실 가동."
    },
    {
        "id": "22",
        "district": "춘천시",
        "name": "김도훈재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "목·허리 디스크, 오십견, 체외충격파, 물리치료",
        "specialty": "통증재활 의원",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 춘천시 후석로 312 (후평동)",
        "phone": "033-253-6606",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "후평동 주거지역 중심지 위치. 지역 밀착형 통증 진료 및 다양한 물리치료 장비 구비."
    },
    {
        "id": "23",
        "district": "춘천시",
        "name": "우성재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "관절 마비 통증, 척추 측만증, 도수치료",
        "specialty": "통증재활 의원",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 춘천시 중앙로 67 (중앙로2가)",
        "phone": "033-257-5455",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "춘천 명동 인근 위치. 근골격계 통증 조기 관리 및 외래 소수 정예 도수치료."
    },
    {
        "id": "24",
        "district": "춘천시",
        "name": "중앙재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "신경통, 관절 연골 통증 완화, 초음파 유도하 주사",
        "specialty": "통증재활 의원",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 춘천시 금강로 68-9 (중앙로2가)",
        "phone": "033-254-7555",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "시내 중심상권 위치. 전문의의 정밀 진단 및 1:1 환자 맞춤형 통증 완화 물리치료 프로그램."
    },
    {
        "id": "25",
        "district": "원주시",
        "name": "연세준재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "자세 교정, 목·어깨 통증, 도수치료, 운동 재활",
        "specialty": "도수/체형 교정 전문",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "가능",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 원주시 지정면 신지정로 216, 6~7층 (기업도시)",
        "phone": "033-900-0847",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "원주 기업도시 내 위치. 대규모 도수 치료 및 체형 교정 운동시설 완비."
    },
    {
        "id": "26",
        "district": "원주시",
        "name": "다온재활의학과의원",
        "type": "focus",
        "type": "의원",
        "inclusion": "재활의학과 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "척추 신경통, 비수술 인대 강화 주사, 물리치료",
        "specialty": "통증재활 의원",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 원주시 능라동길 61, 정한타워 3층 (무실동)",
        "phone": "033-746-7500",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "무실동 중심가 위치. 쾌적한 물리치료 장비 및 체외충격파 집중 통증 케어."
    },
    {
        "id": "27",
        "district": "원주시",
        "name": "연세재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "신경통 완화, 마비 통증 케어, 디스크 외래 재활",
        "specialty": "원주 전통 통증재활 의원",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 원주시 감영길 11-3, 1~3층 (일산동)",
        "phone": "033-761-9119",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "원주 감영 인근 유서 깊은 재활의원. 노인 관절 질환 및 오랜 통증 환자를 위한 물리치료 집중."
    },
    {
        "id": "28",
        "district": "강릉시",
        "name": "세란재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "비수술적 척추 치료, 관절 물리치료, 도수치료",
        "specialty": "강릉 대표 재활의학과의원",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 강릉시 경강로 2120, 5층 (옥천동)",
        "phone": "033-648-7119",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "강릉 옥천오거리 인근 위치. 세심한 물리치료와 통증 치료로 지역 인지도 높음."
    },
    {
        "id": "29",
        "district": "강릉시",
        "name": "연세재활의학과의원",
        "type": "의원",
        "inclusion": "재활의학과 의원",
        "rehabDept": "있음",
        "specialists": "전문의 상주",
        "careType": "외래재활",
        "conditions": "스포츠 재활, 오십견, 퇴행성 척추질환 물리치료",
        "specialty": "통증재활 의원",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 강릉시 솔올로5번길 40, 3층 (교동)",
        "phone": "033-655-7522",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "교동 택지지구 내 위치. 현대식 인프라와 체계적인 도수치료 프로토콜 보유."
    },
    {
        "id": "30",
        "district": "홍천군",
        "name": "삼성마취통증의학과의원",
        "type": "의원",
        "inclusion": "지역 통증 및 물리치료 지원",
        "rehabDept": "확인필요",
        "specialists": "확인필요",
        "careType": "외래재활",
        "conditions": "근골격계 만성통증, 관절염 물리치료",
        "specialty": "마취통증의학과 / 물리치료실",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 홍천군 홍천읍 꽃뫼로 124",
        "phone": "033-435-3663",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "홍천읍 터미널 인근 위치. 근골격계 통증 조절 주사 및 기초 장비 물리치료 제공."
    },
    {
        "id": "31",
        "district": "홍천군",
        "name": "정성마취통증의학과의원",
        "type": "focus",
        "type": "의원",
        "inclusion": "지역 통증 및 물리치료 지원",
        "rehabDept": "확인필요",
        "specialists": "확인필요",
        "careType": "외래재활",
        "conditions": "허리 통증, 어깨 통증, 도수치료, 일반 물리치료",
        "specialty": "마취통증의학과 / 물리치료실",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 홍천군 홍천읍 홍천로 315",
        "phone": "033-432-7588",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "홍천읍 소재. 목/허리 통증 관리를 위한 비수술 치료와 온열 물리치료 제공."
    },
    {
        "id": "32",
        "district": "홍천군",
        "name": "박영록신경외과의원",
        "type": "의원",
        "inclusion": "지역 통증 및 물리치료 지원",
        "rehabDept": "확인필요",
        "specialists": "확인필요",
        "careType": "외래재활",
        "conditions": "디스크 관련 신경통, 관절 주사, 온열 물리치료",
        "specialty": "신경외과 / 물리치료실",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 홍천군 홍천읍 홍천로 366",
        "phone": "033-434-8275",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "신경외과 전문의 진료. 척추 신경 차단 주사 및 일반 물리치료 기기 운영."
    },
    {
        "id": "33",
        "district": "횡성군",
        "name": "이재형내과의원",
        "type": "의원",
        "inclusion": "지역 물리치료실 연동",
        "rehabDept": "확인필요",
        "specialists": "확인필요",
        "careType": "외래재활",
        "conditions": "만성 노인 관절통, 만성 질환 관리, 기본 온열치료",
        "specialty": "내과 / 물리치료실 병행",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 횡성군 횡성읍 한우로 306",
        "phone": "033-343-3636",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "횡성읍 위치. 내과 진료와 더불어 지역 어르신들을 위한 부설 물리치료실 운영."
    },
    {
        "id": "34",
        "district": "정선군",
        "name": "정선군립병원",
        "type": "병원",
        "inclusion": "지역 거점 공립병원 물리치료",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "외래/입원재활",
        "conditions": "수술 후 조기 거동 훈련, 통증 완화 물리치료",
        "specialty": "공립 거점병원 / 정형외과 물리치료실",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "강원특별자치도 정선군 사북읍 지장천로 727",
        "phone": "033-592-3121",
        "sources": "http://jsgh.or.kr/",
        "verification": "공식 홈페이지 확인",
        "notes": "정선군립 의료기관. 영농기 농업인 직업성 통증 및 수술 후 기본적인 재활 물리치료실 제공."
    },
    {
        "id": "35",
        "district": "철원군",
        "name": "철원병원",
        "type": "병원",
        "inclusion": "지역 종합병원급 물리치료",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "외래/입원재활",
        "conditions": "정형 수술 후 물리치료, 노인마비 요양",
        "specialty": "지역 거점 종합병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "강원특별자치도 철원군 갈말읍 명성로 208",
        "phone": "033-452-5011",
        "sources": "http://www.cheolwonhospital.co.kr/",
        "verification": "공식 홈페이지 확인",
        "notes": "철원 갈말읍 소재 거점 병원. 정형외과 진료와 연동한 집중식 통증 물리치료실 지원."
    },
    {
        "id": "36",
        "district": "평창군",
        "name": "평창의원",
        "type": "의원",
        "inclusion": "지역 물리치료실 운영",
        "rehabDept": "확인필요",
        "specialists": "확인필요",
        "careType": "외래재활",
        "conditions": "경증 요통, 오십견 물리치료",
        "specialty": "일반의원 / 물리치료실",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 평창군 평창읍 평창중앙로 47",
        "phone": "033-334-8877",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "평창읍 소재 로컬 의원. 지역 주민들의 급성/만성 통증에 대비한 물리치료 공간 구비."
    },
    {
        "id": "37",
        "district": "화천군",
        "name": "21세기바른정형외과의원",
        "type": "의원",
        "inclusion": "지역 정형외과 물리치료",
        "rehabDept": "확인필요",
        "specialists": "확인필요",
        "careType": "외래재활",
        "conditions": "뼈·관절 통증, 도수치료, 견인 물리치료",
        "specialty": "정형외과 / 도수치료",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 화천군 화천읍 중앙로 25",
        "phone": "033-441-8575",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "화천읍 소재 정형외과. 디스크 견인 기기 및 치료사가 상주하는 도수치료 지원."
    },
    {
        "id": "38",
        "district": "화천군",
        "name": "화천연세의원",
        "type": "의원",
        "inclusion": "지역 물리치료 지원",
        "rehabDept": "확인필요",
        "specialists": "확인필요",
        "careType": "외래재활",
        "conditions": "경증 척추 관절염, 만성 근육통 물리치료",
        "specialty": "일반의원 / 물리치료실",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 화천군 화천읍 중앙로2길 41-8",
        "phone": "033-441-3800",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "화천읍 주거지역 내 위치. 가벼운 기계 물리치료 중심 외래 운영."
    },
    {
        "id": "39",
        "district": "양구군",
        "name": "백두병원",
        "type": "병원",
        "inclusion": "지역 병원 물리치료",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "외래/입원재활",
        "conditions": "골절 수술 후 운동치료, 노인성 통증 제어",
        "specialty": "지역 거점 병원 / 정형물리치료",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "강원특별자치도 양구군 양구읍 금강산로 510",
        "phone": "033-481-9880",
        "sources": "http://www.baekduhosp.com/",
        "verification": "공식 홈페이지 확인",
        "notes": "양구읍 내 위치한 일반 병원. 수술 후 관절 가동 범위 회복을 위한 물리치료실 제공."
    },
    {
        "id": "40",
        "district": "양구군",
        "name": "양구우리병원",
        "type": "병원",
        "inclusion": "지역 병원 물리치료",
        "rehabDept": "확인필요",
        "specialists": "확인필요",
        "careType": "외래/입원재활",
        "conditions": "신경성 관절 통증, 온열/전기 물리치료",
        "specialty": "지역 일반병원",
        "recovery": "해당없음",
        "workersComp": "확인필요",
        "autoInsurance": "가능",
        "dayRehab": "확인필요",
        "address": "강원특별자치도 양구군 양구읍 정림리 188-3",
        "phone": "033-480-5172",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "양구 정림리 소재 일반 병원. 노령 환자 대상의 보조 물리치료 진료 지원."
    },
    {
        "id": "41",
        "district": "고성군",
        "name": "한마음의원",
        "type": "의원",
        "inclusion": "지역 물리치료 지원",
        "rehabDept": "있음(확인필요)",
        "specialists": "확인필요",
        "careType": "외래재활",
        "conditions": "노인성 관절 마비, 만성 요통 물리치료",
        "specialty": "재활의학과 과목 진료 / 물리치료실",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 고성군 간성읍 간성로 23",
        "phone": "033-681-9076",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "고성군 간성읍 중심지 위치. 고령층 만성 관절 통증 완화를 위한 기초 물리치료실 운영."
    },
    {
        "id": "42",
        "district": "양양군",
        "name": "양양정형외과의원",
        "type": "의원",
        "inclusion": "지역 정형외과 물리치료",
        "rehabDept": "확인필요",
        "specialists": "확인필요",
        "careType": "외래재활",
        "conditions": "퇴행성 마디 통증, 뼈 정형외과 도수, 물리치료",
        "specialty": "정형외과 / 물리치료실",
        "recovery": "해당없음",
        "workersComp": "해당없음",
        "autoInsurance": "확인필요",
        "dayRehab": "해당없음",
        "address": "강원특별자치도 양양군 양양읍 양양로 9-1",
        "phone": "033-672-6723",
        "sources": "https://www.hira.or.kr",
        "verification": "HIRA 확인",
        "notes": "양양읍 중심지 위치. 척추/관절 정형 수술 후 잔여 통증을 해결하기 위한 정기 물리치료실 운영."
    }
];
